package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 15} of event {@code FR_amendApplication}.
 */
public final class FRAmendApplicationPage15 {
    private FRAmendApplicationPage15() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("15");
        fields.mandatory(FinremCaseData::getAllocatedToBeHeardAtHighCourtJudgeLevel);
        fields.mandatory(FinremCaseData::getAllocatedToBeHeardAtHighCourtJudgeLevelText)
                    .fieldShowCondition("allocatedToBeHeardAtHighCourtJudgeLevel=\"Yes\"");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getSpecialAssistanceRequiredLabel).done();
        fields.optional(FinremCaseData::getSpecialAssistanceRequired);
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getSpecificArrangementsRequiredLabel).done();
        fields.optional(FinremCaseData::getSpecificArrangementsRequired);
        fields.mandatory(FinremCaseData::getIsApplicantsHomeCourt);
        fields.mandatory(FinremCaseData::getReasonForLocalCourt)
                    .fieldShowCondition("isApplicantsHomeCourt=\"Yes\"");
        fields.optional(FinremCaseData::getReasonForFrcLocation);
    }
}
