package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.NatureApplicationWrapper;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ScheduleOneWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 8} of event {@code FR_amendPaperApplication}.
 */
public final class FRAmendPaperApplicationPage8 {
    private FRAmendPaperApplicationPage8() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("8");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getNatureOfApplicationLabel).done();
        fields.complex(FinremCaseData::getNatureApplicationWrapper)
                    .mandatory(NatureApplicationWrapper::getNatureOfApplicationChecklist)
                    .fieldShowCondition("typeOfApplication=\"In connection to matrimonial and civil partnership proceedings\"").done();
        fields.complex(FinremCaseData::getScheduleOneWrapper)
                    .mandatory(ScheduleOneWrapper::getNatureOfApplicationChecklistSchedule)
                    .fieldShowCondition("typeOfApplication=\"Under paragraph 1 or 2 of schedule 1 children act 1989\"").done();
    }
}
