package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 25} of event {@code FR_amendApplication}.
 */
public final class FRAmendApplicationPage25 {
    private FRAmendApplicationPage25() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("25");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getVariationOrderDocumentLabel)
                    .fieldShowCondition("natureOfApplicationChecklist CONTAINS \"variationOrder\" OR natureOfApplicationChecklistSchedule CONTAINS \"variationOrder\"").done();
        fields.mandatory(FinremCaseData::getVariationOrderDocument)
                    .fieldShowCondition("natureOfApplicationChecklist CONTAINS \"variationOrder\" OR natureOfApplicationChecklistSchedule CONTAINS \"variationOrder\"");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getPromptForAnyDocumentLabel).done();
        fields.mandatory(FinremCaseData::getPromptForAnyDocument);
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getUploadOtherDocumentLabel)
                    .fieldShowCondition("promptForAnyDocument=\"Yes\"").done();
        fields.mandatory(FinremCaseData::getUploadAdditionalDocument)
                    .fieldShowCondition("promptForAnyDocument=\"Yes\"");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getUrgentCaseLabel).done();
        fields.mandatory(FinremCaseData::getPromptForUrgentCaseQuestion);
        fields.mandatory(FinremCaseData::getUrgentCaseQuestionDetailsTextArea)
                    .fieldShowCondition("promptForUrgentCaseQuestion=\"Yes\"");
    }
}
