package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ContactDetailsWrapper;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ScheduleOneWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code FR_amendApplication}.
 */
public final class FRAmendApplicationPage2 {
    private FRAmendApplicationPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("2");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getApplicantRepresentedLabel).done();
        fields.complex(FinremCaseData::getContactDetailsWrapper)
                    .mandatory(ContactDetailsWrapper::getApplicantRepresented).done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getApplicantSolicitorDetailLabel)
                    .fieldShowCondition("applicantRepresented=\"Yes\"").done();
        fields.complex(FinremCaseData::getContactDetailsWrapper)
                    .mandatory(ContactDetailsWrapper::getApplicantSolicitorName)
                    .fieldShowCondition("applicantRepresented=\"Yes\"").done();
        fields.complex(FinremCaseData::getContactDetailsWrapper)
                    .mandatory(ContactDetailsWrapper::getApplicantSolicitorFirm)
                    .fieldShowCondition("applicantRepresented=\"Yes\"")
                    .mandatory(ContactDetailsWrapper::getSolicitorReference)
                    .fieldShowCondition("applicantRepresented=\"Yes\"").done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getApplicantSolicitorAddressLabel)
                    .fieldShowCondition("applicantRepresented=\"Yes\"").done();
        fields.complex(FinremCaseData::getContactDetailsWrapper)
                    .mandatory(ContactDetailsWrapper::getApplicantSolicitorAddress)
                    .fieldShowCondition("applicantRepresented=\"Yes\"")
                    .mandatory(ContactDetailsWrapper::getApplicantSolicitorPhone)
                    .fieldShowCondition("applicantRepresented=\"Yes\"")
                    .mandatory(ContactDetailsWrapper::getApplicantSolicitorEmail)
                    .fieldShowCondition("applicantRepresented=\"Yes\"")
                    .optional(ContactDetailsWrapper::getApplicantSolicitorDxNumber)
                    .fieldShowCondition("applicantRepresented=\"Yes\"")
                    .mandatory(ContactDetailsWrapper::getApplicantSolicitorConsentForEmails)
                    .fieldShowCondition("applicantRepresented=\"Yes\"").done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getTypeOfApplicationLabel).done();
        fields.complex(FinremCaseData::getScheduleOneWrapper)
                    .readonly(ScheduleOneWrapper::getTypeOfApplication).done();
    }
}
