package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.wrapper.PaymentDetailsWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 3} of event {@code FR_applicationPaymentSubmission}.
 */
public final class FRApplicationPaymentSubmissionPage3 {
    private FRApplicationPaymentSubmissionPage3() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("3");
        fields.showCondition("helpWithFeesQuestion=\"Yes\"");
        fields.complex(FinremCaseData::getPaymentDetailsWrapper)
                    .mandatory(PaymentDetailsWrapper::getHwfNumber).done();
    }
}
