package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ConsentOrderWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code FR_consentOrder}.
 */
public final class FRConsentOrderPage2 {
    private FRConsentOrderPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("2");
        fields.pageLabel("Consent Order Application");
        fields.showCondition("consentNatureOfApplicationChecklist CONTAINS \"periodicalPaymentOrder\" OR consentNatureOfApplicationChecklistSchedule CONTAINS \"periodicalPaymentOrder\"");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getConsentOrderForChildrenQuestionLabel).done();
        fields.complex(FinremCaseData::getConsentOrderWrapper)
                    .mandatory(ConsentOrderWrapper::getConsentOrderForChildrenQuestion1)
                    .optional(ConsentOrderWrapper::getConsentNatureOfApplication5)
                    .fieldShowCondition("consentOrderForChildrenQuestion1=\"Yes\"")
                    .optional(ConsentOrderWrapper::getConsentNatureOfApplication6)
                    .fieldShowCondition("consentOrderForChildrenQuestion1=\"Yes\" AND consentNatureOfApplication5=\"No\"")
                    .optional(ConsentOrderWrapper::getConsentNatureOfApplication7)
                    .fieldShowCondition("consentOrderForChildrenQuestion1=\"Yes\" AND consentNatureOfApplication5=\"No\"").done();
    }
}
