package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.OrderRefusalHolder;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code FR_consentOrderNotApproved}.
 */
public final class FRConsentOrderNotApprovedPage1 {
    private FRConsentOrderNotApprovedPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("1");
        fields.complex(FinremCaseData::getOrderRefusalOnScreen)
                    .optional(OrderRefusalHolder::getOrderRefusalAfterText)
                    .eventLabel("AND AFTER")
                    .noHintText()
                    .mandatory(OrderRefusalHolder::getOrderRefusal)
                    .eventLabel("Reason for Refusal")
                    .noHintText()
                    .optional(OrderRefusalHolder::getOrderRefusalOther)
                    .eventLabel("Other (please specify)")
                    .noHintText()
                    .mandatory(OrderRefusalHolder::getOrderRefusalJudge)
                    .eventLabel("Select Judge")
                    .noHintText()
                    .mandatory(OrderRefusalHolder::getOrderRefusalJudgeName)
                    .eventLabel("Name of Judge")
                    .noHintText()
                    .mandatory(OrderRefusalHolder::getOrderRefusalDate)
                    .eventLabel("Date of order")
                    .optional(OrderRefusalHolder::getOrderRefusalAddComments)
                    .eventLabel("Additional comments")
                    .noHintText().done();
    }
}
