package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.DraftOrdersWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code FR_draftOrders}.
 */
public final class FRDraftOrdersPage1 {
    private FRDraftOrdersPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("1");
        fields.pageLabel("Upload draft orders");
        fields.complex(FinremCaseData::getDraftOrdersWrapper)
                    .mandatory(DraftOrdersWrapper::getTypeOfDraftOrder)
                    .mandatoryNoSummary(DraftOrdersWrapper::getShowUploadPartyQuestion)
                    .fieldShowCondition("typeOfDraftOrder=\"never show\"")
                    .retainHiddenValue().done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getUploadDraftOrdersDisputesGuidance)
                    .readonly(CaseDataExtra::getGeneralApplicationGuidance)
                    .fieldShowCondition("[STATE]=\"applicationIssued\" OR [STATE]=\"schedulingAndHearing\" OR [STATE]=\"prepareForHearing\" OR [STATE]=\"solicitorDraftOrder\" OR [STATE]=\"judgeDraftOrder\" OR [STATE]=\"draftOrderNotApproved\" OR [STATE]=\"scheduleRaiseDirectionsOrder\" OR [STATE]=\"orderDrawn\" OR [STATE]=\"caseWorkerReview\" OR [STATE]=\"gateKeepingAndAllocation\" OR [STATE]=\"caseFileSubmitted\" OR [STATE]=\"reviewOrder\" OR [STATE]=\"awaitingJudiciaryResponse\" OR [STATE]=\"close\" OR [STATE]=\"orderSent\" OR [STATE]=\"generalApplication\" OR [STATE]=\"generalApplicationOutcome\"").done();
        fields.complex(FinremCaseData::getDraftOrdersWrapper)
                    .mandatory(DraftOrdersWrapper::getConsentApplicationGuidanceText)
                    .fieldShowCondition("generalApplicationGuidance=\"DONOTSHOW\"").done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getConsentApplicationGuidance).done();
    }
}
