package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.GeneralOrderWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code FR_generalOrderConsent}.
 */
public final class FRGeneralOrderConsentPage1 {
    private FRGeneralOrderConsentPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("1");
        fields.complex(FinremCaseData::getGeneralOrderWrapper)
                    .mandatoryNoSummary(GeneralOrderWrapper::getGeneralOrderCreatedBy)
                    .optionalNoSummary(GeneralOrderWrapper::getGeneralOrderRecitals)
                    .mandatoryNoSummary(GeneralOrderWrapper::getGeneralOrderJudgeType)
                    .mandatoryNoSummary(GeneralOrderWrapper::getGeneralOrderJudgeName)
                    .mandatoryNoSummary(GeneralOrderWrapper::getGeneralOrderDate)
                    .mandatoryNoSummary(GeneralOrderWrapper::getGeneralOrderBodyText).done();
    }
}
