package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.BarristerCollectionWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 3} of event {@code FR_manageBarrister}.
 */
public final class FRManageBarristerPage3 {
    private FRManageBarristerPage3() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("3");
        fields.pageLabel("Manage Barrister");
        fields.showCondition("currentUserCaseRoleLabel=\"RESPSOLICITOR\" OR barristerParty=\"respondent\"");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getRespBarristerCollectionLabel).done();
        fields.complex(FinremCaseData::getBarristerCollectionWrapper)
                    .complexMember(BarristerCollectionWrapper::getRespondentBarristers).done();
        fields.optionalNoSummary(FinremCaseData::getCurrentUserCaseRole)
                    .fieldShowCondition("appBarristerCollection=\"IMPOSSIBLE_VALUE\"");
        fields.optionalNoSummary(FinremCaseData::getCurrentUserCaseRoleLabel)
                    .fieldShowCondition("appBarristerCollection=\"IMPOSSIBLE_VALUE\"");
    }
}
