package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ExpressCaseWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 15} of event {@code FR_newPaperCase}.
 */
public final class FRNewPaperCasePage15 {
    private FRNewPaperCasePage15() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("15");
        fields.showCondition("expressCaseParticipation=\"Enrolled\"");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getSuitableForExpressCaseLabel).done();
        fields.complex(FinremCaseData::getExpressCaseWrapper)
                    .optionalNoSummary(ExpressCaseWrapper::getExpressCaseParticipation)
                    .fieldShowCondition("suitableForExpressCaseLabel=\"IMPOSSIBLE\"")
                    .retainHiddenValue().done();
    }
}
