package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.MiamWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 18} of event {@code FR_newPaperCase}.
 */
public final class FRNewPaperCasePage18 {
    private FRNewPaperCasePage18() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("18");
        fields.showCondition("claimingExemptionMIAM=\"Yes\" AND applicantAttendedMIAM=\"No\" AND  MIAMExemptionsChecklist  CONTAINS \"domesticViolence\"");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getMIAMDomesticViolenceLabel)
                    .readonly(CaseDataExtra::getMIAMDomesticViolenceSelectAll).done();
        fields.complex(FinremCaseData::getMiamWrapper)
                    .mandatory(MiamWrapper::getMiamDomesticViolenceChecklist).done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getEvidenceUnavailableDomesticAbuseMIAMLabel).done();
        fields.complex(FinremCaseData::getMiamWrapper)
                    .optional(MiamWrapper::getEvidenceUnavailableDomesticAbuseMiam).done();
    }
}
