package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ContactDetailsWrapper;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.RefugeWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 6} of event {@code FR_newPaperCase}.
 */
public final class FRNewPaperCasePage6 {
    private FRNewPaperCasePage6() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("6");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getRespondentRepresentedLabel).done();
        fields.complex(FinremCaseData::getContactDetailsWrapper)
                    .mandatory(ContactDetailsWrapper::getContestedRespondentRepresented).done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getRSolicitorLabel)
                    .fieldShowCondition("respondentRepresented=\"Yes\"").done();
        fields.complex(FinremCaseData::getContactDetailsWrapper)
                    .optional(ContactDetailsWrapper::getRespondentSolicitorName)
                    .fieldShowCondition("respondentRepresented=\"Yes\"")
                    .optional(ContactDetailsWrapper::getRespondentSolicitorReference)
                    .fieldShowCondition("respondentRepresented=\"Yes\"")
                    .mandatory(ContactDetailsWrapper::getRespondentSolicitorFirm)
                    .fieldShowCondition("respondentRepresented=\"Yes\"").done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getRSolicitorAddressLabel)
                    .fieldShowCondition("respondentRepresented=\"Yes\"").done();
        fields.complex(FinremCaseData::getContactDetailsWrapper)
                    .mandatory(ContactDetailsWrapper::getRespondentSolicitorAddress)
                    .fieldShowCondition("respondentRepresented=\"Yes\"")
                    .mandatory(ContactDetailsWrapper::getRespondentSolicitorPhone)
                    .fieldShowCondition("respondentRepresented=\"Yes\"")
                    .mandatory(ContactDetailsWrapper::getRespondentSolicitorEmail)
                    .fieldShowCondition("respondentRepresented=\"Yes\"")
                    .optional(ContactDetailsWrapper::getRespondentSolicitorDxNumber)
                    .fieldShowCondition("respondentRepresented=\"Yes\"").done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getRRespondentLabel2)
                    .fieldShowCondition("respondentRepresented=\"No\"").done();
        fields.complex(FinremCaseData::getContactDetailsWrapper)
                    .optional(ContactDetailsWrapper::getRespondentResideOutsideUK)
                    .fieldShowCondition("respondentRepresented=\"No\"")
                    .mandatory(ContactDetailsWrapper::getRespondentAddress)
                    .fieldShowCondition("respondentRepresented=\"No\"")
                    .optional(ContactDetailsWrapper::getRespondentPhone)
                    .fieldShowCondition("respondentRepresented=\"No\"")
                    .optional(ContactDetailsWrapper::getRespondentEmail)
                    .fieldShowCondition("respondentRepresented=\"No\"")
                    .mandatory(ContactDetailsWrapper::getRespondentAddressHiddenFromApplicant)
                    .fieldShowCondition("respondentRepresented=\"No\"").done();
        fields.complex(FinremCaseData::getRefugeWrapper)
                    .optional(RefugeWrapper::getRespondentInRefugeQuestion).done();
    }
}
