package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ConsentOrderWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 3} of event {@code FR_respondToConsentOrder}.
 */
public final class FRRespondToConsentOrderPage3 {
    private FRRespondToConsentOrderPage3() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("3");
        fields.pageLabel("Consent Order Application");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getConsentD81Label).done();
        fields.complex(FinremCaseData::getConsentOrderWrapper)
                    .mandatory(ConsentOrderWrapper::getConsentD81Question)
                    .mandatory(ConsentOrderWrapper::getConsentD81Joint)
                    .fieldShowCondition("consentD81Question=\"Yes\"")
                    .mandatory(ConsentOrderWrapper::getConsentD81Applicant)
                    .fieldShowCondition("consentD81Question=\"No\"")
                    .mandatory(ConsentOrderWrapper::getConsentD81Respondent)
                    .fieldShowCondition("consentD81Question=\"No\"").done();
    }
}
