package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ConsentOrderWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 25} of event {@code FR_solicitorCreate}.
 */
public final class FRSolicitorCreatePage25 {
    private FRSolicitorCreatePage25() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("25");
        fields.pageLabel("Consent Order Application");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getBeforeSavePreConfirmation).done();
        fields.complex(FinremCaseData::getConsentOrderWrapper)
                    .readonlyNoSummary(ConsentOrderWrapper::getConsentOrderFrcName)
                    .readonlyNoSummary(ConsentOrderWrapper::getConsentOrderFrcAddress)
                    .readonlyNoSummary(ConsentOrderWrapper::getConsentOrderFrcEmail)
                    .readonlyNoSummary(ConsentOrderWrapper::getConsentOrderFrcPhone).done();
    }
}
