package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 3} of event {@code FR_solicitorCreate}.
 */
public final class FRSolicitorCreatePage3 {
    private FRSolicitorCreatePage3() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("3");
        fields.showCondition("typeOfApplication=\"In connection to matrimonial and civil partnership proceedings\"");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getDivorceDetailsLabel).done();
        fields.mandatory(FinremCaseData::getDivorceCaseNumber);
        fields.mandatory(FinremCaseData::getCivilPartnership);
        fields.mandatory(FinremCaseData::getDateOfMarriage);
        fields.optional(FinremCaseData::getDateOfSepration);
        fields.mandatory(FinremCaseData::getDivorcePetitionIssuedDate);
        fields.mandatory(FinremCaseData::getNameOfCourtDivorceCentre);
        fields.mandatory(FinremCaseData::getDivorceStageReached);
        fields.mandatory(FinremCaseData::getDivorceUploadEvidence1)
                    .fieldShowCondition("divorceStageReached=\"Decree Nisi\"");
        fields.mandatory(FinremCaseData::getDivorceDecreeNisiDate)
                    .fieldShowCondition("divorceStageReached=\"Decree Nisi\"");
        fields.mandatory(FinremCaseData::getDivorceUploadEvidence2)
                    .fieldShowCondition("divorceStageReached=\"Decree Absolute\"");
        fields.mandatory(FinremCaseData::getDivorceDecreeAbsoluteDate)
                    .fieldShowCondition("divorceStageReached=\"Decree Absolute\"");
        fields.mandatory(FinremCaseData::getDivorceUploadPetition)
                    .fieldShowCondition("divorceStageReached=\"Petition Issued\"");
    }
}
