package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 13} of event {@code FR_solicitorCreate}.
 */
public final class FRSolicitorCreatePage13 {
    private FRSolicitorCreatePage13() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("13");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getFastTrackDecisionLabel).done();
        fields.mandatory(FinremCaseData::getFastTrackDecision);
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getFastTrackDecisionReasonLabel)
                    .fieldShowCondition("fastTrackDecision=\"Yes\"").done();
        fields.mandatory(FinremCaseData::getFastTrackDecisionReason)
                    .fieldShowCondition("fastTrackDecision=\"Yes\"");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getFastTrackMoreInfoContent1).done();
    }
}
