package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ContactDetailsWrapper;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.RefugeWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 3} of event {@code FR_updateContactDetails}.
 */
public final class FRUpdateContactDetailsPage3 {
    private FRUpdateContactDetailsPage3() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("3");
        fields.showCondition("updateIncludesRepresentativeChange=\"No\" OR nocParty=\"applicant\"");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getApplicantDetailsLabel).done();
        fields.complex(FinremCaseData::getContactDetailsWrapper)
                    .mandatory(ContactDetailsWrapper::getApplicantFmName)
                    .mandatory(ContactDetailsWrapper::getApplicantLname).done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getApplicantContactLabel).done();
        fields.complex(FinremCaseData::getContactDetailsWrapper)
                    .optional(ContactDetailsWrapper::getApplicantResideOutsideUK)
                    .mandatory(ContactDetailsWrapper::getApplicantAddress)
                    .optional(ContactDetailsWrapper::getApplicantPhone)
                    .optional(ContactDetailsWrapper::getApplicantEmail)
                    .optional(ContactDetailsWrapper::getApplicantAddressHiddenFromRespondent).done();
        fields.complex(FinremCaseData::getRefugeWrapper)
                    .optional(RefugeWrapper::getApplicantInRefugeQuestion).done();
    }
}
