package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ContactDetailsWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code FR_updateCaseDetailsSolicitor}.
 */
public final class FRUpdateCaseDetailsSolicitorPage1 {
    private FRUpdateCaseDetailsSolicitorPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("1");
        fields.showCondition("currentUserIsApplicantSolicitor=\"Yes\"");
        fields.complex(FinremCaseData::getContactDetailsWrapper)
                    .mandatory(ContactDetailsWrapper::getApplicantSolicitorName)
                    .optional(ContactDetailsWrapper::getSolicitorReference).done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getApplicantSolicitorAddressLabel).done();
        fields.complex(FinremCaseData::getContactDetailsWrapper)
                    .mandatory(ContactDetailsWrapper::getApplicantSolicitorAddress)
                    .mandatory(ContactDetailsWrapper::getApplicantSolicitorPhone)
                    .mandatory(ContactDetailsWrapper::getApplicantSolicitorEmail)
                    .readonly(ContactDetailsWrapper::getCurrentUserIsApplicantSolicitor)
                    .fieldShowCondition("applicantSolicitorAddressLabel=\" \"")
                    .retainHiddenValue().done();
    }
}
