package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ContactDetailsWrapper;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.RefugeWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 5} of event {@code FR_updateContactDetails}.
 */
public final class FRUpdateContactDetailsPage5 {
    private FRUpdateContactDetailsPage5() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("5");
        fields.showCondition("updateIncludesRepresentativeChange=\"No\" OR nocParty=\"respondent\"");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getRespondentDetailsLabel).done();
        fields.complex(FinremCaseData::getContactDetailsWrapper)
                    .mandatory(ContactDetailsWrapper::getRespondentFmName)
                    .mandatory(ContactDetailsWrapper::getRespondentLname).done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getRRespondentLabel2)
                    .fieldShowCondition("respondentRepresented=\"No\"").done();
        fields.complex(FinremCaseData::getContactDetailsWrapper)
                    .optional(ContactDetailsWrapper::getRespondentResideOutsideUK)
                    .fieldShowCondition("respondentRepresented=\"No\"")
                    .mandatory(ContactDetailsWrapper::getRespondentAddress)
                    .fieldShowCondition("respondentRepresented=\"No\"")
                    .optional(ContactDetailsWrapper::getRespondentPhone)
                    .fieldShowCondition("respondentRepresented=\"No\"")
                    .optional(ContactDetailsWrapper::getRespondentEmail)
                    .fieldShowCondition("respondentRepresented=\"No\"")
                    .optional(ContactDetailsWrapper::getRespondentAddressHiddenFromApplicant)
                    .fieldShowCondition("respondentRepresented=\"No\"").done();
        fields.complex(FinremCaseData::getRefugeWrapper)
                    .optional(RefugeWrapper::getRespondentInRefugeQuestion).done();
    }
}
