package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.Address;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.Organisation;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.OrganisationPolicy;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.IntervenerFour;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Wizard page {@code 9} of event {@code manageInterveners}.
 */
public final class ManageIntervenersPage9 {
    private ManageIntervenersPage9() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<FinremCaseData, CcdState, Event.EventBuilder<FinremCaseData, UserRole, CcdState>> fields) {
        fields.page("9");
        fields.showCondition("intervenerOptionList=\"addIntervener4\"");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getIntervener4Label).done();
        fields.complex(FinremCaseData::getIntervenerFour)
                    .mandatory(IntervenerFour::getIntervenerName)
                    .eventLabel("Intervener's Full Name")
                    .optional(IntervenerFour::getIntervenerResideOutsideUK)
                    .eventLabel("Does the intervener live outside of the UK?")
                    .mandatory(IntervenerFour::getIntervenerAddress)
                    .eventLabel("Intervener's Address")
                    .complex(IntervenerFour::getIntervenerAddress)
                    .mandatory(Address::getAddressLine1)
                    .eventLabel("Building and Street").done()
                    .complex(IntervenerFour::getIntervenerAddress)
                    .optional(Address::getAddressLine2).done()
                    .complex(IntervenerFour::getIntervenerAddress)
                    .optional(Address::getAddressLine3).done()
                    .complex(IntervenerFour::getIntervenerAddress)
                    .optional(Address::getPostTown)
                    .eventLabel("Town or City").done()
                    .complex(IntervenerFour::getIntervenerAddress)
                    .optional(Address::getCounty)
                    .eventLabel("County").done()
                    .complex(IntervenerFour::getIntervenerAddress)
                    .optional(Address::getCountry)
                    .eventLabel("Country").done()
                    .complex(IntervenerFour::getIntervenerAddress)
                    .mandatory(Address::getPostCode)
                    .eventLabel("Postcode").done()
                    .optional(IntervenerFour::getIntervenerEmail)
                    .eventLabel("Email address")
                    .optional(IntervenerFour::getIntervenerPhone)
                    .eventLabel("Phone number")
                    .optional(IntervenerFour::getIntervenerAddressConfidential)
                    .eventLabel("Keep the Intervener's contact details private from the Applicant & Respondent?")
                    .optional(IntervenerFour::getIntervenerInRefuge)
                    .eventLabel("Is the intervener currently a resident in a refuge?")
                    .mandatory(IntervenerFour::getIntervenerRepresented)
                    .eventLabel("Is the Intervener represented ?")
                    .mandatory(IntervenerFour::getIntervenerDateAdded)
                    .fieldShowCondition("intervener4.intervenerRepresented=\"Both\"")
                    .eventLabel("Date added")
                    .mandatory(IntervenerFour::getIntervenerSolName)
                    .fieldShowCondition("intervener4.intervenerRepresented=\"Yes\"")
                    .eventLabel("Representative's Full Name")
                    .mandatory(IntervenerFour::getIntervenerSolEmail)
                    .fieldShowCondition("intervener4.intervenerRepresented=\"Yes\"")
                    .eventLabel("Representative's Email")
                    .optional(IntervenerFour::getIntervenerSolPhone)
                    .fieldShowCondition("intervener4.intervenerRepresented=\"Yes\"")
                    .eventLabel("Representative's Phone Number")
                    .mandatory(IntervenerFour::getIntervenerSolicitorFirm)
                    .fieldShowCondition("intervener4.intervenerRepresented=\"Yes\"")
                    .eventLabel("Representative Firm")
                    .mandatory(IntervenerFour::getIntervenerSolicitorReference)
                    .fieldShowCondition("intervener4.intervenerRepresented=\"Yes\"")
                    .eventLabel("Your Reference")
                    .complex(IntervenerFour::getIntervenerOrganisation)
                    .optional(OrganisationPolicy::getOrgPolicyCaseAssignedRole)
                    .fieldShowCondition("divorceCaseNumber=\"IMPOSSIBLAW\"")
                    .eventLabel("Organisation Policy").done()
                    .complex(IntervenerFour::getIntervenerOrganisation)
                    .complex(OrganisationPolicy::getOrganisation)
                    .mandatory(Organisation::getOrganisationID).done().done()
                    .complex(IntervenerFour::getIntervenerOrganisation)
                    .optional(OrganisationPolicy::getOrgPolicyReference).done().done();
    }
}
