language: java
jdk: openjdk11

services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_install:
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew check
  - ./gradlew test
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)