package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.AttachScannedDocsPage1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.AttachScannedDocsPage2;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code attachScannedDocs} for case type {@code FinancialRemedyContested}.
 */
@Component
public class AttachScannedDocs implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ATTACH_SCANNED_DOCS = "attachScannedDocs";

    /**
     * Registers event {@code attachScannedDocs}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(ATTACH_SCANNED_DOCS)
            .forAllStates()
            .name("Attach scanned docs")
            .displayOrder(107)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_SYSTEMUPDATE)
            .fields();
        AttachScannedDocsPage1.apply(fields);
        AttachScannedDocsPage2.apply(fields);
    }
}
