package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code attachScannedDocsWithOcr} for case type {@code FinancialRemedyContested}.
 */
@Component
public class AttachScannedDocsWithOcr implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ATTACH_SCANNED_DOCS_WITH_OCR = "attachScannedDocsWithOcr";

    /**
     * Registers event {@code attachScannedDocsWithOcr}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        builder.event(ATTACH_SCANNED_DOCS_WITH_OCR)
            .forAllStates()
            .name("Bulk Scanning - Case Update")
            .description("Update a case adding additional data from scanned documents to an existing case")
            .displayOrder(111)
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_BULKSCAN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR);
    }
}
