package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code clearRespondentPolicy} for case type {@code FinancialRemedyContested}.
 */
@Component
public class ClearRespondentPolicy implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CLEAR_RESPONDENT_POLICY = "clearRespondentPolicy";

    /**
     * Registers event {@code clearRespondentPolicy}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(CLEAR_RESPONDENT_POLICY)
            .forAllStates()
            .name("Clear Respondent Policy")
            .description("Clear Respondent Policy - when respondent organisation not valid any more for some reason")
            .displayOrder(151)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SUPERUSER)
            .fields();
        fields.page("1");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getCautionMessage).done();
    }
}
