package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.CaseFlagsWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code createFlags} for case type {@code FinancialRemedyContested}.
 */
@Component
public class CreateFlags implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_FLAGS = "createFlags";

    /**
     * Registers event {@code createFlags}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(CREATE_FLAGS)
            .forAllStates()
            .name("Create Flag")
            .description("Create Case Flag")
            .displayOrder(135)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY)
            .fields();
        fields.page("1");
        fields.complex(FinremCaseData::getCaseFlagsWrapper)
                    .optional(CaseFlagsWrapper::getCaseFlags)
                    .fieldShowCondition("[STATE]=\"IMPOSSIBLE\"")
                    .retainHiddenValue()
                    .optional(CaseFlagsWrapper::getApplicantFlags)
                    .fieldShowCondition("[STATE]=\"IMPOSSIBLE\"")
                    .retainHiddenValue()
                    .optional(CaseFlagsWrapper::getRespondentFlags)
                    .fieldShowCondition("[STATE]=\"IMPOSSIBLE\"")
                    .retainHiddenValue().done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .mandatory(CaseDataExtra::getFlagLauncher)
                    .displayContextParameter("#ARGUMENT(CREATE)").done();
    }
}
