package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.CreateGeneralApplicationPage1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.CreateGeneralApplicationPage2;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.CreateGeneralApplicationPage3;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.CreateGeneralApplicationPage4;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.CreateGeneralApplicationPage5;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.CreateGeneralApplicationPage6;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.GeneralApplicationItems;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.GeneralApplicationSuportingDocumentItems;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.GeneralApplicationWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code createGeneralApplication} for case type {@code FinancialRemedyContested}.
 */
@Component
public class CreateGeneralApplication implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_GENERAL_APPLICATION = "createGeneralApplication";

    /**
     * Registers event {@code createGeneralApplication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(CREATE_GENERAL_APPLICATION)
            .forStateTransition(EnumSet.of(CcdState.applicationIssued, CcdState.schedulingAndHearing, CcdState.prepareForHearing, CcdState.solicitorDraftOrder, CcdState.judgeDraftOrder, CcdState.draftOrderNotApproved, CcdState.scheduleRaiseDirectionsOrder, CcdState.orderDrawn, CcdState.caseWorkerReview, CcdState.gateKeepingAndAllocation, CcdState.caseFileSubmitted, CcdState.reviewOrder, CcdState.awaitingJudiciaryResponse, CcdState.close, CcdState.orderSent, CcdState.generalApplication, CcdState.generalApplicationOutcome), CcdState.generalApplication)
            .name("Create General Application")
            .displayOrder(124)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY)
            .fields();
        CreateGeneralApplicationPage1.apply(fields);
        CreateGeneralApplicationPage2.apply(fields);
        CreateGeneralApplicationPage3.apply(fields);
        CreateGeneralApplicationPage4.apply(fields);
        CreateGeneralApplicationPage5.apply(fields);
        CreateGeneralApplicationPage6.apply(fields);
        fields.complex(FinremCaseData::getGeneralApplicationWrapper)
                    .complex(GeneralApplicationWrapper::getGeneralApplications, GeneralApplicationItems.class)
                    .optional(GeneralApplicationItems::getGeneralApplicationReceivedFrom)
                    .fieldShowCondition("generalApplicationReceivedFrom=\"IMPOSSIBLE\"")
                    .mandatory(GeneralApplicationItems::getGeneralApplicationSender)
                    .mandatory(GeneralApplicationItems::getAppRespGeneralApplicationReceivedFrom)
                    .fieldShowCondition("appRespGeneralApplicationReceivedFrom=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationCreatedBy)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .mandatory(GeneralApplicationItems::getGeneralApplicationHearingRequired)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationTimeEstimate)
                    .fieldShowCondition("generalApplications.generalApplicationHearingRequired=\"Yes\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationSpecialMeasures)
                    .fieldShowCondition("generalApplications.generalApplicationHearingRequired=\"Yes\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationDraftOrder)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationDocument)
                    .complex(GeneralApplicationItems::getGaSupportDocuments, GeneralApplicationSuportingDocumentItems.class)
                    .optional(GeneralApplicationSuportingDocumentItems::getSupportDocument).done()
                    .optional(GeneralApplicationItems::getGeneralApplicationCreatedDate)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationStatus)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationOutcomeOther)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationDirectionsDocument)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"").done().done();
        fields.complex(FinremCaseData::getGeneralApplicationWrapper)
                    .complex(GeneralApplicationWrapper::getIntervener1GeneralApplications, GeneralApplicationItems.class)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationReceivedFrom)
                    .fieldShowCondition("generalApplicationReceivedFrom=\"IMPOSSIBLE\"")
                    .mandatory(GeneralApplicationItems::getGeneralApplicationSender)
                    .fieldShowCondition("generalApplicationReceivedFrom=\"IMPOSSIBLE\"")
                    .mandatory(GeneralApplicationItems::getAppRespGeneralApplicationReceivedFrom)
                    .fieldShowCondition("appRespGeneralApplicationReceivedFrom=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationCreatedBy)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .mandatory(GeneralApplicationItems::getGeneralApplicationHearingRequired)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationTimeEstimate)
                    .fieldShowCondition("intervener1GeneralApplications.generalApplicationHearingRequired=\"Yes\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationSpecialMeasures)
                    .fieldShowCondition("intervener1GeneralApplications.generalApplicationHearingRequired=\"Yes\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationDraftOrder)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationDocument)
                    .complex(GeneralApplicationItems::getGaSupportDocuments, GeneralApplicationSuportingDocumentItems.class)
                    .optional(GeneralApplicationSuportingDocumentItems::getSupportDocument).done()
                    .optional(GeneralApplicationItems::getGeneralApplicationCreatedDate)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationStatus)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationOutcomeOther)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationDirectionsDocument)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"").done().done();
        fields.complex(FinremCaseData::getGeneralApplicationWrapper)
                    .complex(GeneralApplicationWrapper::getIntervener2GeneralApplications, GeneralApplicationItems.class)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationReceivedFrom)
                    .fieldShowCondition("generalApplicationReceivedFrom=\"IMPOSSIBLE\"")
                    .mandatory(GeneralApplicationItems::getGeneralApplicationSender)
                    .fieldShowCondition("generalApplicationReceivedFrom=\"IMPOSSIBLE\"")
                    .mandatory(GeneralApplicationItems::getAppRespGeneralApplicationReceivedFrom)
                    .fieldShowCondition("appRespGeneralApplicationReceivedFrom=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationCreatedBy)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .mandatory(GeneralApplicationItems::getGeneralApplicationHearingRequired)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationTimeEstimate)
                    .fieldShowCondition("intervener2GeneralApplications.generalApplicationHearingRequired=\"Yes\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationSpecialMeasures)
                    .fieldShowCondition("intervener2GeneralApplications.generalApplicationHearingRequired=\"Yes\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationDraftOrder)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationDocument)
                    .complex(GeneralApplicationItems::getGaSupportDocuments, GeneralApplicationSuportingDocumentItems.class)
                    .optional(GeneralApplicationSuportingDocumentItems::getSupportDocument).done()
                    .optional(GeneralApplicationItems::getGeneralApplicationCreatedDate)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationStatus)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationOutcomeOther)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationDirectionsDocument)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"").done().done();
        fields.complex(FinremCaseData::getGeneralApplicationWrapper)
                    .complex(GeneralApplicationWrapper::getIntervener3GeneralApplications, GeneralApplicationItems.class)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationReceivedFrom)
                    .fieldShowCondition("generalApplicationReceivedFrom=\"IMPOSSIBLE\"")
                    .mandatory(GeneralApplicationItems::getGeneralApplicationSender)
                    .fieldShowCondition("generalApplicationReceivedFrom=\"IMPOSSIBLE\"")
                    .mandatory(GeneralApplicationItems::getAppRespGeneralApplicationReceivedFrom)
                    .fieldShowCondition("appRespGeneralApplicationReceivedFrom=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationCreatedBy)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .mandatory(GeneralApplicationItems::getGeneralApplicationHearingRequired)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationTimeEstimate)
                    .fieldShowCondition("intervener3GeneralApplications.generalApplicationHearingRequired=\"Yes\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationSpecialMeasures)
                    .fieldShowCondition("intervener3GeneralApplications.generalApplicationHearingRequired=\"Yes\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationDraftOrder)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationDocument)
                    .complex(GeneralApplicationItems::getGaSupportDocuments, GeneralApplicationSuportingDocumentItems.class)
                    .optional(GeneralApplicationSuportingDocumentItems::getSupportDocument).done()
                    .optional(GeneralApplicationItems::getGeneralApplicationCreatedDate)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationStatus)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationOutcomeOther)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationDirectionsDocument)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"").done().done();
        fields.complex(FinremCaseData::getGeneralApplicationWrapper)
                    .complex(GeneralApplicationWrapper::getIntervener4GeneralApplications, GeneralApplicationItems.class)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationReceivedFrom)
                    .fieldShowCondition("generalApplicationReceivedFrom=\"IMPOSSIBLE\"")
                    .mandatory(GeneralApplicationItems::getGeneralApplicationSender)
                    .fieldShowCondition("generalApplicationReceivedFrom=\"IMPOSSIBLE\"")
                    .mandatory(GeneralApplicationItems::getAppRespGeneralApplicationReceivedFrom)
                    .fieldShowCondition("appRespGeneralApplicationReceivedFrom=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationCreatedBy)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .mandatory(GeneralApplicationItems::getGeneralApplicationHearingRequired)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationTimeEstimate)
                    .fieldShowCondition("intervener4GeneralApplications.generalApplicationHearingRequired=\"Yes\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationSpecialMeasures)
                    .fieldShowCondition("intervener4GeneralApplications.generalApplicationHearingRequired=\"Yes\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationDraftOrder)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationDocument)
                    .complex(GeneralApplicationItems::getGaSupportDocuments, GeneralApplicationSuportingDocumentItems.class)
                    .optional(GeneralApplicationSuportingDocumentItems::getSupportDocument).done()
                    .optional(GeneralApplicationItems::getGeneralApplicationCreatedDate)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationStatus)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationOutcomeOther)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationDirectionsDocument)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"").done().done();
        fields.complex(FinremCaseData::getGeneralApplicationWrapper)
                    .complex(GeneralApplicationWrapper::getAppRespGeneralApplications, GeneralApplicationItems.class)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationReceivedFrom)
                    .fieldShowCondition("currentUserCaseRoleType=\"case\"")
                    .mandatory(GeneralApplicationItems::getGeneralApplicationSender)
                    .fieldShowCondition("currentUserCaseRoleType=\"case\"")
                    .mandatory(GeneralApplicationItems::getAppRespGeneralApplicationReceivedFrom)
                    .optional(GeneralApplicationItems::getGeneralApplicationCreatedBy)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .mandatory(GeneralApplicationItems::getGeneralApplicationHearingRequired)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationTimeEstimate)
                    .fieldShowCondition("appRespGeneralApplications.generalApplicationHearingRequired=\"Yes\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationSpecialMeasures)
                    .fieldShowCondition("appRespGeneralApplications.generalApplicationHearingRequired=\"Yes\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationDraftOrder)
                    .mandatory(GeneralApplicationItems::getGeneralApplicationDocument)
                    .complex(GeneralApplicationItems::getGaSupportDocuments, GeneralApplicationSuportingDocumentItems.class)
                    .optional(GeneralApplicationSuportingDocumentItems::getSupportDocument).done()
                    .optional(GeneralApplicationItems::getGeneralApplicationCreatedDate)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationStatus)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationOutcomeOther)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"")
                    .optional(GeneralApplicationItems::getGeneralApplicationDirectionsDocument)
                    .fieldShowCondition("generalApplicationCreatedBy=\"IMPOSSIBLE\"").done().done();
    }
}
