package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.EnvironmentFlags;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code CUI_invalidateApplicantAccessCode} for case type {@code FinancialRemedyContested}.
 */
@Component
public class CUIInvalidateApplicantAccessCodeNonprod implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CUI_INVALIDATE_APPLICANT_ACCESS_CODE = "CUI_invalidateApplicantAccessCode";

    /**
     * Registers overlay event {@code CUI_invalidateApplicantAccessCode} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        builder.event(CUI_INVALIDATE_APPLICANT_ACCESS_CODE)
            .forAllStates()
            .name("Invalidate Applicant Code")
            .description("Invalidate Applicant Access Code")
            .displayOrder(160)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_SYSTEMUPDATE);
    }
}
