package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage10;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage11;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage12;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage13;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage14;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage15;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage16;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage17;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage18;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage19;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage2;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage20;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage21;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage22;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage23;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage24;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage25;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage26;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage3;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage4;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage5;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage6;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage7;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage8;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendPaperApplicationPage9;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_amendPaperApplication} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRAmendPaperApplication implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_AMEND_PAPER_APPLICATION = "FR_amendPaperApplication";

    /**
     * Registers event {@code FR_amendPaperApplication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_AMEND_PAPER_APPLICATION)
            .forState(CcdState.paperCaseAdded)
            .name("Amend Application Details")
            .displayOrder(16)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY)
            .fields();
        FRAmendPaperApplicationPage1.apply(fields);
        FRAmendPaperApplicationPage2.apply(fields);
        FRAmendPaperApplicationPage3.apply(fields);
        FRAmendPaperApplicationPage4.apply(fields);
        FRAmendPaperApplicationPage5.apply(fields);
        FRAmendPaperApplicationPage6.apply(fields);
        FRAmendPaperApplicationPage7.apply(fields);
        FRAmendPaperApplicationPage8.apply(fields);
        FRAmendPaperApplicationPage9.apply(fields);
        FRAmendPaperApplicationPage10.apply(fields);
        FRAmendPaperApplicationPage11.apply(fields);
        FRAmendPaperApplicationPage12.apply(fields);
        FRAmendPaperApplicationPage13.apply(fields);
        FRAmendPaperApplicationPage14.apply(fields);
        FRAmendPaperApplicationPage15.apply(fields);
        FRAmendPaperApplicationPage16.apply(fields);
        FRAmendPaperApplicationPage17.apply(fields);
        FRAmendPaperApplicationPage18.apply(fields);
        FRAmendPaperApplicationPage19.apply(fields);
        FRAmendPaperApplicationPage20.apply(fields);
        FRAmendPaperApplicationPage21.apply(fields);
        FRAmendPaperApplicationPage22.apply(fields);
        FRAmendPaperApplicationPage23.apply(fields);
        FRAmendPaperApplicationPage24.apply(fields);
        FRAmendPaperApplicationPage25.apply(fields);
        FRAmendPaperApplicationPage26.apply(fields);
    }
}
