package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage10;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage11;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage12;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage13;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage14;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage15;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage16;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage17;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage18;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage19;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage2;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage20;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage21;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage22;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage23;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage24;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage25;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage26;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage3;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage4;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage5;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage6;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage7;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage8;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRAmendApplicationPage9;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_amendApplication} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRAmendApplication implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_AMEND_APPLICATION = "FR_amendApplication";

    /**
     * Registers event {@code FR_amendApplication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_AMEND_APPLICATION)
            .forState(CcdState.caseAdded)
            .name("Amend Application Details")
            .displayOrder(16)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY)
            .fields();
        FRAmendApplicationPage1.apply(fields);
        FRAmendApplicationPage2.apply(fields);
        FRAmendApplicationPage3.apply(fields);
        FRAmendApplicationPage4.apply(fields);
        FRAmendApplicationPage5.apply(fields);
        FRAmendApplicationPage6.apply(fields);
        FRAmendApplicationPage7.apply(fields);
        FRAmendApplicationPage8.apply(fields);
        FRAmendApplicationPage9.apply(fields);
        FRAmendApplicationPage10.apply(fields);
        FRAmendApplicationPage11.apply(fields);
        FRAmendApplicationPage12.apply(fields);
        FRAmendApplicationPage13.apply(fields);
        FRAmendApplicationPage14.apply(fields);
        FRAmendApplicationPage15.apply(fields);
        FRAmendApplicationPage16.apply(fields);
        FRAmendApplicationPage17.apply(fields);
        FRAmendApplicationPage18.apply(fields);
        FRAmendApplicationPage19.apply(fields);
        FRAmendApplicationPage20.apply(fields);
        FRAmendApplicationPage21.apply(fields);
        FRAmendApplicationPage22.apply(fields);
        FRAmendApplicationPage23.apply(fields);
        FRAmendApplicationPage24.apply(fields);
        FRAmendApplicationPage25.apply(fields);
        FRAmendApplicationPage26.apply(fields);
    }
}
