package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_approveApplication} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRApproveApplication implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_APPROVE_APPLICATION = "FR_approveApplication";

    /**
     * Registers event {@code FR_approveApplication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_APPROVE_APPLICATION)
            .forStateTransition(CcdState.awaitingJudiciaryResponse, CcdState.consentOrderApproved)
            .name("Approve Application")
            .displayOrder(21)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .fields();
        fields.page("1");
        fields.mandatory(FinremCaseData::getSubjectToDecreeAbsoluteValue);
        fields.mandatory(FinremCaseData::getServePensionProvider);
        fields.mandatory(FinremCaseData::getServePensionProviderResponsibility)
                    .fieldShowCondition("servePensionProvider=\"Yes\"");
        fields.mandatory(FinremCaseData::getServePensionProviderOther)
                    .fieldShowCondition("servePensionProvider=\"Yes\" AND servePensionProviderResponsibility=\"other\"");
        fields.mandatory(FinremCaseData::getSelectJudge);
        fields.mandatory(FinremCaseData::getDateOfOrder);
        fields.optional(FinremCaseData::getAdditionalComments);
    }
}
