package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_assignToJudge} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRAssignToJudge implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_ASSIGN_TO_JUDGE = "FR_assignToJudge";

    /**
     * Registers event {@code FR_assignToJudge}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_ASSIGN_TO_JUDGE)
            .forStateTransition(EnumSet.of(CcdState.consentProcess, CcdState.consentOrderNotApproved, CcdState.consentOrderApproved), CcdState.awaitingJudiciaryResponse)
            .name("Assign To Judge")
            .displayOrder(17)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .fields();
        fields.page("1");
        fields.mandatory(FinremCaseData::getAssignToJudgeReason);
        fields.mandatory(FinremCaseData::getAssignToJudgeText);
    }
}
