package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ConsentOrderWrapper;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ScheduleOneWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_consentOrderApproved} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRConsentOrderApproved implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_CONSENT_ORDER_APPROVED = "FR_consentOrderApproved";

    /**
     * Registers event {@code FR_consentOrderApproved}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_CONSENT_ORDER_APPROVED)
            .forStateTransition(CcdState.consentedOrderAssignJudge, CcdState.consentedOrderApproved)
            .name("Consent Application Approved")
            .displayOrder(118)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .fields();
        fields.page("1");
        fields.pageLabel("Approve Application");
        fields.complex(FinremCaseData::getScheduleOneWrapper)
                    .readonly(ScheduleOneWrapper::getTypeOfApplication)
                    .fieldShowCondition("consentServePensionProvider=\"banana\"").done();
        fields.complex(FinremCaseData::getConsentOrderWrapper)
                    .mandatory(ConsentOrderWrapper::getConsentSubjectToDecreeAbsoluteValue)
                    .fieldShowCondition("typeOfApplication=\"In connection to matrimonial and civil partnership proceedings\"")
                    .mandatory(ConsentOrderWrapper::getConsentServePensionProvider)
                    .fieldShowCondition("typeOfApplication=\"In connection to matrimonial and civil partnership proceedings\"")
                    .mandatory(ConsentOrderWrapper::getConsentServePensionProviderResponsibility)
                    .fieldShowCondition("consentServePensionProvider=\"Yes\"")
                    .mandatory(ConsentOrderWrapper::getConsentServePensionProviderOther)
                    .fieldShowCondition("consentServePensionProvider=\"Yes\" AND consentServePensionProviderResponsibility=\"other\"")
                    .mandatory(ConsentOrderWrapper::getConsentSelectJudge)
                    .mandatory(ConsentOrderWrapper::getConsentJudgeName)
                    .mandatory(ConsentOrderWrapper::getConsentDateOfOrder)
                    .optional(ConsentOrderWrapper::getConsentAdditionalComments).done();
    }
}
