package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRCreateGeneralApplicationCreateGeneralApplicationDocumentPage;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRCreateGeneralApplicationCreateGeneralApplicationOrderPage;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRCreateGeneralApplicationCreateGeneralApplicationPage;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRCreateGeneralApplicationPage1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_createGeneralApplication} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRCreateGeneralApplication implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_CREATE_GENERAL_APPLICATION = "FR_createGeneralApplication";

    /**
     * Registers event {@code FR_createGeneralApplication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_CREATE_GENERAL_APPLICATION)
            .forStateTransition(EnumSet.of(CcdState.applicationIssued, CcdState.schedulingAndHearing, CcdState.prepareForHearing, CcdState.solicitorDraftOrder, CcdState.judgeDraftOrder, CcdState.draftOrderNotApproved, CcdState.scheduleRaiseDirectionsOrder, CcdState.orderDrawn, CcdState.caseWorkerReview, CcdState.gateKeepingAndAllocation, CcdState.caseFileSubmitted, CcdState.reviewOrder, CcdState.awaitingJudiciaryResponse, CcdState.close, CcdState.orderSent), CcdState.generalApplication)
            .name("Create General Application")
            .description("Deprecated - Kept as needed this for existing cases")
            .displayOrder(124)
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .fields();
        FRCreateGeneralApplicationCreateGeneralApplicationPage.apply(fields);
        FRCreateGeneralApplicationCreateGeneralApplicationDocumentPage.apply(fields);
        FRCreateGeneralApplicationCreateGeneralApplicationOrderPage.apply(fields);
        FRCreateGeneralApplicationPage1.apply(fields);
    }
}
