package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRDraftOrdersPage1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRDraftOrdersPage2;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRDraftOrdersPage3;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.draftorders.upload.UploadDraftOrderAdditionalDocument;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.draftorders.upload.agreed.AgreedPensionSharingAnnex;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.draftorders.upload.agreed.UploadAgreedDraftOrder;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.draftorders.upload.suggested.SuggestedPensionSharingAnnex;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.draftorders.upload.suggested.UploadSuggestedDraftOrder;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.draftorders.upload.suggested.UploadedDraftOrder;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.DraftOrdersWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_draftOrders} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRDraftOrders implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_DRAFT_ORDERS = "FR_draftOrders";

    /**
     * Registers event {@code FR_draftOrders}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_DRAFT_ORDERS)
            .forStateTransition(EnumSet.of(CcdState.schedulingAndHearing, CcdState.generalApplication, CcdState.generalApplicationOutcome, CcdState.orderDrawn, CcdState.prepareForHearing, CcdState.consentProcess, CcdState.consentOrderNotApproved, CcdState.consentOrderApproved, CcdState.caseWorkerReview, CcdState.caseFileSubmitted, CcdState.judgeDraftOrder, CcdState.reviewOrder, CcdState.draftOrderNotApproved, CcdState.solicitorDraftOrder, CcdState.scheduleRaiseDirectionsOrder, CcdState.awaitingJudiciaryResponse, CcdState.awaitingJudiciaryResponseConsent, CcdState.consentOrderMade, CcdState.consentedOrderApproved, CcdState.consentedOrderAssignJudge, CcdState.consentedOrderNotApproved, CcdState.consentedOrderSubmitted, CcdState.generalApplicationAwaitingJudiciaryResponse, CcdState.orderSent, CcdState.responseReceived), CcdState.reviewOrder)
            .name("Upload draft orders")
            .displayOrder(32)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY)
            .fields();
        FRDraftOrdersPage1.apply(fields);
        FRDraftOrdersPage2.apply(fields);
        FRDraftOrdersPage3.apply(fields);
        fields.complex(FinremCaseData::getDraftOrdersWrapper)
                    .complexScope(DraftOrdersWrapper::getUploadSuggestedDraftOrder)
                    .mandatory(UploadSuggestedDraftOrder::getConfirmUploadedDocuments)
                    .mandatory(UploadSuggestedDraftOrder::getUploadParty)
                    .fieldShowCondition("showUploadPartyQuestion=\"Yes\"")
                    .mandatory(UploadSuggestedDraftOrder::getUploadOrdersOrPsas)
                    .mandatory(UploadSuggestedDraftOrder::getUploadSuggestedDraftOrderCollection)
                    .fieldShowCondition("uploadSuggestedDraftOrder.uploadOrdersOrPsas CONTAINS \"orders\"")
                    .complex(UploadSuggestedDraftOrder::getUploadSuggestedDraftOrderCollection, UploadedDraftOrder.class)
                    .mandatory(UploadedDraftOrder::getSuggestedDraftOrderDocument)
                    .noHintText().done()
                    .complex(UploadSuggestedDraftOrder::getUploadSuggestedDraftOrderCollection, UploadedDraftOrder.class)
                    .optional(UploadedDraftOrder::getAdditionalDocuments)
                    .noHintText().done()
                    .complex(UploadSuggestedDraftOrder::getUploadSuggestedDraftOrderCollection, UploadedDraftOrder.class)
                    .complex(UploadedDraftOrder::getAdditionalDocuments, UploadDraftOrderAdditionalDocument.class)
                    .optional(UploadDraftOrderAdditionalDocument::getOrderAttachment).done().done()
                    .mandatory(UploadSuggestedDraftOrder::getSuggestedPsaCollection)
                    .fieldShowCondition("uploadSuggestedDraftOrder.uploadOrdersOrPsas CONTAINS \"pensionSharingAnnexes\"")
                    .complex(UploadSuggestedDraftOrder::getSuggestedPsaCollection, SuggestedPensionSharingAnnex.class)
                    .mandatory(SuggestedPensionSharingAnnex::getSuggestedPensionSharingAnnexes)
                    .noHintText().done().done().done();
        fields.complex(FinremCaseData::getDraftOrdersWrapper)
                    .complexScope(DraftOrdersWrapper::getUploadAgreedDraftOrder)
                    .mandatory(UploadAgreedDraftOrder::getConfirmUploadedDocuments)
                    .mandatory(UploadAgreedDraftOrder::getHearingDetails)
                    .readonly(UploadAgreedDraftOrder::getJudgeNameGuidance)
                    .fieldShowCondition("typeOfDraftOrder=\"anAgreedOrderFollowingAHearing\"")
                    .mandatory(UploadAgreedDraftOrder::getJudgeKnownAtHearing)
                    .fieldShowCondition("typeOfDraftOrder=\"anAgreedOrderFollowingAHearing\"")
                    .readonly(UploadAgreedDraftOrder::getJudgeUnknownWarning)
                    .fieldShowCondition("uploadAgreedDraftOrder.judgeKnownAtHearing=\"No\"")
                    .mandatory(UploadAgreedDraftOrder::getJudge)
                    .fieldShowCondition("uploadAgreedDraftOrder.judgeKnownAtHearing=\"Yes\"")
                    .mandatory(UploadAgreedDraftOrder::getUploadParty)
                    .fieldShowCondition("showUploadPartyQuestion=\"Yes\"")
                    .mandatory(UploadAgreedDraftOrder::getUploadOrdersOrPsas)
                    .mandatory(UploadAgreedDraftOrder::getUploadAgreedDraftOrderCollection)
                    .fieldShowCondition("uploadAgreedDraftOrder.uploadOrdersOrPsas CONTAINS \"orders\"")
                    .complex(UploadAgreedDraftOrder::getUploadAgreedDraftOrderCollection, uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.draftorders.upload.agreed.UploadedDraftOrder.class)
                    .mandatory(uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.draftorders.upload.agreed.UploadedDraftOrder::getAgreedDraftOrderDocument)
                    .noHintText().done()
                    .complex(UploadAgreedDraftOrder::getUploadAgreedDraftOrderCollection, uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.draftorders.upload.agreed.UploadedDraftOrder.class)
                    .optional(uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.draftorders.upload.agreed.UploadedDraftOrder::getResubmission).done()
                    .complex(UploadAgreedDraftOrder::getUploadAgreedDraftOrderCollection, uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.draftorders.upload.agreed.UploadedDraftOrder.class)
                    .optional(uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.draftorders.upload.agreed.UploadedDraftOrder::getAdditionalDocuments)
                    .noHintText().done()
                    .complex(UploadAgreedDraftOrder::getUploadAgreedDraftOrderCollection, uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.draftorders.upload.agreed.UploadedDraftOrder.class)
                    .complex(uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.draftorders.upload.agreed.UploadedDraftOrder::getAdditionalDocuments, UploadDraftOrderAdditionalDocument.class)
                    .optional(UploadDraftOrderAdditionalDocument::getOrderAttachment).done().done()
                    .mandatory(UploadAgreedDraftOrder::getAgreedPsaCollection)
                    .fieldShowCondition("uploadAgreedDraftOrder.uploadOrdersOrPsas CONTAINS \"pensionSharingAnnexes\"")
                    .complex(UploadAgreedDraftOrder::getAgreedPsaCollection, AgreedPensionSharingAnnex.class)
                    .mandatory(AgreedPensionSharingAnnex::getAgreedPensionSharingAnnexes)
                    .noHintText().done().done().done();
    }
}
