package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.DraftDirectionDetailsHolder;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.DraftDirectionOrder;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.DraftDirectionWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_draftOrderApproved} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRDraftOrderApproved implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_DRAFT_ORDER_APPROVED = "FR_draftOrderApproved";

    /**
     * Registers event {@code FR_draftOrderApproved}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_DRAFT_ORDER_APPROVED)
            .forStateTransition(CcdState.reviewOrder, CcdState.scheduleRaiseDirectionsOrder)
            .name("Draft Order Approved")
            .displayOrder(35)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .fields();
        fields.page("1");
        fields.complex(FinremCaseData::getDraftDirectionWrapper)
                    .complexMember(DraftDirectionWrapper::getLatestDraftDirectionOrder).done();
        fields.mandatory(FinremCaseData::getOrderApprovedJudgeType);
        fields.mandatory(FinremCaseData::getOrderApprovedJudgeName);
        fields.mandatory(FinremCaseData::getOrderApprovedDate);
        fields.complex(FinremCaseData::getDraftDirectionWrapper)
                    .complexMember(DraftDirectionWrapper::getDraftDirectionDetailsCollection).done();
        fields.complex(FinremCaseData::getDraftDirectionWrapper)
                    .complex(DraftDirectionWrapper::getDraftDirectionDetailsCollection, DraftDirectionDetailsHolder.class)
                    .optional(DraftDirectionDetailsHolder::getListingInstructor)
                    .mandatory(DraftDirectionDetailsHolder::getIsThisFinalYN)
                    .mandatory(DraftDirectionDetailsHolder::getIsAnotherHearingYN)
                    .mandatory(DraftDirectionDetailsHolder::getTypeOfHearing)
                    .mandatory(DraftDirectionDetailsHolder::getTimeEstimate)
                    .mandatory(DraftDirectionDetailsHolder::getAdditionalTime)
                    .mandatory(DraftDirectionDetailsHolder::getLocalCourt)
                    .mandatory(DraftDirectionDetailsHolder::getNottinghamList)
                    .mandatory(DraftDirectionDetailsHolder::getCfcList).done().done();
        fields.complex(FinremCaseData::getDraftDirectionWrapper)
                    .complexScope(DraftDirectionWrapper::getLatestDraftDirectionOrder)
                    .mandatory(DraftDirectionOrder::getPurposeOfDocument)
                    .mandatory(DraftDirectionOrder::getUploadDraftDocument)
                    .optional(DraftDirectionOrder::getAdditionalDocuments)
                    .fieldShowCondition("uploadHearingOrder=\"DONOTSHOW\"").done().done();
    }
}
