package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.GeneralApplicationCourtListWrapper;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.GeneralApplicationRegionWrapper;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.GeneralApplicationWrapper;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.RegionWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_GeneralApplicationDirections} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRGeneralApplicationDirections implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_GENERAL_APPLICATION_DIRECTIONS = "FR_GeneralApplicationDirections";

    /**
     * Registers event {@code FR_GeneralApplicationDirections}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_GENERAL_APPLICATION_DIRECTIONS)
            .forStates(CcdState.generalApplicationOutcome, CcdState.reviewOrder, CcdState.scheduleRaiseDirectionsOrder, CcdState.draftOrderNotApproved, CcdState.orderDrawn, CcdState.orderSent, CcdState.solicitorDraftOrder, CcdState.prepareForHearing, CcdState.caseFileSubmitted, CcdState.generalApplication)
            .name("General Application Directions")
            .description("General Application Directions (Deprecated)")
            .displayOrder(126)
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .fields();
        fields.page("1");
        fields.complex(FinremCaseData::getGeneralApplicationWrapper)
                    .mandatory(GeneralApplicationWrapper::getGeneralApplicationDirectionsList)
                    .mandatory(GeneralApplicationWrapper::getGeneralApplicationDirectionsHearingRequired).done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getHearingDateLabel)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\"").done();
        fields.complex(FinremCaseData::getGeneralApplicationWrapper)
                    .mandatory(GeneralApplicationWrapper::getGeneralApplicationDirectionsHearingDate)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\"").done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getFastTrackWranMsg)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\"")
                    .readonly(CaseDataExtra::getStandardTrackWranMsg)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\"")
                    .readonly(CaseDataExtra::getHearingTimeLabel)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\"").done();
        fields.complex(FinremCaseData::getGeneralApplicationWrapper)
                    .mandatory(GeneralApplicationWrapper::getGeneralApplicationDirectionsHearingTime)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\"").done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getTimeEstimateLabel)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\"").done();
        fields.complex(FinremCaseData::getGeneralApplicationWrapper)
                    .mandatory(GeneralApplicationWrapper::getGeneralApplicationDirectionsHearingTimeEstimate)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\"").done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getChooseCourtLabelSL)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\"").done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .mandatory(GeneralApplicationRegionWrapper::getGeneralApplicationDirectionsRegionList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .mandatory(GeneralApplicationRegionWrapper::getGeneralApplicationDirectionsLondonFrcList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"london\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .mandatory(GeneralApplicationRegionWrapper::getGeneralApplicationDirectionsNorthWestFrcList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"northwest\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .mandatory(GeneralApplicationRegionWrapper::getGeneralApplicationDirectionsNorthEastFrcList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"northeast\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .mandatory(GeneralApplicationRegionWrapper::getGeneralApplicationDirectionsSouthEastFrcList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"southeast\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .mandatory(GeneralApplicationRegionWrapper::getGeneralApplicationDirectionsSouthWestFrcList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"southwest\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .mandatory(GeneralApplicationRegionWrapper::getGeneralApplicationDirectionsWalesFrcList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"wales\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .mandatory(GeneralApplicationRegionWrapper::getGeneralApplicationDirectionsHighCourtFrcList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"highcourt\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .mandatory(GeneralApplicationRegionWrapper::getGeneralApplicationDirectionsMidlandsFrcList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"midlands\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsNottinghamCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"midlands\" AND generalApplicationDirections_midlandsFRCList=\"nottingham\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsCfcCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"london\" AND generalApplicationDirections_londonFRCList=\"cfc\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsBirminghamCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"midlands\" AND generalApplicationDirections_midlandsFRCList=\"birmingham\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsLiverpoolCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"northwest\" AND generalApplicationDirections_northWestFRCList=\"liverpool\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsManchesterCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"northwest\" AND generalApplicationDirections_northWestFRCList=\"manchester\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsLancashireCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"northwest\" AND generalApplicationDirections_northWestFRCList=\"lancashire\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsClevelandCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"northeast\" AND generalApplicationDirections_northEastFRCList=\"cleaveland\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsNwYorkshireCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"northeast\" AND generalApplicationDirections_northEastFRCList=\"nwyorkshire\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsHumberCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"northeast\" AND generalApplicationDirections_northEastFRCList=\"hsyorkshire\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsKentSurreyCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"southeast\" AND generalApplicationDirections_southEastFRCList=\"kentfrc\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsBedfordshireCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"southeast\" AND generalApplicationDirections_southEastFRCList=\"bedfordshire\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsThamesValleyCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"southeast\" AND generalApplicationDirections_southEastFRCList=\"thamesvalley\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsDevonCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"southwest\" AND generalApplicationDirections_southWestFRCList=\"devon\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsDorsetCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"southwest\" AND generalApplicationDirections_southWestFRCList=\"dorset\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsBristolCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"southwest\" AND generalApplicationDirections_southWestFRCList=\"bristol\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsNewportCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"wales\" AND generalApplicationDirections_walesFRCList=\"newport\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsSwanseaCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"wales\" AND generalApplicationDirections_walesFRCList=\"swansea\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsNorthWalesCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"wales\" AND generalApplicationDirections_walesFRCList=\"northwales\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getGeneralApplicationRegionWrapper)
                    .complex(GeneralApplicationRegionWrapper::getCourtListWrapper)
                    .mandatory(GeneralApplicationCourtListWrapper::getGeneralApplicationDirectionsHighCourtList)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\" AND generalApplicationDirections_regionList=\"highcourt\" AND generalApplicationDirections_highCourtFRCList=\"highcourt\"").done().done().done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getAdditionalInformationAboutHearingLabel)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\"").done();
        fields.complex(FinremCaseData::getGeneralApplicationWrapper)
                    .optional(GeneralApplicationWrapper::getGeneralApplicationDirectionsAdditionalInformation)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"Yes\"")
                    .optional(GeneralApplicationWrapper::getGeneralApplicationDirectionsRecitals)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"No\"")
                    .mandatory(GeneralApplicationWrapper::getGeneralApplicationDirectionsJudgeType)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"No\"")
                    .mandatory(GeneralApplicationWrapper::getGeneralApplicationDirectionsJudgeName)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"No\"")
                    .mandatory(GeneralApplicationWrapper::getGeneralApplicationDirectionsCourtOrderDate)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"No\"")
                    .mandatory(GeneralApplicationWrapper::getGeneralApplicationDirectionsTextFromJudge)
                    .fieldShowCondition("generalApplicationDirectionsHearingRequired=\"No\"").done();
    }
}
