package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.GeneralApplicationWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_GeneralApplicationOutcome} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRGeneralApplicationOutcome implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_GENERAL_APPLICATION_OUTCOME = "FR_GeneralApplicationOutcome";

    /**
     * Registers event {@code FR_GeneralApplicationOutcome}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_GENERAL_APPLICATION_OUTCOME)
            .forStateTransition(EnumSet.of(CcdState.generalApplicationAwaitingJudiciaryResponse, CcdState.generalApplicationOutcome, CcdState.prepareForHearing), CcdState.generalApplicationOutcome)
            .name("General Application Outcome")
            .displayOrder(125)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .fields();
        fields.page("1");
        fields.complex(FinremCaseData::getGeneralApplicationWrapper)
                    .mandatory(GeneralApplicationWrapper::getGeneralApplicationOutcomeList)
                    .mandatory(GeneralApplicationWrapper::getGeneralApplicationOutcome)
                    .mandatory(GeneralApplicationWrapper::getGeneralApplicationOutcomeOther)
                    .fieldShowCondition("generalApplicationOutcome=\"Other\"").done();
    }
}
