package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.GeneralApplicationWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_generalApplicationReferToJudge} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRGeneralApplicationReferToJudge implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_GENERAL_APPLICATION_REFER_TO_JUDGE = "FR_generalApplicationReferToJudge";

    /**
     * Registers event {@code FR_generalApplicationReferToJudge}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_GENERAL_APPLICATION_REFER_TO_JUDGE)
            .forStateTransition(EnumSet.of(CcdState.generalApplication, CcdState.generalApplicationAwaitingJudiciaryResponse, CcdState.reviewOrder, CcdState.scheduleRaiseDirectionsOrder, CcdState.draftOrderNotApproved, CcdState.orderDrawn, CcdState.orderSent, CcdState.solicitorDraftOrder, CcdState.prepareForHearing, CcdState.caseFileSubmitted, CcdState.generalApplicationOutcome), CcdState.generalApplicationAwaitingJudiciaryResponse)
            .name("Refer to Judge (Application)")
            .displayOrder(125)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .fields();
        fields.page("generalApplicationReferToJudge");
        fields.pageLabel("Refer to Judge (Application)");
        fields.complex(FinremCaseData::getGeneralApplicationWrapper)
                    .mandatory(GeneralApplicationWrapper::getGeneralApplicationReferList)
                    .optional(GeneralApplicationWrapper::getGeneralApplicationReferToJudgeEmail)
                    .mandatory(GeneralApplicationWrapper::getGeneralApplicationReferDetail)
                    .fieldShowCondition("generalApplicationReferToJudgeEmail=\"IMPOSSIBLE\"").done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getGeneralApplicationReferToJudgeEmailWarning)
                    .fieldShowCondition("generalApplicationReferToJudgeEmail=\"\"").done();
    }
}
