package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRGeneralOrderConsentPage1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRGeneralOrderConsentPage2;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_generalOrderConsent} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRGeneralOrderConsent implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_GENERAL_ORDER_CONSENT = "FR_generalOrderConsent";

    /**
     * Registers event {@code FR_generalOrderConsent}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_GENERAL_ORDER_CONSENT)
            .forStateTransition(EnumSet.of(CcdState.consentedOrderSubmitted, CcdState.awaitingJudiciaryResponseConsent, CcdState.consentedOrderAssignJudge, CcdState.consentedOrderApproved, CcdState.consentOrderNotApproved, CcdState.responseReceived), CcdState.consentedOrderNotApproved)
            .name("Create General Order (consent)")
            .displayOrder(120)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .fields();
        FRGeneralOrderConsentPage1.apply(fields);
        FRGeneralOrderConsentPage2.apply(fields);
    }
}
