package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRGeneralOrderPage1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRGeneralOrderPage2;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_generalOrder} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRGeneralOrder implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_GENERAL_ORDER = "FR_generalOrder";

    /**
     * Registers event {@code FR_generalOrder}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_GENERAL_ORDER)
            .forStateTransition(EnumSet.of(CcdState.caseWorkerReview, CcdState.gateKeepingAndAllocation, CcdState.schedulingAndHearing, CcdState.prepareForHearing, CcdState.caseFileSubmitted, CcdState.judgeDraftOrder, CcdState.reviewOrder, CcdState.draftOrderNotApproved, CcdState.solicitorDraftOrder, CcdState.orderDrawn, CcdState.scheduleRaiseDirectionsOrder, CcdState.awaitingJudiciaryResponse, CcdState.generalApplicationOutcome), CcdState.orderDrawn)
            .name("Create General Order")
            .displayOrder(18)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY)
            .fields();
        FRGeneralOrderPage1.apply(fields);
        FRGeneralOrderPage2.apply(fields);
    }
}
