package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRGiveAllocationDirectionsV2Page1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRGiveAllocationDirectionsV2Page2;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_giveAllocationDirectionsV2} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRGiveAllocationDirectionsV2 implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_GIVE_ALLOCATION_DIRECTIONS_V2 = "FR_giveAllocationDirectionsV2";

    /**
     * Registers event {@code FR_giveAllocationDirectionsV2}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_GIVE_ALLOCATION_DIRECTIONS_V2)
            .forStateTransition(CcdState.gateKeepingAndAllocation, CcdState.schedulingAndHearing)
            .name("Give Allocation Directions")
            .displayOrder(12)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY)
            .fields();
        FRGiveAllocationDirectionsV2Page1.apply(fields);
        FRGiveAllocationDirectionsV2Page2.apply(fields);
    }
}
