package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_judgeToDraftOrder} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRJudgeToDraftOrder implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_JUDGE_TO_DRAFT_ORDER = "FR_judgeToDraftOrder";

    /**
     * Registers event {@code FR_judgeToDraftOrder}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_JUDGE_TO_DRAFT_ORDER)
            .forStateTransition(CcdState.caseFileSubmitted, CcdState.judgeDraftOrder)
            .name("Judge To Draft Order")
            .displayOrder(30)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .fields();
        fields.page("1");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getAttendingCourtWithAssistanceLabel).done();
        fields.mandatory(FinremCaseData::getAttendingCourtWithAssistance);
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getAttendingCourtWithArrangementLabel).done();
        fields.mandatory(FinremCaseData::getAttendingCourtWithArrangement);
    }
}
