package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_listForInterimHearing} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRListForInterimHearing implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_LIST_FOR_INTERIM_HEARING = "FR_listForInterimHearing";

    /**
     * Registers event {@code FR_listForInterimHearing}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        builder.event(FR_LIST_FOR_INTERIM_HEARING)
            .forAllStates()
            .name("List for Interim Hearing")
            .description("List for Interim Hearing (Deprecated)")
            .displayOrder(142)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR);
    }
}
