package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.EnvironmentFlags;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_manageExpressCase} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRManageExpressCaseProd implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_MANAGE_EXPRESS_CASE = "FR_manageExpressCase";

    /**
     * Registers overlay event {@code FR_manageExpressCase} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        if (!EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        builder.event(FR_MANAGE_EXPRESS_CASE)
            .forAllStates()
            .name("Manage Express Case")
            .description("Remove a case from the Express Pilot")
            .displayOrder(157)
            .showSummary(false)
            .explicitGrants();
    }
}
