package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRManageScannedDocsPage1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRManageScannedDocsPage2;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_manageScannedDocs} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRManageScannedDocs implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_MANAGE_SCANNED_DOCS = "FR_manageScannedDocs";

    /**
     * Registers event {@code FR_manageScannedDocs}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_MANAGE_SCANNED_DOCS)
            .forAllStates()
            .name("Manage scanned documents")
            .displayOrder(105)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN)
            .fields();
        FRManageScannedDocsPage1.apply(fields);
        FRManageScannedDocsPage2.apply(fields);
    }
}
