package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.HearingBundleDocument;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.HearingUploadBundleHolder;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_manageHearingBundles} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRManageHearingBundles implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_MANAGE_HEARING_BUNDLES = "FR_manageHearingBundles";

    /**
     * Registers event {@code FR_manageHearingBundles}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_MANAGE_HEARING_BUNDLES)
            .forAllStates()
            .name("Manage Hearing Bundles")
            .displayOrder(134)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APPBARRISTER, UserRole.APPSOLICITOR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.RESPBARRISTER, UserRole.RESPSOLICITOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY)
            .fields();
        fields.page("1");
        fields.complex(FinremCaseData::getHearingUploadBundle).done();
        fields.complex(FinremCaseData::getHearingUploadBundle, HearingUploadBundleHolder.class)
                    .mandatory(HearingUploadBundleHolder::getHearingBundleDate)
                    .mandatory(HearingUploadBundleHolder::getHearingBundleFdr)
                    .complex(HearingUploadBundleHolder::getHearingBundleDocuments, HearingBundleDocument.class)
                    .mandatory(HearingBundleDocument::getBundleDocuments).done()
                    .complex(HearingUploadBundleHolder::getHearingBundleDocuments, HearingBundleDocument.class)
                    .optional(HearingBundleDocument::getBundleUploadDate)
                    .fieldShowCondition("hearingUploadBundle.hearingBundleDocuments.bundleDocuments=\"IMPOSSIBLE\"").done()
                    .optional(HearingUploadBundleHolder::getHearingBundleDescription).done();
    }
}
