package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_manualPayment} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRManualPayment implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_MANUAL_PAYMENT = "FR_manualPayment";

    /**
     * Registers event {@code FR_manualPayment}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_MANUAL_PAYMENT)
            .forStateTransition(EnumSet.of(CcdState.caseAdded, CcdState.paperCaseAdded), CcdState.applicationSubmitted)
            .name("Manual Payment")
            .displayOrder(8)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN)
            .fields();
        fields.page("1");
        fields.mandatoryNoSummary(FinremCaseData::getCopyOfPaperFormA);
    }
}
