package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRManageHearingsPage1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRManageHearingsPage2;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRManageHearingsPage3;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRManageHearingsPage4;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.Court;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.managehearings.WorkingHearing;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.managehearings.WorkingVacatedHearing;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ManageHearingsWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_manageHearings} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRManageHearings implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_MANAGE_HEARINGS = "FR_manageHearings";

    /**
     * Registers event {@code FR_manageHearings}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_MANAGE_HEARINGS)
            .forAllStates()
            .name("Manage Hearings")
            .description("Manage case hearings")
            .displayOrder(158)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR, UserRole.CASEWORKER_DIVORCE_SYSTEMUPDATE)
            .fields();
        FRManageHearingsPage1.apply(fields);
        FRManageHearingsPage2.apply(fields);
        FRManageHearingsPage3.apply(fields);
        FRManageHearingsPage4.apply(fields);
        fields.complex(FinremCaseData::getManageHearingsWrapper)
                    .complexScope(ManageHearingsWrapper::getWorkingHearing)
                    .mandatory(WorkingHearing::getHearingTypeDynamicList)
                    .mandatory(WorkingHearing::getHearingTimeEstimate)
                    .mandatory(WorkingHearing::getHearingDate)
                    .noHintText()
                    .mandatory(WorkingHearing::getHearingTime)
                    .complexMember(WorkingHearing::getHearingCourtSelection)
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .readonly(Court::getLocalCourtLbl).done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getRegion).done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getMidlandsList)
                    .fieldShowCondition("workingHearing.hearingCourtSelection.region=\"midlands\"").done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getLondonList)
                    .fieldShowCondition("workingHearing.hearingCourtSelection.region=\"london\"").done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getNorthWestList)
                    .fieldShowCondition("workingHearing.hearingCourtSelection.region=\"northwest\"").done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getNorthEastList)
                    .fieldShowCondition("workingHearing.hearingCourtSelection.region=\"northeast\"").done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getSouthEastList)
                    .fieldShowCondition("workingHearing.hearingCourtSelection.region=\"southeast\"").done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getSouthWestList)
                    .fieldShowCondition("workingHearing.hearingCourtSelection.region=\"southwest\"").done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getWalesList)
                    .fieldShowCondition("workingHearing.hearingCourtSelection.region=\"wales\"").done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getHcCourtList)
                    .fieldShowCondition("workingHearing.hearingCourtSelection.region=\"highcourt\"").done()
                    .mandatory(WorkingHearing::getHearingMode)
                    .optional(WorkingHearing::getAdditionalHearingInformation)
                    .mandatory(WorkingHearing::getAdditionalHearingDocPrompt)
                    .mandatory(WorkingHearing::getAdditionalHearingDocs)
                    .mandatory(WorkingHearing::getHearingNoticePrompt)
                    .noHintText()
                    .mandatory(WorkingHearing::getPartiesOnCaseMultiSelectList).done().done();
        fields.complex(FinremCaseData::getManageHearingsWrapper)
                    .complexScope(ManageHearingsWrapper::getWorkingVacatedHearing)
                    .mandatory(WorkingVacatedHearing::getVacateOrAdjournAction)
                    .mandatory(WorkingVacatedHearing::getChooseHearings)
                    .mandatory(WorkingVacatedHearing::getVacateHearingDate)
                    .noHintText()
                    .mandatory(WorkingVacatedHearing::getVacateReason)
                    .mandatory(WorkingVacatedHearing::getSpecifyOtherReason).done().done();
    }
}
