package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_migrateCase} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRMigrateCase implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_MIGRATE_CASE = "FR_migrateCase";

    /**
     * Registers event {@code FR_migrateCase}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        builder.event(FR_MIGRATE_CASE)
            .forAllStates()
            .name("Case Data Migration")
            .displayOrder(106)
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
    }
}
