package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewManageCaseDocumentsPage1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewManageCaseDocumentsPage2;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UploadCaseDocument;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ManageCaseDocumentsWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_newManageCaseDocuments} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRNewManageCaseDocuments implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_NEW_MANAGE_CASE_DOCUMENTS = "FR_newManageCaseDocuments";

    /**
     * Registers event {@code FR_newManageCaseDocuments}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_NEW_MANAGE_CASE_DOCUMENTS)
            .forAllStates()
            .name("Manage case documents")
            .displayOrder(105)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .fields();
        FRNewManageCaseDocumentsPage1.apply(fields);
        FRNewManageCaseDocumentsPage2.apply(fields);
        fields.complex(FinremCaseData::getManageCaseDocumentsWrapper)
                    .complex(ManageCaseDocumentsWrapper::getInputManageCaseDocumentCollection, UploadCaseDocument.class)
                    .mandatory(UploadCaseDocument::getCaseDocuments)
                    .mandatory(UploadCaseDocument::getCaseDocumentType)
                    .mandatory(UploadCaseDocument::getCaseDocumentOther)
                    .optional(UploadCaseDocument::getHearingDetails)
                    .mandatory(UploadCaseDocument::getCaseDocumentConfidentiality)
                    .mandatory(UploadCaseDocument::getCaseDocumentFdr)
                    .mandatory(UploadCaseDocument::getCaseDocumentParty)
                    .optional(UploadCaseDocument::getCaseDocumentUploadDateTime)
                    .fieldShowCondition("inputManageCaseDocumentCollection=\"IMPOSSIBLAW\"").done().done();
    }
}
