package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage10;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage11;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage12;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage13;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage14;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage15;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage16;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage17;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage18;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage19;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage2;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage20;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage21;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage22;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage23;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage3;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage4;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage5;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage6;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage7;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage8;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRNewPaperCasePage9;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_newPaperCase} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRNewPaperCase implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_NEW_PAPER_CASE = "FR_newPaperCase";

    /**
     * Registers event {@code FR_newPaperCase}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_NEW_PAPER_CASE)
            .initialState(CcdState.paperCaseAdded)
            .name("New Paper Case")
            .displayOrder(122)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .fields();
        FRNewPaperCasePage1.apply(fields);
        FRNewPaperCasePage2.apply(fields);
        FRNewPaperCasePage3.apply(fields);
        FRNewPaperCasePage4.apply(fields);
        FRNewPaperCasePage5.apply(fields);
        FRNewPaperCasePage6.apply(fields);
        FRNewPaperCasePage7.apply(fields);
        FRNewPaperCasePage8.apply(fields);
        FRNewPaperCasePage9.apply(fields);
        FRNewPaperCasePage10.apply(fields);
        FRNewPaperCasePage11.apply(fields);
        FRNewPaperCasePage12.apply(fields);
        FRNewPaperCasePage13.apply(fields);
        FRNewPaperCasePage14.apply(fields);
        FRNewPaperCasePage15.apply(fields);
        FRNewPaperCasePage16.apply(fields);
        FRNewPaperCasePage17.apply(fields);
        FRNewPaperCasePage18.apply(fields);
        FRNewPaperCasePage19.apply(fields);
        FRNewPaperCasePage20.apply(fields);
        FRNewPaperCasePage21.apply(fields);
        FRNewPaperCasePage22.apply(fields);
        FRNewPaperCasePage23.apply(fields);
    }
}
