package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRProcessOrderPage1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRProcessOrderPage2;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.Court;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.DirectionOrder;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.managehearings.WorkingHearing;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.DraftOrdersWrapper;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ManageHearingsWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_processOrder} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRProcessOrder implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_PROCESS_ORDER = "FR_processOrder";

    /**
     * Registers event {@code FR_processOrder}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_PROCESS_ORDER)
            .forStateTransition(EnumSet.of(CcdState.orderDrawn, CcdState.generalApplication, CcdState.scheduleRaiseDirectionsOrder), CcdState.orderDrawn)
            .name("Process Order")
            .displayOrder(36)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR, UserRole.CASEWORKER_DIVORCE_SYSTEMUPDATE)
            .fields();
        FRProcessOrderPage1.apply(fields);
        FRProcessOrderPage2.apply(fields);
        fields.complex(FinremCaseData::getDraftOrdersWrapper)
                    .complex(DraftOrdersWrapper::getUnprocessedApprovedDocuments, DirectionOrder.class)
                    .mandatory(DirectionOrder::getUploadDraftDocument)
                    .eventHint("PLEASE NOTE: You must upload a Word document or PDF version of document.").done().done();
        fields.complex(FinremCaseData::getManageHearingsWrapper)
                    .complexScope(ManageHearingsWrapper::getWorkingHearing)
                    .mandatory(WorkingHearing::getHearingTypeDynamicList)
                    .mandatory(WorkingHearing::getHearingTimeEstimate)
                    .mandatory(WorkingHearing::getHearingDate)
                    .noHintText()
                    .mandatory(WorkingHearing::getHearingTime)
                    .complexMember(WorkingHearing::getHearingCourtSelection)
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .readonly(Court::getLocalCourtLbl).done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getRegion).done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getMidlandsList)
                    .fieldShowCondition("workingHearing.hearingCourtSelection.region=\"midlands\"").done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getLondonList)
                    .fieldShowCondition("workingHearing.hearingCourtSelection.region=\"london\"").done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getNorthWestList)
                    .fieldShowCondition("workingHearing.hearingCourtSelection.region=\"northwest\"").done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getNorthEastList)
                    .fieldShowCondition("workingHearing.hearingCourtSelection.region=\"northeast\"").done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getSouthEastList)
                    .fieldShowCondition("workingHearing.hearingCourtSelection.region=\"southeast\"").done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getSouthWestList)
                    .fieldShowCondition("workingHearing.hearingCourtSelection.region=\"southwest\"").done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getWalesList)
                    .fieldShowCondition("workingHearing.hearingCourtSelection.region=\"wales\"").done()
                    .complex(WorkingHearing::getHearingCourtSelection)
                    .mandatory(Court::getHcCourtList)
                    .fieldShowCondition("workingHearing.hearingCourtSelection.region=\"highcourt\"").done()
                    .mandatory(WorkingHearing::getHearingMode)
                    .optional(WorkingHearing::getAdditionalHearingInformation)
                    .mandatory(WorkingHearing::getAdditionalHearingDocPrompt)
                    .mandatory(WorkingHearing::getAdditionalHearingDocs)
                    .mandatory(WorkingHearing::getHearingNoticePrompt)
                    .noHintText()
                    .mandatory(WorkingHearing::getPartiesOnCaseMultiSelectList).done().done();
    }
}
