package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_removeUserCaseAccess} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRRemoveUserCaseAccess implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_REMOVE_USER_CASE_ACCESS = "FR_removeUserCaseAccess";

    /**
     * Registers event {@code FR_removeUserCaseAccess}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_REMOVE_USER_CASE_ACCESS)
            .forAllStates()
            .name("Remove user case access")
            .displayOrder(156)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SUPERUSER)
            .fields();
        fields.page("1");
        fields.mandatory(FinremCaseData::getUserCaseAccessList);
    }
}
