package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_revertFromSchedulingToSubmitted} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRRevertFromSchedulingToSubmitted implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_REVERT_FROM_SCHEDULING_TO_SUBMITTED = "FR_revertFromSchedulingToSubmitted";

    /**
     * Registers event {@code FR_revertFromSchedulingToSubmitted}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        builder.event(FR_REVERT_FROM_SCHEDULING_TO_SUBMITTED)
            .forStateTransition(CcdState.schedulingAndHearing, CcdState.applicationSubmitted)
            .name("Revert Scheduling to Submitted")
            .description("Revert from Scheduling to Submitted")
            .displayOrder(131)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
    }
}
