package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_returnTogateKeepingAndAllocation} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRReturnTogateKeepingAndAllocation implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_RETURN_TOGATE_KEEPING_AND_ALLOCATION = "FR_returnTogateKeepingAndAllocation";

    /**
     * Registers event {@code FR_returnTogateKeepingAndAllocation}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        builder.event(FR_RETURN_TOGATE_KEEPING_AND_ALLOCATION)
            .forStateTransition(CcdState.caseWorkerReview, CcdState.gateKeepingAndAllocation)
            .name("Return to G&A")
            .displayOrder(26)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR);
    }
}
