package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage10;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage11;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage12;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage13;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage14;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage15;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage16;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage17;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage18;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage19;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage2;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage20;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage21;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage22;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage23;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage24;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage25;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage3;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage4;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage5;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage6;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage7;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage8;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.FRSolicitorCreatePage9;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_solicitorCreate} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRSolicitorCreate implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_SOLICITOR_CREATE = "FR_solicitorCreate";

    /**
     * Registers event {@code FR_solicitorCreate}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_SOLICITOR_CREATE)
            .initialState(CcdState.caseAdded)
            .name("Form A Application")
            .description("Create an application for financial remedy by contested")
            .displayOrder(1)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY)
            .fields();
        FRSolicitorCreatePage1.apply(fields);
        FRSolicitorCreatePage2.apply(fields);
        FRSolicitorCreatePage3.apply(fields);
        FRSolicitorCreatePage4.apply(fields);
        FRSolicitorCreatePage5.apply(fields);
        FRSolicitorCreatePage6.apply(fields);
        FRSolicitorCreatePage7.apply(fields);
        FRSolicitorCreatePage8.apply(fields);
        FRSolicitorCreatePage9.apply(fields);
        FRSolicitorCreatePage10.apply(fields);
        FRSolicitorCreatePage11.apply(fields);
        FRSolicitorCreatePage12.apply(fields);
        FRSolicitorCreatePage13.apply(fields);
        FRSolicitorCreatePage14.apply(fields);
        FRSolicitorCreatePage15.apply(fields);
        FRSolicitorCreatePage16.apply(fields);
        FRSolicitorCreatePage17.apply(fields);
        FRSolicitorCreatePage18.apply(fields);
        FRSolicitorCreatePage19.apply(fields);
        FRSolicitorCreatePage20.apply(fields);
        FRSolicitorCreatePage21.apply(fields);
        FRSolicitorCreatePage22.apply(fields);
        FRSolicitorCreatePage23.apply(fields);
        FRSolicitorCreatePage24.apply(fields);
        FRSolicitorCreatePage25.apply(fields);
    }
}
