package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.StopRepresentationWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_stopRepresentingClient} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRStopRepresentingClient implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_STOP_REPRESENTING_CLIENT = "FR_stopRepresentingClient";

    /**
     * Registers event {@code FR_stopRepresentingClient}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_STOP_REPRESENTING_CLIENT)
            .forStates(CcdState.applicationIssued, CcdState.gateKeepingAndAllocation, CcdState.schedulingAndHearing, CcdState.prepareForHearing, CcdState.caseFileSubmitted, CcdState.close, CcdState.caseWorkerReview, CcdState.judgeDraftOrder, CcdState.solicitorDraftOrder, CcdState.reviewOrder, CcdState.draftOrderNotApproved, CcdState.scheduleRaiseDirectionsOrder, CcdState.orderDrawn, CcdState.orderSent, CcdState.consentedOrderSubmitted, CcdState.awaitingJudiciaryResponseConsent, CcdState.consentedOrderAssignJudge, CcdState.consentedOrderApproved, CcdState.responseReceived, CcdState.consentedOrderNotApproved, CcdState.generalApplication, CcdState.generalApplicationAwaitingJudiciaryResponse, CcdState.generalApplicationOutcome, CcdState.paperCaseAdded, CcdState.caseHidden, CcdState.consentProcess, CcdState.awaitingJudiciaryResponse, CcdState.consentOrderApproved, CcdState.consentOrderNotApproved, CcdState.consentOrderMade)
            .name("Stop representing a client")
            .displayOrder(159)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY)
            .grant(Permission.CRUD, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .fields();
        fields.page("1");
        fields.complex(FinremCaseData::getStopRepresentationWrapper)
                    .mandatory(StopRepresentationWrapper::getClientAddressForService)
                    .fieldShowCondition("showClientAddressForService=\"Yes\"")
                    .readonlyNoSummary(StopRepresentationWrapper::getShowClientAddressForService)
                    .fieldShowCondition("clientAddressForService=\"DO_NOT_SHOW\"")
                    .readonlyNoSummary(StopRepresentationWrapper::getClientAddressForServiceLabel)
                    .fieldShowCondition("clientAddressForService=\"DO_NOT_SHOW\"")
                    .readonly(StopRepresentationWrapper::getClientAddressForServiceConfidentialLabel)
                    .fieldShowCondition("clientAddressForService=\"IMPOSSIBLE\"")
                    .mandatory(StopRepresentationWrapper::getClientAddressForServiceConfidential)
                    .fieldShowCondition("showClientAddressForService=\"Yes\"")
                    .readonly(StopRepresentationWrapper::getExtraClientAddr1Label)
                    .fieldShowCondition("clientAddressForService=\"IMPOSSIBLE\"")
                    .readonly(StopRepresentationWrapper::getExtraClientAddr1Id)
                    .fieldShowCondition("clientAddressForService=\"IMPOSSIBLE\"")
                    .mandatory(StopRepresentationWrapper::getExtraClientAddr1)
                    .fieldShowCondition("extraClientAddr1Label!=\"\"")
                    .readonly(StopRepresentationWrapper::getExtraClientAddr1ConfidentialLabel)
                    .fieldShowCondition("clientAddressForService=\"IMPOSSIBLE\"")
                    .mandatory(StopRepresentationWrapper::getExtraClientAddr1Confidential)
                    .fieldShowCondition("extraClientAddr1ConfidentialLabel!=\"\"")
                    .readonly(StopRepresentationWrapper::getExtraClientAddr2Label)
                    .fieldShowCondition("clientAddressForService=\"IMPOSSIBLE\"")
                    .readonly(StopRepresentationWrapper::getExtraClientAddr2Id)
                    .fieldShowCondition("clientAddressForService=\"IMPOSSIBLE\"")
                    .mandatory(StopRepresentationWrapper::getExtraClientAddr2)
                    .fieldShowCondition("extraClientAddr2Label!=\"\"")
                    .readonly(StopRepresentationWrapper::getExtraClientAddr2ConfidentialLabel)
                    .fieldShowCondition("clientAddressForService=\"IMPOSSIBLE\"")
                    .mandatory(StopRepresentationWrapper::getExtraClientAddr2Confidential)
                    .fieldShowCondition("extraClientAddr2ConfidentialLabel!=\"\"")
                    .readonly(StopRepresentationWrapper::getExtraClientAddr3Label)
                    .fieldShowCondition("clientAddressForService=\"IMPOSSIBLE\"")
                    .readonly(StopRepresentationWrapper::getExtraClientAddr3Id)
                    .fieldShowCondition("clientAddressForService=\"IMPOSSIBLE\"")
                    .mandatory(StopRepresentationWrapper::getExtraClientAddr3)
                    .fieldShowCondition("extraClientAddr3Label!=\"\"")
                    .readonly(StopRepresentationWrapper::getExtraClientAddr3ConfidentialLabel)
                    .fieldShowCondition("clientAddressForService=\"IMPOSSIBLE\"")
                    .mandatory(StopRepresentationWrapper::getExtraClientAddr3Confidential)
                    .fieldShowCondition("extraClientAddr3ConfidentialLabel!=\"\"")
                    .readonly(StopRepresentationWrapper::getExtraClientAddr4Label)
                    .fieldShowCondition("clientAddressForService=\"IMPOSSIBLE\"")
                    .readonly(StopRepresentationWrapper::getExtraClientAddr4Id)
                    .fieldShowCondition("clientAddressForService=\"IMPOSSIBLE\"")
                    .mandatory(StopRepresentationWrapper::getExtraClientAddr4)
                    .fieldShowCondition("extraClientAddr4Label!=\"\"")
                    .readonly(StopRepresentationWrapper::getExtraClientAddr4ConfidentialLabel)
                    .fieldShowCondition("clientAddressForService=\"IMPOSSIBLE\"")
                    .mandatory(StopRepresentationWrapper::getExtraClientAddr4Confidential)
                    .fieldShowCondition("extraClientAddr4ConfidentialLabel!=\"\"")
                    .mandatory(StopRepresentationWrapper::getStopRepClientConsent)
                    .mandatory(StopRepresentationWrapper::getStopRepJudicialApproval)
                    .fieldShowCondition("stopRepClientConsent=\"No\"").done();
    }
}
