package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UploadGeneralDocument;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_uploadGeneralDocument} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRUploadGeneralDocument implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_UPLOAD_GENERAL_DOCUMENT = "FR_uploadGeneralDocument";

    /**
     * Registers event {@code FR_uploadGeneralDocument}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_UPLOAD_GENERAL_DOCUMENT)
            .forAllStates()
            .name("Upload email")
            .description("Upload document")
            .displayOrder(105)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN)
            .fields();
        fields.page("1");
        fields.complex(FinremCaseData::getUploadGeneralDocuments).done();
        fields.complex(FinremCaseData::getUploadGeneralDocuments, UploadGeneralDocument.class)
                    .optional(UploadGeneralDocument::getDocumentType)
                    .optional(UploadGeneralDocument::getDocumentEmailContent)
                    .optional(UploadGeneralDocument::getDocumentLink)
                    .optional(UploadGeneralDocument::getDocumentDateAdded)
                    .optional(UploadGeneralDocument::getDocumentComment)
                    .optional(UploadGeneralDocument::getDocumentFileName)
                    .optional(UploadGeneralDocument::getGeneralDocumentUploadDateTime)
                    .fieldShowCondition("uploadGeneralDocuments=\"IMPOSSIBLAW\"").done();
    }
}
