package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.AllocatedRegionWrapper;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.DefaultCourtListWrapper;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ListForHearingWrapper;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.RegionWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_updateFRCInformation} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRUpdateFRCInformation implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_UPDATE_FRCINFORMATION = "FR_updateFRCInformation";

    /**
     * Registers event {@code FR_updateFRCInformation}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_UPDATE_FRCINFORMATION)
            .forStates(CcdState.applicationIssued, CcdState.gateKeepingAndAllocation, CcdState.schedulingAndHearing, CcdState.caseFileSubmitted, CcdState.close, CcdState.consentProcess, CcdState.awaitingJudiciaryResponse, CcdState.consentOrderApproved, CcdState.consentOrderNotApproved, CcdState.consentOrderMade, CcdState.caseWorkerReview, CcdState.judgeDraftOrder, CcdState.solicitorDraftOrder, CcdState.reviewOrder, CcdState.draftOrderNotApproved, CcdState.scheduleRaiseDirectionsOrder, CcdState.orderDrawn, CcdState.orderSent, CcdState.consentedOrderSubmitted, CcdState.awaitingJudiciaryResponseConsent, CcdState.consentedOrderAssignJudge, CcdState.consentedOrderApproved, CcdState.responseReceived, CcdState.consentedOrderNotApproved, CcdState.generalApplication, CcdState.generalApplicationAwaitingJudiciaryResponse, CcdState.generalApplicationOutcome, CcdState.prepareForHearing)
            .name("Update FRC Information")
            .displayOrder(140)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR, UserRole.CASEWORKER_DIVORCE_SYSTEMUPDATE)
            .grant(Permission.CRU, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN)
            .fields();
        fields.page("1");
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getHearingCourtLabel).done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .mandatory(AllocatedRegionWrapper::getRegionList).done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .mandatory(AllocatedRegionWrapper::getLondonFrcList)
                    .fieldShowCondition("regionList=\"london\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .mandatory(AllocatedRegionWrapper::getNorthWestFrcList)
                    .fieldShowCondition("regionList=\"northwest\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .mandatory(AllocatedRegionWrapper::getNorthEastFrcList)
                    .fieldShowCondition("regionList=\"northeast\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .mandatory(AllocatedRegionWrapper::getSouthEastFrcList)
                    .fieldShowCondition("regionList=\"southeast\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .mandatory(AllocatedRegionWrapper::getSouthWestFrcList)
                    .fieldShowCondition("regionList=\"southwest\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .mandatory(AllocatedRegionWrapper::getWalesFrcList)
                    .fieldShowCondition("regionList=\"wales\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .mandatory(AllocatedRegionWrapper::getHighCourtFrcList)
                    .fieldShowCondition("regionList=\"highcourt\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .mandatory(AllocatedRegionWrapper::getMidlandsFrcList)
                    .fieldShowCondition("regionList=\"midlands\"").done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getNottinghamCourtList)
                    .fieldShowCondition("regionList=\"midlands\" AND midlandsFRCList=\"nottingham\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getCfcCourtList)
                    .fieldShowCondition("regionList=\"london\" AND londonFRCList=\"cfc\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getBirminghamCourtList)
                    .fieldShowCondition("regionList=\"midlands\" AND midlandsFRCList=\"birmingham\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getLiverpoolCourtList)
                    .fieldShowCondition("regionList=\"northwest\" AND northWestFRCList=\"liverpool\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getManchesterCourtList)
                    .fieldShowCondition("regionList=\"northwest\" AND northWestFRCList=\"manchester\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getLancashireCourtList)
                    .fieldShowCondition("regionList=\"northwest\" AND northWestFRCList=\"lancashire\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getCleavelandCourtList)
                    .fieldShowCondition("regionList=\"northeast\" AND northEastFRCList=\"cleaveland\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getNwYorkshireCourtList)
                    .fieldShowCondition("regionList=\"northeast\" AND northEastFRCList=\"nwyorkshire\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getHumberCourtList)
                    .fieldShowCondition("regionList=\"northeast\" AND northEastFRCList=\"hsyorkshire\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getKentSurreyCourtList)
                    .fieldShowCondition("regionList=\"southeast\" AND southEastFRCList=\"kentfrc\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getBedfordshireCourtList)
                    .fieldShowCondition("regionList=\"southeast\" AND southEastFRCList=\"bedfordshire\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getThamesValleyCourtList)
                    .fieldShowCondition("regionList=\"southeast\" AND southEastFRCList=\"thamesvalley\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getDevonCourtList)
                    .fieldShowCondition("regionList=\"southwest\" AND southWestFRCList=\"devon\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getDorsetCourtList)
                    .fieldShowCondition("regionList=\"southwest\" AND southWestFRCList=\"dorset\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getBristolCourtList)
                    .fieldShowCondition("regionList=\"southwest\" AND southWestFRCList=\"bristol\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getNewportCourtList)
                    .fieldShowCondition("regionList=\"wales\" AND walesFRCList=\"newport\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getSwanseaCourtList)
                    .fieldShowCondition("regionList=\"wales\" AND walesFRCList=\"swansea\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getNorthWalesCourtList)
                    .fieldShowCondition("regionList=\"wales\" AND walesFRCList=\"northwales\"").done().done().done();
        fields.complex(FinremCaseData::getRegionWrapper)
                    .complex(RegionWrapper::getAllocatedRegionWrapper)
                    .complex(AllocatedRegionWrapper::getCourtListWrapper)
                    .mandatory(DefaultCourtListWrapper::getHighCourtList)
                    .fieldShowCondition("regionList=\"highcourt\" AND highCourtFRCList=\"highcourt\"").done().done().done();
        fields.complex(FinremCaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getAdditionalInformationAboutHearingLabel).done();
        fields.complex(FinremCaseData::getListForHearingWrapper)
                    .optional(ListForHearingWrapper::getAdditionalInformationAboutHearing).done();
    }
}
