package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.ConsentOrderWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code FR_uploadConsentOrder} for case type {@code FinancialRemedyContested}.
 */
@Component
public class FRUploadConsentOrder implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FR_UPLOAD_CONSENT_ORDER = "FR_uploadConsentOrder";

    /**
     * Registers event {@code FR_uploadConsentOrder}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(FR_UPLOAD_CONSENT_ORDER)
            .forStateTransition(CcdState.consentOrderApproved, CcdState.consentOrderMade)
            .name("Upload Consent Order")
            .displayOrder(22)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .fields();
        fields.page("1");
        fields.complex(FinremCaseData::getConsentOrderWrapper)
                    .optional(ConsentOrderWrapper::getUploadConsentOrder).done();
    }
}
