package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code handleEvidence} for case type {@code FinancialRemedyContested}.
 */
@Component
public class HandleEvidence implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String HANDLE_EVIDENCE = "handleEvidence";

    /**
     * Registers event {@code handleEvidence}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(HANDLE_EVIDENCE)
            .forAllStates()
            .name("Handle supplementary evidence")
            .displayOrder(108)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_SYSTEMUPDATE)
            .fields();
        fields.page("handleEvidence");
        fields.pageLabel("BulkScanning");
        fields.mandatory(FinremCaseData::getEvidenceHandled);
    }
}
