package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code internal-change-UPDATE_CASE} for case type {@code FinancialRemedyContested}.
 */
@Component
public class InternalChangeUPDATECASE implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String INTERNAL_CHANGE_UPDATE_CASE = "internal-change-UPDATE_CASE";

    /**
     * Registers event {@code internal-change-UPDATE_CASE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        builder.event(INTERNAL_CHANGE_UPDATE_CASE)
            .forAllStates()
            .name("(internal) update case")
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_SYSTEMUPDATE);
    }
}
