package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.ManageIntervenersPage1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.ManageIntervenersPage2;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.ManageIntervenersPage3;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.ManageIntervenersPage5;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.ManageIntervenersPage7;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.ManageIntervenersPage9;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code manageInterveners} for case type {@code FinancialRemedyContested}.
 */
@Component
public class ManageInterveners implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MANAGE_INTERVENERS = "manageInterveners";

    /**
     * Registers event {@code manageInterveners}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(MANAGE_INTERVENERS)
            .forStates(CcdState.applicationIssued, CcdState.gateKeepingAndAllocation, CcdState.schedulingAndHearing, CcdState.prepareForHearing, CcdState.consentProcess, CcdState.awaitingJudiciaryResponse, CcdState.consentOrderApproved, CcdState.consentOrderNotApproved, CcdState.consentOrderMade, CcdState.caseWorkerReview, CcdState.judgeDraftOrder, CcdState.solicitorDraftOrder, CcdState.reviewOrder, CcdState.scheduleRaiseDirectionsOrder, CcdState.orderDrawn, CcdState.orderSent, CcdState.awaitingJudiciaryResponseConsent, CcdState.consentedOrderAssignJudge, CcdState.consentedOrderApproved, CcdState.consentedOrderNotApproved, CcdState.generalApplication, CcdState.generalApplicationAwaitingJudiciaryResponse, CcdState.generalApplicationOutcome, CcdState.responseReceived, CcdState.consentedOrderSubmitted, CcdState.caseFileSubmitted)
            .name("Manage Interveners")
            .description("Manage Interveners isolate events for Intervener's Solicitor's")
            .displayOrder(148)
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .grant(Permission.CRU, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN)
            .fields();
        ManageIntervenersPage1.apply(fields);
        ManageIntervenersPage2.apply(fields);
        ManageIntervenersPage3.apply(fields);
        ManageIntervenersPage5.apply(fields);
        ManageIntervenersPage7.apply(fields);
        ManageIntervenersPage9.apply(fields);
    }
}
