package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.ApplicantScanDocsCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.RespondentScanDocsCollection;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code moveScannedDocs} for case type {@code FinancialRemedyContested}.
 */
@Component
public class MoveScannedDocs implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MOVE_SCANNED_DOCS = "moveScannedDocs";

    /**
     * Registers event {@code moveScannedDocs}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(MOVE_SCANNED_DOCS)
            .forAllStates()
            .name("Move Scanned Documents")
            .displayOrder(141)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN)
            .grant(Permission.CR, UserRole.CASEWORKER_DIVORCE_SYSTEMUPDATE)
            .fields();
        fields.page("1");
        fields.pageLabel("BulkScanning");
        fields.mandatory(FinremCaseData::getScannedDocsTypeOfDocument);
        fields.complex(FinremCaseData::getApplicantScanDocuments).done()
                    .fieldShowCondition("typeOfDocument=\"applicantDoc\"");
        fields.complex(FinremCaseData::getApplicantScanDocuments, ApplicantScanDocsCollection.class)
                    .mandatory(ApplicantScanDocsCollection::getScanDocType)
                    .mandatory(ApplicantScanDocsCollection::getUrl)
                    .optional(ApplicantScanDocsCollection::getControlNumber)
                    .mandatory(ApplicantScanDocsCollection::getFileName)
                    .optional(ApplicantScanDocsCollection::getScannedDate)
                    .optional(ApplicantScanDocsCollection::getDeliveryDate)
                    .optional(ApplicantScanDocsCollection::getExceptionRecordReference).done();
        fields.complex(FinremCaseData::getRespondentScanDocuments).done()
                    .fieldShowCondition("typeOfDocument=\"respondentDoc\"");
        fields.complex(FinremCaseData::getRespondentScanDocuments, RespondentScanDocsCollection.class)
                    .mandatory(RespondentScanDocsCollection::getScanDocType)
                    .mandatory(RespondentScanDocsCollection::getUrl)
                    .optional(RespondentScanDocsCollection::getControlNumber)
                    .mandatory(RespondentScanDocsCollection::getFileName)
                    .optional(RespondentScanDocsCollection::getScannedDate)
                    .optional(RespondentScanDocsCollection::getDeliveryDate)
                    .optional(RespondentScanDocsCollection::getExceptionRecordReference).done();
    }
}
