package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.wrapper.GeneralApplicationWrapper;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code rejectGeneralApplication} for case type {@code FinancialRemedyContested}.
 */
@Component
public class RejectGeneralApplication implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REJECT_GENERAL_APPLICATION = "rejectGeneralApplication";

    /**
     * Registers event {@code rejectGeneralApplication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(REJECT_GENERAL_APPLICATION)
            .forStateTransition(EnumSet.of(CcdState.generalApplication, CcdState.reviewOrder, CcdState.scheduleRaiseDirectionsOrder, CcdState.draftOrderNotApproved, CcdState.orderDrawn, CcdState.orderSent, CcdState.solicitorDraftOrder, CcdState.prepareForHearing, CcdState.caseFileSubmitted), CcdState.generalApplication)
            .name("Reject General Application")
            .displayOrder(125)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR)
            .grant(Permission.CRU, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN)
            .fields();
        fields.page("1");
        fields.complex(FinremCaseData::getGeneralApplicationWrapper)
                    .mandatoryNoSummary(GeneralApplicationWrapper::getGeneralApplicationList)
                    .mandatoryNoSummary(GeneralApplicationWrapper::getGeneralApplicationRejectReason).done();
    }
}
