package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.ShareSelectedDocumentsPage1;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.event.page.ShareSelectedDocumentsPage2;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.CcdState;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>Event {@code shareSelectedDocuments} for case type {@code FinancialRemedyContested}.
 */
@Component
public class ShareSelectedDocuments implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SHARE_SELECTED_DOCUMENTS = "shareSelectedDocuments";

    /**
     * Registers event {@code shareSelectedDocuments}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        var fields = builder.event(SHARE_SELECTED_DOCUMENTS)
            .forStates(CcdState.applicationIssued, CcdState.gateKeepingAndAllocation, CcdState.schedulingAndHearing, CcdState.prepareForHearing, CcdState.consentProcess, CcdState.awaitingJudiciaryResponse, CcdState.consentOrderApproved, CcdState.consentOrderNotApproved, CcdState.consentOrderMade, CcdState.caseWorkerReview, CcdState.judgeDraftOrder, CcdState.solicitorDraftOrder, CcdState.reviewOrder, CcdState.scheduleRaiseDirectionsOrder, CcdState.orderDrawn, CcdState.orderSent, CcdState.awaitingJudiciaryResponseConsent, CcdState.consentedOrderAssignJudge, CcdState.consentedOrderApproved, CcdState.consentedOrderNotApproved, CcdState.generalApplication, CcdState.generalApplicationAwaitingJudiciaryResponse, CcdState.generalApplicationOutcome, CcdState.responseReceived, CcdState.consentedOrderSubmitted, CcdState.caseFileSubmitted)
            .name("Share Selected Documents")
            .description("This event should allow solicitors on a case to share selected documents with other solicitors")
            .displayOrder(149)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APPBARRISTER, UserRole.APPSOLICITOR, UserRole.INTVRBARRISTER1, UserRole.INTVRBARRISTER2, UserRole.INTVRBARRISTER3, UserRole.INTVRBARRISTER4, UserRole.INTVRSOLICITOR1, UserRole.INTVRSOLICITOR2, UserRole.INTVRSOLICITOR3, UserRole.INTVRSOLICITOR4, UserRole.RESPBARRISTER, UserRole.RESPSOLICITOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY)
            .fields();
        ShareSelectedDocumentsPage1.apply(fields);
        ShareSelectedDocumentsPage2.apply(fields);
    }
}
