package uk.gov.hmcts.reform.finrem.caseorchestration.service.bulkscan;

public class OcrFieldName {
    public static final String DIVORCE_CASE_NUMBER = "divorceCaseNumber";
    public static final String HWF_NUMBER = "HWFNumber";
    public static final String APPLICANT_FULL_NAME = "ApplicantFullName";
    public static final String RESPONDENT_FULL_NAME = "RespondentFullName";
    public static final String PROVISION_MADE_FOR = "ProvisionMadeFor";
    public static final String NATURE_OF_APPLICATION = "natureOfApplication";
    public static final String APPLICANT_INTENDS_TO = "ApplicantIntendsTo";
    public static final String DISCHARGE_PERIODICAL_PAYMENT_SUBSTITUTE = "DischargePeriodicalPaymentSubstituteFor";
    public static final String APPLYING_FOR_CONSENT_ORDER = "ApplyingForConsentOrder";
    public static final String DIVORCE_STAGE_REACHED = "divorceStageReached";
    public static final String APPLICANT_REPRESENTED = "ApplicantRepresented";
    public static final String APPLICANT_SOLICITOR_NAME = "ApplicantSolicitorName";
    public static final String APPLICANT_SOLICITOR_FIRM = "ApplicantSolicitorFirm";
    public static final String APPLICANT_SOLICITOR_ADDRESS_LINE_1 = "ApplicantSolicitorAddressLine1";
    public static final String APPLICANT_SOLICITOR_ADDRESS_TOWN = "ApplicantSolicitorAddressTown";
    public static final String APPLICANT_SOLICITOR_ADDRESS_COUNTY = "ApplicantSolicitorAddressCounty";
    public static final String APPLICANT_SOLICITOR_ADDRESS_POSTCODE = "ApplicantSolicitorAddressPostcode";
    public static final String APPLICANT_SOLICITOR_ADDRESS_COUNTRY = "ApplicantSolicitorAddressCountry";
    public static final String APPLICANT_SOLICITOR_PHONE = "ApplicantSolicitorPhone";
    public static final String APPLICANT_SOLICITOR_DX_NUMBER = "ApplicantSolicitorDXnumber";
    public static final String APPLICANT_SOLICITOR_REFERENCE = "ApplicantSolicitorReference";
    public static final String APPLICANT_PBA_NUMBER = "ApplicantPBANumber";
    public static final String APPLICANT_SOLICITOR_EMAIL = "ApplicantSolicitorEmail";
    public static final String APPLICANT_ADDRESS_LINE_1 = "ApplicantAddressLine1";
    public static final String APPLICANT_ADDRESS_TOWN = "ApplicantAddressTown";
    public static final String APPLICANT_ADDRESS_COUNTY = "ApplicantAddressCounty";
    public static final String APPLICANT_ADDRESS_POSTCODE = "ApplicantAddressPostcode";
    public static final String APPLICANT_ADDRESS_COUNTRY = "ApplicantAddressCountry";
    public static final String APPLICANT_PHONE = "ApplicantPhone";
    public static final String APPLICANT_EMAIL = "ApplicantEmail";
    public static final String RESPONDENT_ADDRESS_LINE_1 = "RespondentAddressLine1";
    public static final String RESPONDENT_ADDRESS_TOWN = "RespondentAddressTown";
    public static final String RESPONDENT_ADDRESS_COUNTY = "RespondentAddressCounty";
    public static final String RESPONDENT_ADDRESS_POSTCODE = "RespondentAddressPostcode";
    public static final String RESPONDENT_ADDRESS_COUNTRY = "RespondentAddressCountry";
    public static final String RESPONDENT_SOLICITOR_ADDRESS_LINE_1 = "RespondentSolicitorAddressLine1";
    public static final String RESPONDENT_SOLICITOR_ADDRESS_TOWN = "RespondentSolicitorAddressTown";
    public static final String RESPONDENT_SOLICITOR_ADDRESS_COUNTY = "RespondentSolicitorAddressCounty";
    public static final String RESPONDENT_SOLICITOR_ADDRESS_POSTCODE = "RespondentSolicitorAddressPostcode";
    public static final String RESPONDENT_SOLICITOR_ADDRESS_COUNTRY = "RespondentSolicitorAddressCountry";
}
