package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import lombok.Data;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import com.fasterxml.jackson.annotation.JsonProperty;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesGpeopvAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.DefaultAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerCaaCudAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.RESPSOLICITORRAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerApproverCaseworkerCaaCrudAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyCourtadminCudPlus1RolesQgxjxfAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedySolicitorCrudPlus1RolesAvwswjAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedySolicitorCrudPlus1RolesOpciwwAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesSfvgopAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesSvbfxpAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyCourtadminCrudAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyJudiciaryCrudAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesYcfimvAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CREATORRAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedySolicitorRAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesUoltzlAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyCourtadminRAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.RESPBARRISTERCrudAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.RESPSOLICITORCudAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerCaaRAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceSystemupdateCrudAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.INTVRBARRISTER1RPlus7RolesCzukhwAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerCaaCrudAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyCrudAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerApproverCrudCaseworkerCaaCudAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.INTVRSOLICITOR1RPlus4RolesIvknqaAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesEnaquoAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEunwzwAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedySuperuserRAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyCourtadminCuPlus1RolesOsjhrjAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedySuperuserCruAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedySuperuserCrudAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyCourtadminCruPlus1RolesChccdnAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyJudiciaryRuAccess;
import uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access.CaseworkerDivorceFinancialremedyJudiciaryRAccess;

/**
 * Synthesised definition-only fields for the retrofit that would otherwise push the root
 * case-data class past the JVM/Lombok all-args-constructor limit. Added to the root as a
 * prefix-less {@code @JsonUnwrapped} member, so these members flatten to the same CCD field
 * IDs. Generated by ccd-definition-converter (retrofit).
 *
 * <p>ccd-definition-converter:retrofit-overflow-companion
 */
@Data
public class CaseDataExtra {

  @CCD(
          label = "## Before You Start",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesGpeopvAccess.class}
  )
  private String beforeYouStart;
  @CCD(
          label = "Before you start completing this application you will need:\r\n\r\n*\tYour PBA number or an online help with fees reference number.\r\n*\tThe name of the Applicant’s local Court (<a href=\"https://www.find-court-tribunal.service.gov.uk/\">https://www.find-court-tribunal.service.gov.uk/</a>)\r\n*\tYou will have the opportunity to upload any other relevant documents e.g. pension forms, cover letters etc throughout the course of this application\r\n\r\nFor a refresher on how to use the financial remedy contested service you can find the quick guide here:\r\n<a href=\"https://www.gov.uk/government/publications/myhmcts-financial-remedy-services-for-legal-professionals\">https://www.gov.uk/government/publications/myhmcts-financial-remedy-services-for-legal-professionals</a>\r\n\r\nFor full guidance on using the financial remedy services you can find all guidance here:\r\n<a href=\"https://www.gov.uk/government/publications/myhmcts-how-to-use-online-financial-remedy-services\">https://www.gov.uk/government/publications/myhmcts-how-to-use-online-financial-remedy-services</a>\r\n\r\n",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesGpeopvAccess.class}
  )
  private String beforeYouStartPara1;
  @CCD(
          label = ">**Scope**\r\n\r\n>>The project team will continue to improve and add additional features based on the user feedback we receive. Please check the list below to ensure the application is within the current scope of the platform.\r\n\r\nCurrently, you can use the FR platform for any cases that fit the following criteria:\r\n\r\n*\tThe application is being made as part of a Divorce/Dissolution case, including Civil Partnership, Judicial Separation or Nullity.\r\n*\tIs a Schedule 1 application of the Children Act 1989\r\n*\tIs an application for a variation order\r\n*\tThe Divorce case, or Children’s matter may have been submitted via paper or online, however, there must be no previous financial remedy proceedings on the case unless you are applying to vary the same.\r\n*\tYou must be representing the Applicant (the applicant for FR proceedings could be either the petitioner or respondent in the divorce proceedings)\r\n\r\n>If your application does not meet these criteria, it will be returned and will have to be submitted via the normal paper process.",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesGpeopvAccess.class}
  )
  private String beforeYouStartPara2;
  @CCD(
          label = "## Is the Applicant represented ? ##",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String applicantRepresentedLabel;
  @CCD(
          label = "#### Applicant’s Contact details",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String applicantContactLabel;
  @CCD(
          label = "## Solicitor Details",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String applicantSolicitorDetailLabel;
  @CCD(
          label = "#### Solicitor’s Contact Details",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class, CaseworkerCaaCudAccess.class}
  )
  private String applicantSolicitorAddressLabel;
  @CCD(
          label = "## Divorce / Dissolution Details",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String divorceDetailsLabel;
  @CCD(
          label = "## Applicant’s Details",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String applicantDetailsLabel;
  @CCD(label = "## Urgent Case", searchable = false, typeOverride = FieldType.Label, access = {DefaultAccess.class})
  private String urgentCaseLabel;
  @CCD(
          label = "## Respondent’s Details ##",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String respondentDetailsLabel;
  @CCD(
          label = "## Is the respondent represented ? ##",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String respondentRepresentedLabel;
  @CCD(
          label = "## Respondent’s Solicitor’s Details",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class, RESPSOLICITORRAccess.class}
  )
  private String rSolicitorLabel;
  @CCD(
          label = "#### Respondent’s Solicitor’s Contact Details",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class, RESPSOLICITORRAccess.class, CaseworkerCaaCudAccess.class}
  )
  private String rSolicitorAddressLabel;
  @CCD(
          label = "#### Respondent’s Contact details",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String rRespondentLabel2;
  @CCD(
          label = "#### What is the nature of the application ?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String natureOfApplicationLabel;
  @CCD(
          label = "## Property adjustment order details",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String propertyAdjustmentOrderDetailLabel;
  @CCD(
          label = "## Do you want to add additional property ?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String additionalPropertyOrderLabel;
  @CCD(
          label = "## Does the application contain any periodical payments or secured periodical payments for children ?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String paymentForChildrenLabel;
  @CCD(
          label = "## Has a written agreement been made about maintenance for the benefit of children?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String benefitForChildrenLabel;
  @CCD(
          label = "## Has a written agreement been made about maintenance for the benefit of children?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class, CaseworkerApproverCaseworkerCaaCrudAccess.class}
  )
  private String benefitForChildrenLabelSchedule;
  @CCD(
          label = "## What payments are you applying for ?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String benefitPaymentChecklistLabel;
  @CCD(
          label = "## What payments are you applying for ?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class, CaseworkerApproverCaseworkerCaaCrudAccess.class}
  )
  private String benefitPaymentChecklistLabelSchedule;
  @CCD(
          label = "## Is the application suitable to be dealt with under the Fast Track Procedure?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String fastTrackDecisionLabel;
  @CCD(
          label = "Select all that apply",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesGpeopvAccess.class}
  )
  private String fastTrackDecisionReasonLabel;
  @CCD(
          label = "> *The types of cases to which the fast track procedure applies are set out in rule 9.9B of the Family Procedure Rules 2010. This rule came into force on 4 June 2018.*\r\n\r\n> *The main differences from the standard track procedure are:*\r\n*\t*Cases allocated to the fast track will be listed 6-10 weeks in advance (as opposed to the standard 12-16 weeks)*\r\n*\t*Financial Statements must be exchanged by no later than 21 days after the date of issue of the application (as opposed to not less than 14 days before the first appointment hearing in the standard track)*\r\n*\t*Financial statements for fast track cases should be filed on Form E1 (rather than the standard Form E)*\r\n*\t*The process at the fast track first hearing will differ from the process at a standard track first appointment hearing*",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesGpeopvAccess.class}
  )
  private String fastTrackMoreInfoContent1;
  @CCD(
          label = "## Should this application be allocated to the Complexity List of the Financial Remedies Court? ",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String addToComplexityListOfCourtsLbl;
  @CCD(
          label = "## Please state the current estimated net assets in this case:",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String estimatedAssetsLabel;
  @CCD(
          label = "## Please state the current estimated assets in this case (this should include pensions for all but the under £250,000 option).\r\n ## If the net assets, excluding pensions, are under £250,000, then the bottom option should be chosen even if the addition of pensions would otherwise take the case into a higher bracket.",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesGpeopvAccess.class}
  )
  private String estimatedAssetsLabelV3;
  @CCD(
          label = "## Of the above value, what is the net value of the family home?",
          hint = "The net value is the value after deduction of the sum owing on any mortgage",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String netValueOfHomeLabel;
  @CCD(
          label = "## Please tick any potential allegations/issues which may arise",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String potentialAllegationLabel;
  @CCD(
          label = "## Please give brief details of the potential allegation/issue:",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String detailPotentialAllegationLabel;
  @CCD(
          label = "## Is there any other reason why the case should be allocated to the Complexity List? ",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String otherReasonForComplexityLabel;
  @CCD(
          label = "## Which Financial Remedies Court are you applying to?\r\n",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesGpeopvAccess.class}
  )
  private String chooseCourtLabel;
  @CCD(
          label = "#### Does anyone in this application need assistance or special facilities when attending court?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String specialAssistanceRequiredLabel;
  @CCD(
          label = "#### Does anyone in this application need specific arrangements when attending court?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String specificArrangementsRequiredLabel;
  @CCD(
          label = "## Has the applicant attended a Mediation information & Assessment Meeting (MIAM)?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String applicantAttendedMIAMLabel;
  @CCD(label = "Yes", searchable = false, typeOverride = FieldType.Label)
  private String applicantAttendedMIAMYesLabel;
  @CCD(label = "No", searchable = false, typeOverride = FieldType.Label)
  private String applicantAttendedMIAMNoLabel;
  @CCD(
          label = "## Is the applicant claiming exemption from the requirement to attend a MIAM ?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String claimingExemptionMIAMLabel;
  @CCD(label = "Yes", searchable = false, typeOverride = FieldType.Label)
  private String claimingExemptionMIAMYesLabel;
  @CCD(label = "No", searchable = false, typeOverride = FieldType.Label)
  private String claimingExemptionMIAMNoLabel;
  @CCD(
          label = "## Reason(s) why the required evidence could not be provided:",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCudPlus1RolesQgxjxfAccess.class}
  )
  private String evidenceUnavailableMIAMTabLabel;
  @CCD(
          label = "## Additional requested information",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCudPlus1RolesQgxjxfAccess.class}
  )
  private String additionalInfoMIAMTabLabel;
  @CCD(
          label = "If you are unable to provide the required evidence with your application, please use this text box to explain the reasons(s) why",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String evidenceUnavailableDomesticAbuseMIAMLabel;
  @CCD(
          label = "If you are unable to provide the required evidence with your application, please use this text box to explain the reasons(s) why",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String evidenceUnavailableUrgencyMIAMLabel;
  @CCD(
          label = "If you are unable to provide the required evidence with your application, please use this text box to explain the reasons(s) why",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String evidenceUnavailablePreviousAttendanceMIAMLabel;
  @CCD(
          label = "If you are unable to provide the required evidence with your application, please use this text box to explain the reasons(s) why",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String evidenceUnavailableOtherGroundsMIAMLabel;
  @CCD(
          label = "Please provide any additional information requested in this text box",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String additionalInfoOtherGroundsMIAMLabel;
  @CCD(
          label = "## Has a family mediator informed the applicant that a mediator’s exemption applies, and they do not need to attend a MIAM ?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCudPlus1RolesQgxjxfAccess.class}
  )
  private String familyMediatorMIAMLabel;
  @CCD(
          label = "## MIAM Exemptions: what is the reason(s) for the applicant not attending a MIAM?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String MIAMExemptionsLabel;
  @CCD(
          label = "Select all that apply",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String MIAMExemptionsSelectAll;
  @CCD(
          label = "## MIAM Evidence : What evidence of domestic abuse does the applicant have ?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String MIAMDomesticViolenceLabel;
  @CCD(
          label = "Select all that apply",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String MIAMDomesticViolenceSelectAll;
  @CCD(
          label = "## MIAM Evidence: what reason does the applicant have for the application to be made urgently?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String MIAMUrgencyReasonLabel;
  @CCD(
          label = "Select all that apply",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String MIAMUrgencyReasonSelectAll;
  @CCD(
          label = "## MIAM Evidence : Previous MIAM attendance or MIAM exemption",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String MIAMPreviousAttendanceLabel;
  @CCD(
          label = "## MIAM Evidence: what other grounds of exemption apply?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String MIAMOtherGroundsLabel;
  @CCD(
          label = "## Enter details of MIAM certification",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String MIAMCertificationPageLabel;
  @CCD(
          label = "**You should have a document signed by the mediator confirming this (which you should bring to your first hearing)**",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String MIAMCertificationPageMessagePaperCase;
  @CCD(
          label = "**You should have a document signed by the mediator confirming this. Please upload the document here in readiness for the hearing or bring a copy to your first hearing.**",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String MIAMCertificationPageMessageFormA;
  @CCD(
          label = "## Enter details of MIAM certification",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String MIAMCertificationPageLabel1;
  @CCD(
          label = "**You should have a document signed by the mediator confirming this (which you should bring to your first hearing)**",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String MIAMCertificationPageMessage1;
  @CCD(
          label = "## Do you want to upload any other documents ?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String promptForAnyDocumentLabel;
  @CCD(
          label = "## Upload other documents",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorCrudPlus1RolesAvwswjAccess.class}
  )
  private String uploadOtherDocumentLabel;
  @CCD(
          label = "# Saving your application\r\nOnce you have pressed ‘continue’ at the bottom of this page, you will have the opportunity to check your application and make any necessary amendments.\r\n\r\nTo save a copy of the application, please press the ‘submit’ button at the bottom of the page.\r\n\r\n# What happens next\r\nOnce you have saved a copy of your application, you will be directed to the case file. Here you can use the ‘Next Steps’ options on the top right of the file to administer the case.\r\n\r\nYou will have the option to:\r\n* Update the application\r\n* Authorise, pay for and submit the application\r\n\r\nPlease note, your application will not be sent to the Court and your payment will not be taken until you authorise, pay for and submit the application.\r\n\r\n# If you need help \r\nYou can contact the court if you need help. \r\n************************************************************\r\n",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String beforeSavePreConfirmation;
  @CCD(
          label = "## AUTHORISATION",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorCrudPlus1RolesAvwswjAccess.class}
  )
  private String authorisationTitle;
  @CCD(
          label = "# I am duly authorised by the Applicant to complete this application.",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorCrudPlus1RolesAvwswjAccess.class}
  )
  private String authorisationLabel;
  @CCD(
          label = "#### PAYMENT DETAILS",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorCrudPlus1RolesAvwswjAccess.class}
  )
  private String payment;
  @CCD(
          label = "Payment Method: **Fee Account**",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorCrudPlus1RolesAvwswjAccess.class}
  )
  private String paymentMethodPBA;
  @CCD(
          label = "Payment Method: **Help with fees**",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorCrudPlus1RolesAvwswjAccess.class}
  )
  private String paymentMethodHWF;
  @CCD(
          label = "Your fee reference: **${PBAreference}**",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorCrudPlus1RolesAvwswjAccess.class}
  )
  private String solicitorReferenceLabel;
  @CCD(
          label = "Fee account number: **${PBANumber}**",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorCrudPlus1RolesAvwswjAccess.class}
  )
  private String pbaFeeAccountNumber;
  @CCD(
          label = "Help with fee reference: **${HWFNumber}**",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorCrudPlus1RolesOpciwwAccess.class}
  )
  private String hwfFeeReferenceNumber;
  @CCD(
          label = "# Sending your application to the Court\r\nOnce you have pressed ‘continue’ at the bottom of this page, you will have the opportunity to check your authorisation and payment information and make any necessary amendments.\r\n\r\nWhen you are happy that the details you have entered are correct, please press the ‘submit’ button at the bottom of the page to send the application to the Court.\r\n\r\n# What happens next\r\nYou will see a confirmation page showing that the case has been submitted and explaining the next steps in the process.\r\n\r\n# If you need help \r\nYou can contact the court if you need help. \r\n************************************************************\r\n",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorCrudPlus1RolesAvwswjAccess.class}
  )
  private String makePaymentPreConfirmationInfoText;
  @CCD(
          label = "#### Time Estimate",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesSfvgopAccess.class}
  )
  private String timeEstimateLabel;
  @CCD(
          label = "#### Hearing Date",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesSfvgopAccess.class}
  )
  private String hearingDateLabel;
  @CCD(
          label = "#### Additional information about the hearing",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesSfvgopAccess.class}
  )
  private String additionalInformationAboutHearingLabel;
  @CCD(
          label = "#### Do you want to upload any other documents ?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesSfvgopAccess.class}
  )
  private String additionalHearingDocumentsOptionLabel;
  @CCD(
          label = "#### Please upload any additional documents related to hearing.",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesSfvgopAccess.class}
  )
  private String additionalListOfHearingDocumentsLabel;
  @CCD(
          label = "Fast Track: Date of the Fast Track hearing must be between 6 and 10 weeks",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesSvbfxpAccess.class}
  )
  private String fastTrackWranMsg;
  @CCD(
          label = "\r\nExpress pilot: Date of the express pilot hearing should be between 16 and 20 weeks",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesSvbfxpAccess.class}
  )
  private String expressPilotWarnMsg;
  @CCD(
          label = "\r\nStandard Track: Date of the hearing must be between 12 and 16 weeks",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesSvbfxpAccess.class}
  )
  private String standardTrackWranMsg;
  @CCD(
          label = "#### Hearing Time",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesSfvgopAccess.class}
  )
  private String hearingTimeLabel;
  @CCD(
          label = "#### Hearing Court",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudAccess.class}
  )
  private String chooseCourtLabelSL;
  @CCD(
          label = "## The hearing centre for the case is:",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyJudiciaryCrudAccess.class}
  )
  private String chooseCourtLabelGA;
  @CCD(
          label = "## The application is suitable to be heard by a:",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesYcfimvAccess.class}
  )
  private String judgeAllocatedLabel;
  @CCD(
          label = "## Should the application be dealt with as a ‘complex case’?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesYcfimvAccess.class}
  )
  private String applicationAllocatedToLabel;
  @CCD(
          label = "## Should this case be allocated to the Express Pilot?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class}
  )
  private String shouldAllocateToExpressPilotLabel;
  @CCD(
          label = "## Should the application be allocated to the Fast Track?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesYcfimvAccess.class}
  )
  private String caseAllocatedToLabel;
  @CCD(
          label = "The types of cases to which the fast track procedure applies are set out in rule 9.9B of the Family Procedure Rules 2010. This rule came into force on 4 June 2018.",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesYcfimvAccess.class}
  )
  private String caseAllocatedToDescription;
  @CCD(
          label = "## Time Estimate for First Appointment Hearing (please specify):",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesYcfimvAccess.class}
  )
  private String judgeTimeEstimateLabel;
  @JsonProperty("CaseHistoryViewer")
  @CCD(
          label = "CaseHistoryViewer",
          searchable = false,
          typeOverride = FieldType.CaseHistoryViewer,
          access = {CREATORRAccess.class}
  )
  private String caseHistoryViewer;
  @CCD(label = "Custom Payment History Viewer", searchable = false, typeOverride = FieldType.CasePaymentHistoryViewer)
  private String casePaymentHistoryViewer;
  @CCD(
          label = "## Upload case documents",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String uploadCaseDocumentLabel;
  @CCD(
          label = "## General Application",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorRAccess.class}
  )
  private String generalApplicationLabel;
  @CCD(
          label = "## Order for children",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCudPlus1RolesQgxjxfAccess.class}
  )
  private String orderForChildrenLabel;
  @CCD(
          label = "#### Does anyone in this application need assistance or special facilities when attending court?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesYcfimvAccess.class}
  )
  private String attendingCourtWithAssistanceLabel;
  @CCD(
          label = "#### Does anyone in this application need specific arrangements when attending court?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesYcfimvAccess.class}
  )
  private String attendingCourtWithArrangementLabel;
  @CCD(
          label = "#### Please select the solicitor responsible to draft the order",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesYcfimvAccess.class}
  )
  private String solicitorResponsibleForDraftingOrderLabel;
  @CCD(
          label = "## Special Measures (Application)",
          hint = "Special Measures (Application)",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String specialMeasuresApplicationLbl;
  @CCD(
          label = "## Special Measures (Post Hearing)",
          hint = "Special Measures (Post Hearing)",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String specialMeasuresPostHearingLbl;
  @CCD(
          label = "## First Hearing (caseworker S&L)",
          hint = "First Hearing (caseworker S&L)",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorRAccess.class}
  )
  private String firsttHearingLbl;
  @CCD(label = "## Nature of application", searchable = false, typeOverride = FieldType.Label)
  private String tabNatureOfApplication;
  @CCD(
          label = "**What payments are you applying for**",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorRAccess.class}
  )
  private String tabBenefitPaymentChecklistLabel;
  @CCD(
          label = "**Does the application contain any periodical payments or secured periodical payments for children**",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabPaymentForChildrenLabel;
  @CCD(
          label = "**Has a written agreement been made about maintenance for the benefit of children**",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabBenefitForChildrenLabel;
  @CCD(
          label = "**Applicant name** : ${applicantFMName} ${applicantLName}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabApplicantName;
  @CCD(label = "**Applicant Solicitor**: ${applicantSolicitorFirm}", searchable = false, typeOverride = FieldType.Label)
  private String tabApplicantSolicitorFirm;
  @CCD(
          label = "**Respondent Name**: ${respondentFMName} ${respondentLName}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabRespondentName;
  @CCD(label = "**Respondent Solicitor**: ${rSolicitorFirm}", searchable = false, typeOverride = FieldType.Label)
  private String tabRespondentSolicitorFirm;
  @CCD(label = "**Respondent unrepresented**", searchable = false, typeOverride = FieldType.Label)
  private String tabRespondentUnrepresented;
  @CCD(
          label = "**Solicitor Reference** :  ${solicitorReference}",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class}
  )
  private String tabSolicitorReference;
  @CCD(
          label = "**Date of marriage / civil partnership** : ${dateOfMarriage}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabDateOfMarriage;
  @CCD(label = "**Case reference** : ${divorceCaseNumber}", searchable = false, typeOverride = FieldType.Label)
  private String tabCcdCaseNumber;
  @CCD(label = "**Date of separation** : ${dateOfSepration}", searchable = false, typeOverride = FieldType.Label)
  private String tabDateOfSepration;
  @CCD(
          label = "**Name of Court / Divorce Centre where petition issued**: ${nameOfCourtDivorceCentre}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabNameOfCourtDivorceCentre;
  @CCD(
          label = "**Decree Absolute Date** : ${divorceDecreeAbsoluteDate}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabDivorceDecreeAbsoluteDate;
  @CCD(label = "**Date order granted** : ${divorceDecreeNisiDate}", searchable = false, typeOverride = FieldType.Label)
  private String tabDivorceDecreeNisiDate;
  @CCD(
          label = "**Application Issued Date** : ${divorcePetitionIssuedDate}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabDivorcePetitionIssuedDate;
  @CCD(label = "## Complexity:", searchable = false, typeOverride = FieldType.Label)
  private String tabComplexityLabel;
  @CCD(
          label = "The Applicants solicitor has stated that this application should be allocated to the Complexity List of the Financial Remedies Court.",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabComplexityList;
  @CCD(
          label = "The Applicants solicitor has stated that this application should be allocated to the Standard List of the Financial Remedies Court.",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabStandardList;
  @CCD(
          label = "The Applicants solicitor is unsure as to whether the application should be allocated to the Complexity List or to the Standard List of the Financial Remedies Court.",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabUnsureAboutComplexityList;
  @CCD(
          label = "**The assets in this case are currently estimated to be in the order of**  ${estimatedAssetsChecklist}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabEstimatedAssestsCheckList;
  @CCD(
          label = "**The net assets in this case are currently estimated to be in the order of**  ${estimatedAssetsChecklistV2}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabEstimatedAssetsCheckList2;
  @CCD(
          label = "**The net assets in this case are currently estimated to be in the order of**  ${estimatedAssetsChecklistV3}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabEstimatedAssetsCheckList3;
  @CCD(
          label = "**The net value of the family home is** ${netValueOfHome}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabNetValueOfHome;
  @CCD(
          label = "**Potential allegations/issues which may arise include** :  ${potentialAllegationChecklist}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabPotentialAllegationChecklist;
  @CCD(
          label = "**Brief details of the potential allegation/issue** : ${detailPotentialAllegation}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabDetailPotentialAllegation;
  @CCD(
          label = "**Other reasons why the case should be allocated to the complexity list**: ${otherReasonForComplexityText}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabOtherReasonForComplexity;
  @CCD(
          label = "**Is the application dealt under the Fast Track Procedure** : ${fastTrackDecision}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabFastTrackDecision;
  @CCD(
          label = "**Reason for fast track decision**: ${fastTrackDecisionReason}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabFastTrackDecisionReason;
  @CCD(label = "## Judges Listing Directions ", searchable = false, typeOverride = FieldType.Label)
  private String tabJudgesListingDirectionsLabel;
  @CCD(label = "**The hearing centre for the case is:**  ", searchable = false, typeOverride = FieldType.Label)
  private String tabAllocatedCourtListGA;
  @CCD(
          label = "**Time Estimate for First Appointment Hearing (please specify):**",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabJudgeTimeEstimateLabel;
  @CCD(
          label = "**Should the application be allocated to the Fast Track?**",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabCaseAllocatedToLabel;
  @CCD(
          label = "**Should the application be dealt with as a ‘complex case’?**",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabApplicationAllocatedToLabel;
  @CCD(label = "**The application is suitable to be heard by a:**", searchable = false, typeOverride = FieldType.Label)
  private String tabJudgeAllocatedLabel;
  @CCD(
          label = "**Does anyone in this application need assistance or special facilities when attending court?**  : ${specialAssistanceRequired}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabSpecialAssistanceRequired;
  @CCD(
          label = "**Does anyone in this application need specific arrangements when attending court?** : ${specificArrangementsRequired}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabSpecificArrangementsRequired;
  @CCD(
          label = "#### NATURE OF THE APPLICATION",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorRAccess.class}
  )
  private String consentNatureOfApplicationLabel;
  @CCD(
          label = "### WARNING: Please note, this process should only be used to lodge a consent order in full and final settlement of your contested financial remedy application. For other applications please use the general application event.",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorRAccess.class}
  )
  private String warningMessage;
  @CCD(
          label = "#### ORDER FOR CHILDREN",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class}
  )
  private String consentOrderForChildrenQuestionLabel;
  @CCD(
          label = "#### CONSENT ORDER",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesUoltzlAccess.class}
  )
  private String consentOrderLabel;
  @CCD(
          label = "#### D81",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesUoltzlAccess.class}
  )
  private String consentD81Label;
  @CCD(
          label = "#### PENSION DOCUMENTS",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesUoltzlAccess.class}
  )
  private String consentPensionCollectionLabel;
  @CCD(
          label = "#### OTHER DOCUMENTS",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesUoltzlAccess.class}
  )
  private String consentOtherCollectionLabel;
  @CCD(
          label = "# Saving your application\r\nOnce you have pressed ‘continue’ at the bottom of this page, you will have the opportunity to check your application and make any necessary amendments.\r\n\r\nTo save a copy of the application, please press the ‘submit’ button at the bottom of the page.\r\n\r\n# What happens next\r\n  Once you have submitted your application, it will be forwarded to the nominated FRC for processing. \r\n\r\nIf a fee is required we will contact you to arrange payment. \r\n\r\n# If you need help \r\nYou can contact the court if you need help. \r\n************************************************************\r\n",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesUoltzlAccess.class}
  )
  private String consentOrderPreSaveText;
  @CCD(
          label = "## CONSENT ORDER PROCESS",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedySolicitorRAccess.class}
  )
  private String tabConsentOrderProcess;
  @CCD(
          label = "If you do not add an email address then no notification will be sent.",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRAccess.class}
  )
  private String generalApplicationReferToJudgeEmailWarning;
  @CCD(
          label = "#### Do you want to share your non-confidential documents with the other party?",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String shareDocsLabel;
  @JsonProperty("LabelState")
  @CCD(
          label = "#### Case State: ${[STATE]}",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {RESPBARRISTERCrudAccess.class, RESPSOLICITORCudAccess.class}
  )
  private String labelState;
  @CCD(
          label = "## Interim Hearing (caseworker S&L)",
          hint = "Interim Hearing (caseworker S&L)",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorRAccess.class}
  )
  private String interimHearingLbl;
  @CCD(
          label = "## Do you want to upload any other documents ?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesSfvgopAccess.class}
  )
  private String interimPromptForAnyDocumentLabel;
  @CCD(
          label = "## Upload other documents",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesSfvgopAccess.class}
  )
  private String interimUploadOtherDocumentLabel;
  @CCD(
          label = "## Hearing Court",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesSfvgopAccess.class, CaseworkerCaaRAccess.class, CaseworkerDivorceSystemupdateCrudAccess.class}
  )
  private String hearingCourtLabel;
  @CCD(
          label = "## Applicant's Barristers",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class}
  )
  private String appBarristerCollectionLabel;
  @CCD(
          label = "## Respondent's Barristers",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class}
  )
  private String respBarristerCollectionLabel;
  @CCD(
          label = "## Intervener's Barristers",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, INTVRBARRISTER1RPlus7RolesCzukhwAccess.class}
  )
  private String intvr1BarristerCollectionLabel;
  @CCD(
          label = "## Intervener's Barristers",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, INTVRBARRISTER1RPlus7RolesCzukhwAccess.class}
  )
  private String intvr2BarristerCollectionLabel;
  @CCD(
          label = "## Intervener's Barristers",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, INTVRBARRISTER1RPlus7RolesCzukhwAccess.class}
  )
  private String intvr3BarristerCollectionLabel;
  @CCD(
          label = "## Intervener's Barristers",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, INTVRBARRISTER1RPlus7RolesCzukhwAccess.class}
  )
  private String intvr4BarristerCollectionLabel;
  @CCD(
          label = "Select Party to which the barrister change applies: ",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorRAccess.class}
  )
  private String barristerPartyLabel;
  @CCD(
          label = "## Upload original order to be varied",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus2RolesUoltzlAccess.class, CaseworkerCaaCrudAccess.class, CaseworkerDivorceFinancialremedyCrudAccess.class}
  )
  private String variationOrderDocumentLabel;
  @CCD(
          label = "## What type of application is this?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class, CaseworkerApproverCrudCaseworkerCaaCudAccess.class}
  )
  private String typeOfApplicationLabel;
  @CCD(
          label = "## Child(ren) details",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {DefaultAccess.class, CaseworkerApproverCrudCaseworkerCaaCudAccess.class}
  )
  private String childrenDetailsLabel;
  @CCD(
          label = "## First Intervener Details",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, INTVRSOLICITOR1RPlus4RolesIvknqaAccess.class}
  )
  private String intervener1Label;
  @CCD(
          label = "## Second Intervener Details",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, INTVRSOLICITOR1RPlus4RolesIvknqaAccess.class}
  )
  private String intervener2Label;
  @CCD(
          label = "## Third Intervener Details",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, INTVRSOLICITOR1RPlus4RolesIvknqaAccess.class}
  )
  private String intervener3Label;
  @CCD(
          label = "## Fourth Intervener Details",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, INTVRSOLICITOR1RPlus4RolesIvknqaAccess.class}
  )
  private String intervener4Label;
  @CCD(
          label = "Launch the Flags screen",
          searchable = false,
          typeOverride = FieldType.FlagLauncher,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesEnaquoAccess.class}
  )
  private String flagLauncher;
  @CCD(
          label = "## Select the documents you wish to share",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEunwzwAccess.class}
  )
  private String documentsLabel;
  @CCD(
          label = "## Documents must be shared with either both applicant and respondent or neither",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String shareDocumentsBothPartiesWarning;
  @CCD(
          label = "## Share documents with",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEunwzwAccess.class}
  )
  private String rolesLabel;
  @CCD(
          label = "## Warning: This event will clear any existing organisation and set the default role. Do you want to continue?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedySuperuserRAccess.class}
  )
  private String cautionMessage;
  @CCD(
          label = "Case File View",
          searchable = false,
          typeOverride = FieldType.ComponentLauncher,
          access = {CaseworkerDivorceFinancialremedyCourtadminCuPlus1RolesOsjhrjAccess.class, CaseworkerDivorceFinancialremedySuperuserCruAccess.class}
  )
  private String caseFileViewComponentLauncher;
  @CCD(
          label = "<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>You may need to change the state if you remove any documents that were waiting to be processed e.g orders, consent orders, general applications</strong></div><br>",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudAccess.class, CaseworkerDivorceFinancialremedySuperuserCrudAccess.class}
  )
  private String documentRemovalStateWarning;
  @CCD(
          label = "<a href=\"/cases/case-details/${[CASE_REFERENCE]}/trigger/FR_approveOrders/\">Approve orders</a>",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String draftOrdersApproveOrdersLink;
  @CCD(
          label = "If the order is not agreed following the hearing, the parties should refer any disputes to the judge by email or as otherwise agreed.",
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEunwzwAccess.class}
  )
  private String uploadDraftOrdersDisputesGuidance;
  @CCD(
          label = "Use the '<a href=\"/cases/case-details/${[CASE_REFERENCE]}/trigger/createGeneralApplication/createGeneralApplication1\">create general application</a>' event if you need to upload a draft order to:<ul><li>apply to adjourn a hearing</li><li>ask for an order within proceedings</li></ul>",
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEunwzwAccess.class}
  )
  private String generalApplicationGuidance;
  @CCD(
          label = "${consentApplicationGuidanceText}",
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCruPlus1RolesChccdnAccess.class}
  )
  private String consentApplicationGuidance;
  @CCD(
          label = "<div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>This page is limited to showing only 5 draft orders/pension sharing annexes requiring review. There are additional draft orders/pension sharing annexes requiring review that are not shown.</strong></div><br>",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyJudiciaryRuAccess.class}
  )
  private String warningMessageToJudgeLabel;
  @CCD(
          label = "You have been automatically entered into the 'express financial remedy procedure' pilot. This is because you have noted that you and the respondent's estimated total combined net assets are £250,000 or less, and your case has been allocated to one of the participating courts.\r\n\r\nYou can find out more information on the pilot procedure here:\r\n<a href=\"https://www.gov.uk/guidance/what-to-expect-if-you-are-in-the-express-financial-remedy-pilot\" target=\"_blank\">https://www.gov.uk/guidance/what-to-expect-if-you-are-in-the-express-financial-remedy-pilot/</a>, this will open a new tab.",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesGpeopvAccess.class}
  )
  private String suitableForExpressCaseLabel;
  @CCD(
          label = "## Your application has been entered into the Express Financial Remedy Pilot.\r\n\r\nThe pilot aims to reduce the time taken to resolve contested financial remedy cases where the parties' estimated total combined net assets are £250,000 or less.\r\n\r\nThis application has automatically entered into the pilot because you have noted the parties' estimated total combined net assets are £250,000 or less; and the case has been allocated to one of the participating courts.\r\n\r\nThe term estimated 'total combined net assets' refers to the combined value of the applicant's and the respondent's assets (excluding pension rights or Pension Protection Fund compensation entitlement) after the deduction of liabilities and mortgages.\r\n\r\nYou can find out more information on the pilot which includes changes to filing and listing times here:\r\n<a href=\"https://www.gov.uk/guidance/what-to-expect-if-you-are-in-the-express-financial-remedy-pilot\" target=\"_blank\">https://www.gov.uk/guidance/what-to-expect-if-you-are-in-the-express-financial-remedy-pilot/</a>, this will open a new tab.",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesGpeopvAccess.class}
  )
  private String suitableForExpressCaseAmendmentLabel;
  @CCD(
          label = "## Your application will no longer be entered in the Express Financial Remedy Pilot.\r\n\r\nTo be entered into the pilot the parties' estimated total combined net assets have to be £250,000 or less; and the case has to be allocated to one of the participating courts.\r\n\r\nAny Fast Track case or a Variation application will not meet the requirements of the pilot.\r\n\r\nYour application will no longer be entered into the pilot as answers have been updated that cause the application to no longer meet the pilot requirements.",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminCrudPlus1RolesGpeopvAccess.class}
  )
  private String unsuitableForExpressCaseAmendmentLabel;
  @CCD(
          label = "### Express Pilot Participation: ${expressCaseParticipation}",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabExpressCaseParticipation;
  @CCD(
          label = "Warning: Once you remove a case from the Express Financial Remedy Pilot, it cannot be re-added so this will be a permanent change.",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRAccess.class}
  )
  private String removeFromExpressPilotWarning;
  @CCD(
          label = "This case was removed from the Express Financial Remedy Pilot.",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRAccess.class}
  )
  private String expressPilotWasWithdrawnLabel;
  @CCD(
          label = "This case is not enrolled in the Express Financial Remedy Pilot.",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRAccess.class}
  )
  private String expressPilotNotEnrolledLabel;
  @CCD(
          label = "## This case was automatically entered into the Express Pilot, should this case remain in the Express Pilot?",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyJudiciaryRAccess.class}
  )
  private String judgeAgreesCaseIsExpressLabel;
  @CCD(
          label = "**This case was automatically entered into the Express Pilot, should this case remain in the Express Pilot?**",
          searchable = false,
          typeOverride = FieldType.Label
  )
  private String tabJudgeAgreesCaseIsExpressLabel;
  @CCD(
          label = "<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Altering the court may impact this case proceeding in the Express Pilot</strong></div><br>",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class}
  )
  private String alteringCourtImpactExpressPilotCaseWarning;
  @CCD(
          label = "#### DIVORCE ORDER",
          searchable = false,
          typeOverride = FieldType.Label,
          access = {CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesEhdmahAccess.class, CaseworkerDivorceFinancialremedySolicitorRAccess.class}
  )
  private String divorceOrderLabel;
}
