package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@Data
@NoArgsConstructor
@ComplexType(
        name = "CU_ct_citizenRespondentDocument",
        generate = true
)
public class CUCtCitizenRespondentDocument {
}
