package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "FR_ct_uploadOrder",
        generate = true
)
public class FRCtUploadOrder {
    @JsonProperty("DocumentType")
    @CCD(
            label = "Type",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "FR_fl_consentOrderType"
    )
    private FRFlConsentOrderType documentType;

    @JsonProperty("DocumentEmailContent")
    @CCD(
            label = "Email content",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String documentEmailContent;

    @JsonProperty("DocumentLink")
    @CCD(
            label = "Document Url",
            categoryID = "administrativeDocumentsTransitional",
            searchable = false
    )
    private Document documentLink;

    @JsonProperty("DocumentDateAdded")
    @CCD(
            label = "Date received",
            searchable = false
    )
    private LocalDate documentDateAdded;

    @JsonProperty("DocumentComment")
    @CCD(
            label = "Comment",
            searchable = false
    )
    private String documentComment;

    @JsonProperty("DocumentFileName")
    @CCD(
            label = "File name",
            searchable = false
    )
    private String documentFileName;
}
