package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "FR_ct_draftDirectionOrder",
        generate = true
)
public class FRCtDraftDirectionOrder {
    @CCD(
            label = "Purpose of Document",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "FR_fl_purposeOfDocument"
    )
    private FRFlPurposeOfDocument purposeOfDocument;

    @CCD(
            label = "Upload Draft Document",
            regex = ".doc,.docx,.pdf",
            searchable = false
    )
    private Document uploadDraftDocument;

    @CCD(
            label = "Is this the final order?",
            searchable = false
    )
    private YesOrNo isFinalOrder;

    @CCD(
            label = "Additional attachments",
            hint = "Please upload any additional attachments. You must upload Microsoft Word or PDF documents",
            searchable = false
    )
    private List<ListValue<Document>> additionalDocuments;
}
