package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import java.time.LocalDateTime;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.ListValue;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "FR_ct_directionOrderCollection",
        generate = true
)
public class FRCtDirectionOrderCollection {
    @CCD(
            label = "Upload Document",
            hint = "PLEASE NOTE: You must upload a Word or PDF version of document",
            categoryID = "approvedOrders",
            searchable = false
    )
    private Document uploadDraftDocument;

    @CCD(
            label = "Is this a final order?",
            searchable = false
    )
    private YesOrNo isFinalOrder;

    @CCD(
            label = "Order created at",
            showCondition = "uploadDraftDocument=\"DONOTSHOW\"",
            searchable = false
    )
    private LocalDateTime orderDateTime;

    @CCD(
            label = "Order stamped",
            showCondition = "uploadDraftDocument=\"DONOTSHOW\"",
            searchable = false
    )
    private YesOrNo isOrderStamped;

    @CCD(
            label = "Original Document",
            showCondition = "uploadDraftDocument=\"DONOTSHOW\"",
            searchable = false
    )
    private Document originalDocument;

    @CCD(
            label = "Additional attachments",
            categoryID = "approvedOrders",
            searchable = false
    )
    private List<ListValue<Document>> additionalDocuments;
}
