package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@ComplexType(
        name = "FR_fl_EvidenceParty",
        generate = true
)
@Getter
@AllArgsConstructor
public enum FRFlEvidenceParty implements HasLabel {
    APPLICANT("Applicant", "applicant"),

    RESPONDENT("Respondent", "respondent"),

    INTERVENER1("Intervener1", "intervener1"),

    INTERVENER2("Intervener2", "intervener2"),

    INTERVENER3("Intervener3", "intervener3"),

    INTERVENER4("Intervener4", "intervener4"),

    CASE_("Case", "case");

    private final String label;

    @JsonValue
    private final String code;
}
