package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@ComplexType(
        name = "FR_fl_postStateOption",
        generate = true
)
@Getter
@AllArgsConstructor
public enum FRFlPostStateOption implements HasLabel {
    PREPARE_FOR_HEARING("Prepare for Hearing", "prepareForHearing"),

    CLOSE("Close", "close"),

    ORDER_SENT("Order Sent", "orderSent");

    private final String label;

    @JsonValue
    private final String code;
}
