package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@ComplexType(
        name = "FR_fl_AssignToJudgeReason",
        generate = true
)
@Getter
@AllArgsConstructor
public enum FRFlAssignToJudgeReason implements HasLabel {
    DRAFT_CONSENT_ORDER("Draft consent order", "Draft consent order"),

    RESUBMITTED_DRAFT_CONSENT_ORDER("Resubmitted draft consent order", "Resubmitted draft consent order");

    private final String label;

    @JsonValue
    private final String code;
}
