package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@ComplexType(
        name = "FR_fl_uploadGeneralDocument",
        generate = true
)
@Getter
@AllArgsConstructor
public enum FRFlUploadGeneralDocument implements HasLabel {
    OTHER("Other", "Other"),

    STATEMENT_REPORT("Statement / Report", "Statement / Report"),

    DRAFT_ORDER("Draft Order", "Draft Order"),

    APPLICATION("Application", "Application"),

    LETTER_EMAIL_FROM_RESPONDENT_SOLICITOR("Letter/Email from Respondent Solicitor", "Letter/Email from Respondent Solicitor"),

    LETTER_EMAIL_FROM_RESPONDENT("Letter/Email from Respondent ", "Letter/Email from Respondent"),

    LETTER_EMAIL_FROM_APPLICANT_SOLICITOR("Letter/Email from Applicant Solicitor", "Letter/Email from Applicant Solicitor"),

    LETTER_EMAIL_FROM_APPLICANT("Letter/Email from Applicant", "Letter/Email from Applicant"),

    NOTICE_OF_ACTING("Notice of Acting", "Notice of Acting"),

    CONDITIONAL_ORDER("Conditional order", "Conditional order"),

    FINAL_ORDER("Final order", "Final order");

    private final String label;

    @JsonValue
    private final String code;
}
