package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@ComplexType(
        name = "FR_fl_RefusalOrderJudgeType",
        generate = true
)
@Getter
@AllArgsConstructor
public enum FRFlRefusalOrderJudgeType implements HasLabel {
    DISTRICT_JUDGE("District Judge", "District Judge"),

    DEPUTY_DISTRICT_JUDGE("Deputy District Judge", "Deputy District Judge"),

    HIS_HONOUR_JUDGE("His Honour Judge", "His Honour Judge"),

    HER_HONOUR_JUDGE("Her Honour Judge", "Her Honour Judge"),

    RECORDER("Recorder", "Recorder"),

    THE_HONOURABLE_MR_JUSTICE("The Honourable Mr Justice", "The Honourable Mr Justice"),

    THE_HONOURABLE_MRS_JUSTICE("The Honourable Mrs Justice", "The Honourable Mrs Justice"),

    THE_HONOURABLE_MS_JUSTICE("The Honourable Ms Justice", "The Honourable Ms Justice");

    private final String label;

    @JsonValue
    private final String code;
}
