package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@ComplexType(
        name = "FR_london_FRCList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum FRLondonFRCList implements HasLabel {
    CFC("London FRC", "cfc");

    private final String label;

    @JsonValue
    private final String code;
}
