package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "FR_manageCaseDocuments",
        generate = true
)
public class FRManageCaseDocuments {
    @CCD(
            label = "Update",
            searchable = false
    )
    private YesOrNo selectForUpdate;

    @CCD(
            label = "Please upload any case documents",
            searchable = false
    )
    private Document caseDocuments;

    @CCD(
            label = "Scanned Date",
            searchable = false
    )
    private LocalDateTime scannedDate;

    @CCD(
            label = "File Name",
            searchable = false
    )
    private String fileName;

    @CCD(
            label = "Document type",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "FR_s_caseDocumentType"
    )
    private FRSCaseDocumentType caseDocumentType;

    @CCD(
            label = "Please specify document type",
            showCondition = "caseDocumentType=\"other\"",
            searchable = false
    )
    private String caseDocumentOther;

    @CCD(
            label = "Provide the date of hearing and a description of the document",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String hearingDetails;

    @CCD(
            label = "Is the document confidential?",
            hint = "Document will be placed in the confidential documents tab visible to caseworkers and judges only",
            showCondition = "caseDocumentType!=\"Without Prejudice offers\" AND caseDocumentType!=\"Attendance Sheets\" AND caseDocumentType!=\"Judicial notes\" AND caseDocumentType!=\"Judgment\" AND caseDocumentType!=\"Witness Summons\" AND caseDocumentType!=\"Transcript\"",
            searchable = false
    )
    private YesOrNo caseDocumentConfidentiality;

    @CCD(
            label = "###### ‘Confidential’ should only be selected for documents that you would never want to share with another party, for example a Form C8 for confidential address, or documents relating to a lock and key cases etc.",
            showCondition = "caseDocumentType!=\"Without Prejudice offers\" AND caseDocumentType!=\"Attendance Sheets\" AND caseDocumentType!=\"Judicial notes\" AND caseDocumentType!=\"Judgment\" AND caseDocumentType!=\"Witness Summons\" AND caseDocumentType!=\"Transcript\"",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String caseDocumentConfidentialityWarning0;

    @CCD(
            label = "\n"
                            + "\n"
                            + "###### &nbsp;",
            showCondition = "caseDocumentType!=\"Without Prejudice offers\" AND caseDocumentType!=\"Attendance Sheets\" AND caseDocumentType!=\"Judicial notes\" AND caseDocumentType!=\"Judgment\" AND caseDocumentType!=\"Witness Summons\" AND caseDocumentType!=\"Transcript\"",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String caseDocumentConfidentialityWarning1;

    @CCD(
            label = "###### Do not use the confidential option to upload a document that you later intend to share as once confidential you will not be able to share it.",
            showCondition = "caseDocumentType!=\"Without Prejudice offers\" AND caseDocumentType!=\"Attendance Sheets\" AND caseDocumentType!=\"Judicial notes\" AND caseDocumentType!=\"Judgment\" AND caseDocumentType!=\"Witness Summons\" AND caseDocumentType!=\"Transcript\"",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String caseDocumentConfidentialityWarning2;

    @CCD(
            label = "\n"
                            + "\n"
                            + "###### &nbsp;",
            showCondition = "caseDocumentType!=\"Without Prejudice offers\" AND caseDocumentType!=\"Attendance Sheets\" AND caseDocumentType!=\"Judicial notes\" AND caseDocumentType!=\"Judgment\" AND caseDocumentType!=\"Witness Summons\" AND caseDocumentType!=\"Transcript\"",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String caseDocumentConfidentialityWarning3;

    @CCD(
            label = "###### Do not select confidential if you are only waiting to exchange documents.",
            showCondition = "caseDocumentType!=\"Without Prejudice offers\" AND caseDocumentType!=\"Attendance Sheets\" AND caseDocumentType!=\"Judicial notes\" AND caseDocumentType!=\"Judgment\" AND caseDocumentType!=\"Witness Summons\" AND caseDocumentType!=\"Transcript\"",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String caseDocumentConfidentialityWarning4;

    @CCD(
            label = "\n"
                            + "\n"
                            + "###### &nbsp;",
            showCondition = "caseDocumentType!=\"Without Prejudice offers\" AND caseDocumentType!=\"Attendance Sheets\" AND caseDocumentType!=\"Judicial notes\" AND caseDocumentType!=\"Judgment\" AND caseDocumentType!=\"Witness Summons\" AND caseDocumentType!=\"Transcript\"",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String caseDocumentConfidentialityWarning5;

    @CCD(
            label = "###### Parties cannot see a document you upload until you formally share it with them within the portal UNLESS it is a FDR document, in which case they will be able to see it immediately without it being formally shared.",
            showCondition = "caseDocumentType!=\"Without Prejudice offers\" AND caseDocumentType!=\"Attendance Sheets\" AND caseDocumentType!=\"Judicial notes\" AND caseDocumentType!=\"Judgment\" AND caseDocumentType!=\"Witness Summons\" AND caseDocumentType!=\"Transcript\"",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String caseDocumentConfidentialityWarning6;

    @CCD(
            label = "\n"
                            + "\n"
                            + "###### &nbsp;",
            showCondition = "caseDocumentType!=\"Without Prejudice offers\" AND caseDocumentType!=\"Attendance Sheets\" AND caseDocumentType!=\"Judicial notes\" AND caseDocumentType!=\"Judgment\" AND caseDocumentType!=\"Witness Summons\" AND caseDocumentType!=\"Transcript\"",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String caseDocumentConfidentialityWarning7;

    @CCD(
            label = "Is this a Financial Dispute Resolution document (FDR)?",
            hint = "Document will be placed in the FDR documents tab",
            showCondition = "caseDocumentConfidentiality=\"No\" AND caseDocumentType!=\"Without Prejudice offers\" AND caseDocumentType!=\"Attendance Sheets\" AND caseDocumentType!=\"Judicial notes\" AND caseDocumentType!=\"Judgment\" AND caseDocumentType!=\"Witness Summons\" AND caseDocumentType!=\"Transcript\"",
            searchable = false
    )
    private YesOrNo caseDocumentFdr;

    @CCD(
            label = "What type of document is this?",
            showCondition = "caseDocumentConfidentiality=\"No\" AND caseDocumentFdr=\"No\" AND caseDocumentType!=\"Attendance Sheets\" AND caseDocumentType!=\"Judicial notes\" AND caseDocumentType!=\"Judgment\" AND caseDocumentType!=\"Witness Summons\" AND caseDocumentType!=\"Transcript\"",
            searchable = false
    )
    private FRFlEvidenceParty caseDocumentParty;

    @CCD(
            label = "Upload DateTime",
            searchable = false
    )
    private LocalDateTime caseDocumentUploadDateTime;

    @CCD(
            label = "Scanned filename",
            searchable = false
    )
    private String scannedFileName;

    @CCD(
            label = "Exception record reference",
            searchable = false
    )
    private String exceptionRecordReference;
}
