package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "FR_manageCaseDocumentWarning",
        generate = true
)
public class FRManageCaseDocumentWarning {
    @CCD(
            label = "###### ‘Confidential’ should only be selected for documents that you would never want to share with another party, for example a Form C8 for confidential address, or documents relating to a lock and key cases etc.",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String warning0;

    @CCD(
            label = "\n"
                            + "\n"
                            + "###### &nbsp;",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String warning1;

    @CCD(
            label = "###### Do not use the confidential option to upload a document that you later intend to share as once confidential you will not be able to share it.",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String warning2;

    @CCD(
            label = "\n"
                            + "\n"
                            + "###### &nbsp;",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String warning3;

    @CCD(
            label = "###### Do not select confidential if you are only waiting to exchange documents.",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String warning4;

    @CCD(
            label = "\n"
                            + "\n"
                            + "###### &nbsp;",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String warning5;

    @CCD(
            label = "###### Parties cannot see a document you upload until you formally share it with them within the portal UNLESS it is a FDR document, in which case they will be able to see it immediately without it being formally shared.",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String warning6;

    @CCD(
            label = "\n"
                            + "\n"
                            + "###### &nbsp;",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String warning7;
}
