package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@ComplexType(
        name = "FR_ms_OrderRefusal",
        generate = true
)
@Getter
@AllArgsConstructor
public enum FRMsOrderRefusal implements HasLabel {
    INSUFFICIENT_INFORMATION_PROVIDED_A("Insufficient information has been provided as to the parties’ capital positions if the order were effected", "Insufficient information provided – A"),

    INSUFFICIENT_INFORMATION_PROVIDED_B("Insufficient information has been provided as to the parties’ housing needs and whether they are met by the order", "Insufficient information provided – B"),

    INSUFFICIENT_INFORMATION_PROVIDED_C("Insufficient information has been provided as to the justification for departure from equality of capital", "Insufficient information provided – C"),

    INSUFFICIENT_INFORMATION_PROVIDED_D("Insufficient information has been provided as to the parties’ pension provision if the order were effected", "Insufficient information provided – D"),

    INSUFFICIENT_INFORMATION_PROVIDED_E("Insufficient information has been provided as to the children’s housing needs and whether they are met by the order", "Insufficient information provided – E"),

    PENSION_ANNEX("The pension annex has not been attached", "Pension annex"),

    RESPONDENT_INDEPENDENT_LEGAL_ADVICE("It is unclear whether the Respondent has obtained independent legal advice", "Respondent – independent legal advice"),

    THE_D81_INCOMPLETE("The D81 form is incomplete", "The D81 incomplete"),

    HEARING_FIXED_FOR_FIRST_AVAILABLE_DATE("Application should be fixed for hearing on first available date for 20 minutes when the Court will consider whether the draft order should be approved. Both parties should attend and if they do not do so the Court may not approve the order", "Hearing fixed for first available date"),

    TRANSFERRED_TO_APPLICANT_S_HOME_COURT("Financial Remedy application to be transferred to the Applicant’s home court to consider listing directions", "Transferred to Applicant’s home Court"),

    TRANSFERRED_TO_APPLICANT_S_HOME_COURT_2("Entire case to be transferred to the Applicant’s home court to consider listing directions", "Transferred to Applicant's home Court"),

    ORDER_DOES_NOT_APPEAR_FAIR("The proposed order does not appear to be fair taking account of S25 Matrimonial Causes Act 1973.  The parties are requested to explain more fully the thinking behind the order and why it is fair.", "Order does not appear fair"),

    PROVIDE_PENSION_VALUES_PROPERTY("Please provide a breakdown of the pension values/property values as it is not possible to understand the values of what each party will receive.", "Provide pension values/property"),

    OTHER_PLEASE_SPECIFY("If other (please specify in text box provided)", "Other (please specify)");

    private final String label;

    @JsonValue
    private final String code;
}
