package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@ComplexType(
        name = "FR_ms_benefitPaymentChecklist",
        generate = true
)
@Getter
@AllArgsConstructor
public enum FRMsBenefitPaymentChecklist implements HasLabel {
    STEP_CHILD_OR_STEP_CHILDREN("For a stepchild or step children", "Step child or step children"),

    IN_ADDITION_TO_CHILD_SUPPORT_MAINTENANCE_ALREADY_PAID_UNDER_A_CHILD_SUPPORT_AGENCY_ASSESSMENT("In addition to child support or maintenance already paid under a Child Support Agency assessment", "In addition to child support maintenance already paid under a Child Support Agency assessment"),

    TO_MEET_EXPENSES_ARISING_FROM_A_CHILD_S_DISABILITY("To meet expenses arising from a child’s disability", "To meet expenses arising from a child’s disability"),

    TO_MEET_EXPENSES_INCURRED_BY_A_CHILD_BEING_IN_EDUCATED_OR_TRAINING_FOR_WORK("To meet expenses incurred by a child in relation to being educated or training for work", "To meet expenses incurred by a child being in educated or training for work"),

    THE_CHILD_OR_THE_PERSON_WITH_CARE_OF_THE_CHILD_OR_THE_ABSENT_PARENT_OF_THE_CHILD_IS_NOT_HABITUALLY_RESIDENT_IN_THE_UNITED_KINGDOM("When either the child or the person with care of the child or the absent parent of the child is not habitually resident in the United Kingdom", "The child or the person with care of the child or the absent parent of the child is not habitually resident in the United Kingdom");

    private final String label;

    @JsonValue
    private final String code;
}
