package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@ComplexType(
        name = "FR_nw_yorkshire_hc_list",
        generate = true
)
@Getter
@AllArgsConstructor
public enum FRNwYorkshireHcList implements HasLabel {
    FR_NW_YORKSHIRE_HC_LIST_1("Harrogate Justice Centre", "FR_nw_yorkshire_hc_list_1"),

    FR_NW_YORKSHIRE_HC_LIST_2("Bradford Combined Court Centre", "FR_nw_yorkshire_hc_list_2"),

    FR_NW_YORKSHIRE_HC_LIST_3("Huddersfield County Court and Family Court", "FR_nw_yorkshire_hc_list_3"),

    FR_NW_YORKSHIRE_HC_LIST_4("Wakefield Civil and Family Justice Centre", "FR_nw_yorkshire_hc_list_4"),

    FR_NW_YORKSHIRE_HC_LIST_5("York County Court and Family Court", "FR_nw_yorkshire_hc_list_5"),

    FR_NW_YORKSHIRE_HC_LIST_6("Scarborough Justice Centre", "FR_nw_yorkshire_hc_list_6"),

    FR_NW_YORKSHIRE_HC_LIST_7("Skipton County Court and Family Court", "FR_nw_yorkshire_hc_list_7"),

    FR_NW_YORKSHIRE_HC_LIST_8("Leeds Combined Court Centre", "FR_nw_yorkshire_hc_list_8");

    private final String label;

    @JsonValue
    private final String code;
}
