package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@ComplexType(
        name = "FR_s_CFCList",
        generate = true
)
@Getter
@AllArgsConstructor
public enum FRSCFCList implements HasLabel {
    FR_S_CFCLIST_1("BROMLEY COUNTY COURT AND FAMILY COURT", "FR_s_CFCList_1"),

    FR_S_CFCLIST_2("CROYDON COUNTY COURT AND FAMILY COURT", "FR_s_CFCList_2"),

    FR_S_CFCLIST_3("EDMONTON COUNTY COURT AND FAMILY COURT", "FR_s_CFCList_3"),

    FR_S_CFCLIST_4("KINGSTON-UPON-THAMES COUNTY COURT AND FAMILY COURT", "FR_s_CFCList_4"),

    FR_S_CFCLIST_5("ROMFORD COUNTY AND FAMILY COURT", "FR_s_CFCList_5"),

    FR_S_CFCLIST_6("BARNET CIVIL AND FAMILY COURTS CENTRE", "FR_s_CFCList_6"),

    FR_S_CFCLIST_8("BRENTFORD COUNTY AND FAMILY COURT", "FR_s_CFCList_8"),

    FR_S_CFCLIST_9("CENTRAL FAMILY COURT", "FR_s_CFCList_9"),

    FR_S_CFCLIST_11("EAST LONDON FAMILY COURT", "FR_s_CFCList_11"),

    FR_S_CFCLIST_14("UXBRIDGE COUNTY COURT AND FAMILY COURT", "FR_s_CFCList_14"),

    FR_S_CFCLIST_16("WILLESDEN COUNTY COURT AND FAMILY COURT", "FR_s_CFCList_16"),

    FR_S_CFCLIST_17("THE ROYAL COURT OF JUSTICE", "FR_s_CFCList_17");

    private final String label;

    @JsonValue
    private final String code;
}
