package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "FR_supportDocument",
        generate = true
)
public class FRSupportDocument {
    @CCD(
            label = "Supporting Document",
            hint = "Please upload a copy of the supporting document as a Word, PDF, or Excel document (Word/Excel documents will be converted to PDF after submission)",
            regex = ".doc,.docx,.pdf,.xls,.xlsx",
            searchable = false
    )
    private Document supportDocument;
}
