package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@ComplexType(
        name = "FR_swansea_hc_list",
        generate = true
)
@Getter
@AllArgsConstructor
public enum FRSwanseaHcList implements HasLabel {
    FR_SWANSEA_HC_LIST_1("Swansea Civil & Family Justice Centre", "FR_swansea_hc_list_1"),

    FR_SWANSEA_HC_LIST_2("Aberystwyth Justice Centre", "FR_swansea_hc_list_2"),

    FR_SWANSEA_HC_LIST_3("Haverfordwest County & Family Court", "FR_swansea_hc_list_3"),

    FR_SWANSEA_HC_LIST_4("Carmarthen County and Family Court", "FR_swansea_hc_list_4"),

    FR_SWANSEA_HC_LIST_5("Llanelli Law Courts", "FR_swansea_hc_list_5"),

    FR_SWANSEA_HC_LIST_6("Port Talbot Justice Centre", "FR_swansea_hc_list_6");

    private final String label;

    @JsonValue
    private final String code;
}
