package uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "FR_uploadCaseDocument",
        generate = true
)
public class FRUploadCaseDocument {
    @CCD(
            label = "Please upload any case documents",
            searchable = false
    )
    private Document caseDocuments;

    @CCD(
            label = "Document type",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "FR_s_caseDocumentType"
    )
    private FRSCaseDocumentType caseDocumentType;

    @CCD(
            label = "Please specify document type",
            showCondition = "caseDocumentType=\"other\"",
            searchable = false
    )
    private String caseDocumentOther;

    @CCD(
            label = "Provide the date of hearing and a description of the document",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String hearingDetails;

    @CCD(
            label = "Is the document confidential?",
            hint = "Document will be placed in the confidential documents tab visible to caseworkers and judges only",
            searchable = false
    )
    private YesOrNo caseDocumentConfidentiality;

    @CCD(
            label = "Is the document confidential?",
            hint = "This field was added back due to compatibility with cases dating pre-2021 and should not be used",
            showCondition = "caseDocumentConfidentiality=\"DONOTSHOW\"",
            searchable = false
    )
    private YesOrNo caseDocumentConfidential;

    @CCD(
            label = "Is this a Financial Dispute Resolution document (FDR)?",
            hint = "Document will be placed in the FDR documents tab",
            showCondition = "caseDocumentConfidentiality=\"No\"",
            searchable = false
    )
    private YesOrNo caseDocumentFdr;

    @CCD(
            label = "What type of document is this?",
            searchable = false
    )
    private FRFlEvidenceParty caseDocumentParty;

    @CCD(
            label = "Upload DateTime",
            searchable = false
    )
    private LocalDateTime caseDocumentUploadDateTime;

    @CCD(
            label = "File name",
            searchable = false
    )
    private String fileName;

    @CCD(
            label = "Original scanned file name",
            searchable = false
    )
    private String scannedFileName;

    @CCD(
            label = "Scanned Date",
            searchable = false
    )
    private LocalDateTime scannedDate;

    @CCD(
            label = "Exception record reference",
            searchable = false
    )
    private String exceptionRecordReference;
}
