package uk.gov.hmcts.reform.finrem.caseorchestration.model.document;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum ContestedUploadCaseFilesCollectionType {

    APPLICANT_CORRESPONDENCE_COLLECTION("appCorrespondenceCollection"),
    APPLICANT_CORRESPONDENCE_DOC_COLLECTION("appCorrespondenceDocsCollection"),
    APPLICANT_FR_FORM_COLLECTION("appFRFormsCollection"),
    APPLICANT_EVIDENCE_COLLECTION("appEvidenceCollection"),
    APPLICANT_TRIAL_BUNDLE_COLLECTION("appTrialBundleCollection"),
    APPLICANT_CONFIDENTIAL_DOCS_COLLECTION("appConfidentialDocsCollection"),
    RESPONDENT_CORRESPONDENCE_COLLECTION("respCorrespondenceCollection"),
    RESPONDENT_FR_FORM_COLLECTION("respFRFormsCollection"),
    RESPONDENT_EVIDENCE_COLLECTION("respEvidenceCollection"),
    RESPONDENT_TRIAL_BUNDLE_COLLECTION("respTrialBundleCollection"),
    RESPONDENT_CONFIDENTIAL_DOCS_COLLECTION("respConfidentialDocsCollection"),
    APP_HEARING_BUNDLES_COLLECTION("appHearingBundlesCollection"),
    APP_FORM_E_EXHIBITS_COLLECTION("appFormEExhibitsCollection"),
    APP_CHRONOLOGIES_STATEMENTS_COLLECTION("appChronologiesCollection"),
    APP_QUESTIONNAIRES_ANSWERS_COLLECTION("appQACollection"),
    APP_STATEMENTS_EXHIBITS_COLLECTION("appStatementsExhibitsCollection"),
    APP_CASE_SUMMARIES_COLLECTION("appCaseSummariesCollection"),
    APP_FORMS_H_COLLECTION("appFormsHCollection"),
    APP_EXPERT_EVIDENCE_COLLECTION("appExpertEvidenceCollection"),
    APP_CORRESPONDENCE_COLLECTION("appCorrespondenceDocsCollection"),
    APP_OTHER_COLLECTION("appOtherCollection"),
    RESP_HEARING_BUNDLES_COLLECTION("respHearingBundlesCollection"),
    RESP_FORM_E_EXHIBITS_COLLECTION("respFormEExhibitsCollection"),
    RESP_CHRONOLOGIES_STATEMENTS_COLLECTION("respChronologiesCollection"),
    RESP_QUESTIONNAIRES_ANSWERS_COLLECTION("respQACollection"),
    RESP_STATEMENTS_EXHIBITS_COLLECTION("respStatementsExhibitsCollection"),
    RESP_CASE_SUMMARIES_COLLECTION("respCaseSummariesCollection"),
    RESP_FORM_H_COLLECTION("respFormsHCollection"),
    RESP_EXPERT_EVIDENCE_COLLECTION("respExpertEvidenceCollection"),
    RESP_CORRESPONDENCE_COLLECTION("respCorrespondenceDocsColl"),
    RESP_OTHER_COLLECTION("respOtherCollection"),
    CONTESTED_UPLOADED_DOCUMENTS("uploadCaseDocument"),
    CONTESTED_FDR_CASE_DOCUMENT_COLLECTION("fdrCaseDocumentCollection"),


    //INTERVENER-ONE
    INTERVENER_ONE_SUMMARIES_COLLECTION("intv1Summaries"),
    INTERVENER_ONE_CHRONOLOGIES_STATEMENTS_COLLECTION("intv1Chronologies"),
    INTERVENER_ONE_CORRESPONDENCE_COLLECTION("intv1CorrespDocs"),
    INTERVENER_ONE_EXPERT_EVIDENCE_COLLECTION("intv1ExpertEvidence"),
    INTERVENER_ONE_FORM_E_EXHIBITS_COLLECTION("intv1FormEsExhibits"),
    INTERVENER_ONE_FORM_H_COLLECTION("intv1FormHs"),
    INTERVENER_ONE_HEARING_BUNDLES_COLLECTION("intv1HearingBundles"),
    INTERVENER_ONE_OTHER_COLLECTION("intv1Other"),
    INTERVENER_ONE_QUESTIONNAIRES_ANSWERS_COLLECTION("intv1Qa"),
    INTERVENER_ONE_STATEMENTS_EXHIBITS_COLLECTION("intv1StmtsExhibits"),

    //INTERVENER-TWO
    INTERVENER_TWO_SUMMARIES_COLLECTION("intv2Summaries"),
    INTERVENER_TWO_CHRONOLOGIES_STATEMENTS_COLLECTION("intv2Chronologies"),
    INTERVENER_TWO_CORRESPONDENCE_COLLECTION("intv2CorrespDocs"),
    INTERVENER_TWO_EXPERT_EVIDENCE_COLLECTION("intv2ExpertEvidence"),
    INTERVENER_TWO_FORM_E_EXHIBITS_COLLECTION("intv2FormEsExhibits"),
    INTERVENER_TWO_FORM_H_COLLECTION("intv2FormHs"),
    INTERVENER_TWO_HEARING_BUNDLES_COLLECTION("intv2HearingBundles"),
    INTERVENER_TWO_OTHER_COLLECTION("intv2Other"),
    INTERVENER_TWO_QUESTIONNAIRES_ANSWERS_COLLECTION("intv2Qa"),
    INTERVENER_TWO_STATEMENTS_EXHIBITS_COLLECTION("intv2StmtsExhibits"),


    //INTERVENER-THREE
    INTERVENER_THREE_SUMMARIES_COLLECTION("intv3Summaries"),
    INTERVENER_THREE_CHRONOLOGIES_STATEMENTS_COLLECTION("intv3Chronologies"),
    INTERVENER_THREE_CORRESPONDENCE_COLLECTION("intv3CorrespDocs"),
    INTERVENER_THREE_EXPERT_EVIDENCE_COLLECTION("intv3ExpertEvidence"),
    INTERVENER_THREE_FORM_E_EXHIBITS_COLLECTION("intv3FormEsExhibits"),
    INTERVENER_THREE_FORM_H_COLLECTION("intv3FormHs"),
    INTERVENER_THREE_HEARING_BUNDLES_COLLECTION("intv3HearingBundles"),
    INTERVENER_THREE_OTHER_COLLECTION("intv3Other"),
    INTERVENER_THREE_QUESTIONNAIRES_ANSWERS_COLLECTION("intv3Qa"),
    INTERVENER_THREE_STATEMENTS_EXHIBITS_COLLECTION("intv3StmtsExhibits"),

    //INTERVENER-FOUR
    INTERVENER_FOUR_SUMMARIES_COLLECTION("intv4Summaries"),
    INTERVENER_FOUR_CHRONOLOGIES_STATEMENTS_COLLECTION("intv4Chronologies"),
    INTERVENER_FOUR_CORRESPONDENCE_COLLECTION("intv4CorrespDocs"),
    INTERVENER_FOUR_EXPERT_EVIDENCE_COLLECTION("intv4ExpertEvidence"),
    INTERVENER_FOUR_FORM_E_EXHIBITS_COLLECTION("intv4FormEsExhibits"),
    INTERVENER_FOUR_FORM_H_COLLECTION("intv4FormHs"),
    INTERVENER_FOUR_HEARING_BUNDLES_COLLECTION("intv4HearingBundles"),
    INTERVENER_FOUR_OTHER_COLLECTION("intv4Other"),
    INTERVENER_FOUR_QUESTIONNAIRES_ANSWERS_COLLECTION("intv4Qa"),
    INTERVENER_FOUR_STATEMENTS_EXHIBITS_COLLECTION("intv4StmtsExhibits");

    private final String ccdKey;

    public String getCcdKey() {
        return ccdKey;
    }
}