package uk.gov.hmcts.reform.finrem.caseorchestration.model.document;

public enum ManageCaseDocumentsCollectionType {

    APPLICANT_FR_FORM_COLLECTION,
    APPLICANT_EVIDENCE_COLLECTION,
    APPLICANT_TRIAL_BUNDLE_COLLECTION,
    APPLICANT_CONFIDENTIAL_DOCS_COLLECTION,
    RESPONDENT_FR_FORM_COLLECTION,
    RESPONDENT_EVIDENCE_COLLECTION,
    RESPONDENT_TRIAL_BUNDLE_COLLECTION,
    RESPONDENT_CONFIDENTIAL_DOCS_COLLECTION,
    APP_HEARING_BUNDLES_COLLECTION,
    APP_FORM_E_EXHIBITS_COLLECTION,
    APP_CHRONOLOGIES_STATEMENTS_COLLECTION,
    APP_QUESTIONNAIRES_ANSWERS_COLLECTION,
    APP_STATEMENTS_EXHIBITS_COLLECTION,
    APP_CASE_SUMMARIES_COLLECTION,
    APP_FORMS_H_COLLECTION,
    APP_EXPERT_EVIDENCE_COLLECTION,
    APP_CORRESPONDENCE_COLLECTION,
    APP_OTHER_COLLECTION,
    RESP_HEARING_BUNDLES_COLLECTION,
    RESP_FORM_E_EXHIBITS_COLLECTION,
    RESP_CHRONOLOGIES_STATEMENTS_COLLECTION,
    RESP_QUESTIONNAIRES_ANSWERS_COLLECTION,
    RESP_STATEMENTS_EXHIBITS_COLLECTION,
    RESP_CASE_SUMMARIES_COLLECTION,
    RESP_FORM_H_COLLECTION,
    RESP_EXPERT_EVIDENCE_COLLECTION,
    RESP_CORRESPONDENCE_COLLECTION,
    RESP_OTHER_COLLECTION,
    CONTESTED_UPLOADED_DOCUMENTS,
    CONTESTED_FDR_CASE_DOCUMENT_COLLECTION;

}