vault_section = "preprod"
idam_api_url = "https://idam-api.demo.platform.hmcts.net"
idam_s2s-auth_url = "http://rpe-service-auth-provider-demo.service.core-compute-demo.internal"
finrem_ns_url = "http://finrem-ns-demo.service.core-compute-demo.internal"
document_generator_baseurl = "http://finrem-dgcs-demo.service.core-compute-demo.internal"
payment_api_url = "http://finrem-ps-demo.service.core-compute-demo.internal"
fees_api_url = "http://fees-register-api-demo.service.core-compute-demo.internal"