vault_section = "preprod"
finrem_ns_url = "http://finrem-ns-demo.service.core-compute-demo.internal"
document_generator_baseurl = "http://finrem-dgcs-demo.service.core-compute-demo.internal"
payment_api_url = "http://finrem-ps-demo.service.core-compute-demo.internal"
fees_api_url = "http://fees-register-api-demo.service.core-compute-demo.internal"