vault_section = "preprod"
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
fees_api_url = "http://fees-register-api-demo.service.core-compute-demo.internal"
payment_api_url = "https://payment-api-demo.service.core-compute-demo.internal"
prd_api_url = "http://rpa-rd-professional-demo.service.core-compute-demo.internal"