vault_section = "preprod"
finrem_ns_url = "http://finrem-ns-aat.service.core-compute-aat.internal"
document_generator_baseurl = "http://finrem-dgcs-aat.service.core-compute-aat.internal"
payment_api_url = "http://finrem-ps-aat.service.core-compute-aat.internal"
fees_api_url = "http://fees-register-api-aat.service.core-compute-aat.internal"
ccd_core_case_data_api_url = "http://ccd-data-store-api-aat.service.core-compute-aat.internal"