vault_section = "test"
finrem_ns_url = "http://finrem-ns-saat.service.core-compute-saat.internal"
document_generator_baseurl = "http://finrem-dgcs-saat.service.core-compute-saat.internal"
payment_api_url = "http://finrem-ps-saat.service.core-compute-saat.internal"
fees_api_url = "http://fees-register-api-saat.service.core-compute-saat.internal"
ccd_core_case_data_api_url = "http://ccd-data-store-api-saat.service.core-compute-saat.internal"