package uk.gov.hmcts.reform.finrem.caseorchestration.ccd;

import uk.gov.hmcts.ccd.sdk.api.CCD;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
public enum CcdState {
    @CCD(
            label = "Application Drafted",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    caseAdded,

    @CCD(
            label = "Awaiting HWF Decision",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    awaitingHWFDecision,

    @CCD(
            label = "Awaiting Payment Response",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    awaitingPaymentResponse,

    @CCD(
            label = "Application Submitted",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    applicationSubmitted,

    @CCD(
            label = "Application Issued",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    applicationIssued,

    @CCD(
            label = "Gate Keeping And Allocation",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    gateKeepingAndAllocation,

    @CCD(
            label = "Scheduling And Hearing",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    schedulingAndHearing,

    @CCD(
            label = "Prepare For Hearing",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    prepareForHearing,

    @CCD(
            label = "Ready for Hearing",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    caseFileSubmitted,

    @CCD(
            label = "Close",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    close,

    @CCD(
            label = "Case Worker Review",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    caseWorkerReview,

    @CCD(
            label = "Judge Draft Order",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    judgeDraftOrder,

    @CCD(
            label = "Solicitor Draft Order",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    solicitorDraftOrder,

    @CCD(
            label = "Review Order",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    reviewOrder,

    @CCD(
            label = "Draft Order Not Approved",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    draftOrderNotApproved,

    @CCD(
            label = "Schedule & Raise Directions Order",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    scheduleRaiseDirectionsOrder,

    @CCD(
            label = "Order Drawn",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    orderDrawn,

    @CCD(
            label = "Order Sent",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    orderSent,

    @CCD(
            label = "Consented Order Submitted",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    consentedOrderSubmitted,

    @CCD(
            label = "Awaiting Judiciary Response (Consent)",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    awaitingJudiciaryResponseConsent,

    @CCD(
            label = "Consent Assigned to Judge",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    consentedOrderAssignJudge,

    @CCD(
            label = "Consented Order Approved",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    consentedOrderApproved,

    @CCD(
            label = "Response Received",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    responseReceived,

    @CCD(
            label = "Consented Order Not Approved",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    consentedOrderNotApproved,

    @CCD(
            label = "General Application",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    generalApplication,

    @CCD(
            label = "Awaiting Judiciary Response (Application)",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    generalApplicationAwaitingJudiciaryResponse,

    @CCD(
            label = "General Application Outcome",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    generalApplicationOutcome,

    @CCD(
            label = "Application Drafted",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    paperCaseAdded,

    @CCD(
            label = "Case Hidden",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    caseHidden,

    @CCD(
            label = "[NOT IN USE] Consent Process",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    consentProcess,

    @CCD(
            label = "[NOT IN USE] Awaiting Judiciary Response",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    awaitingJudiciaryResponse,

    @CCD(
            label = "[NOT IN USE] Consent Order Approved",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    consentOrderApproved,

    @CCD(
            label = "[NOT IN USE] Consent Order Not Approved",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    consentOrderNotApproved,

    @CCD(
            label = "[NOT IN USE] Consent Order Made",
            hint = "**${[CASE_REFERENCE]}  ${applicantLName}  vs ${respondentLName}<br>Financial Remedy - Contested**"
    )
    consentOrderMade
}
