package uk.gov.hmcts.reform.finrem.caseorchestration.ccd;

import java.util.Set;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>AuthorisationComplexType grants for {@code FinancialRemedyContested} (part 2).
 */
public final class FinancialRemedyContestedComplexTypeGrants02 {
    private FinancialRemedyContestedComplexTypeGrants02() {
    }

    /**
     * @param builder the config builder
     */
    static void apply(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerRepresented", Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerRepresented", Set.of(Permission.R), UserRole.INTVRSOLICITOR1);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerRepresented", Set.of(Permission.R), UserRole.INTVRSOLICITOR2);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerRepresented", Set.of(Permission.R), UserRole.INTVRSOLICITOR3);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerRepresented", Set.of(Permission.R), UserRole.INTVRSOLICITOR4);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerName", Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerName", Set.of(Permission.R), UserRole.INTVRSOLICITOR1);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerName", Set.of(Permission.R), UserRole.INTVRSOLICITOR2);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerName", Set.of(Permission.R), UserRole.INTVRSOLICITOR3);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerName", Set.of(Permission.R), UserRole.INTVRSOLICITOR4);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolName", Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolName", Set.of(Permission.R), UserRole.INTVRSOLICITOR1);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolName", Set.of(Permission.R), UserRole.INTVRSOLICITOR2);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolName", Set.of(Permission.R), UserRole.INTVRSOLICITOR3);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolName", Set.of(Permission.R), UserRole.INTVRSOLICITOR4);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolEmail", Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolEmail", Set.of(Permission.R), UserRole.INTVRSOLICITOR1);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolEmail", Set.of(Permission.R), UserRole.INTVRSOLICITOR2);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolEmail", Set.of(Permission.R), UserRole.INTVRSOLICITOR3);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolEmail", Set.of(Permission.R), UserRole.INTVRSOLICITOR4);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolPhone", Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolPhone", Set.of(Permission.R), UserRole.INTVRSOLICITOR1);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolPhone", Set.of(Permission.R), UserRole.INTVRSOLICITOR2);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolPhone", Set.of(Permission.R), UserRole.INTVRSOLICITOR3);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolPhone", Set.of(Permission.R), UserRole.INTVRSOLICITOR4);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolicitorFirm", Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolicitorFirm", Set.of(Permission.R), UserRole.INTVRSOLICITOR1);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolicitorFirm", Set.of(Permission.R), UserRole.INTVRSOLICITOR2);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolicitorFirm", Set.of(Permission.R), UserRole.INTVRSOLICITOR3);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolicitorFirm", Set.of(Permission.R), UserRole.INTVRSOLICITOR4);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolicitorReference", Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolicitorReference", Set.of(Permission.R), UserRole.INTVRSOLICITOR1);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolicitorReference", Set.of(Permission.R), UserRole.INTVRSOLICITOR2);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolicitorReference", Set.of(Permission.R), UserRole.INTVRSOLICITOR3);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerSolicitorReference", Set.of(Permission.R), UserRole.INTVRSOLICITOR4);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerOrganisation", Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_SOLICITOR);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerOrganisation", Set.of(Permission.R), UserRole.INTVRSOLICITOR1);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerOrganisation", Set.of(Permission.R), UserRole.INTVRSOLICITOR2);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerOrganisation", Set.of(Permission.R), UserRole.INTVRSOLICITOR3);
        builder.grantComplexType(FinremCaseData::getIntervenerFour, "intervenerOrganisation", Set.of(Permission.R), UserRole.INTVRSOLICITOR4);
        builder.grantComplexType(FinremCaseData::getOrdersToSend, "value.documentId", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
        builder.grantComplexType(FinremCaseData::getOrdersToSend, "value.documentName", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
        builder.grantComplexType(FinremCaseData::getOrdersToSend, "value.documentToShare", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
        builder.grantComplexType(FinremCaseData::getOrdersToSend, "value.hasSupportingDocuments", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
        builder.grantComplexType(FinremCaseData::getOrdersToSend, "value.includeSupportingDocument", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
        builder.grantComplexType(FinremCaseData::getOrdersToSend, "value.attachmentsToShare", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
        builder.grantComplexType(FinremCaseData::getOrdersToSend, "value.attachmentsToShare.documentId", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
        builder.grantComplexType(FinremCaseData::getOrdersToSend, "value.attachmentsToShare.attachment", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
        builder.grantComplexType(FinremCaseData::getOrdersToSend, "value.attachmentsToShare.documentToShare", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
        builder.grantComplexType(FinremCaseData::getOrdersToSend, "value.coverLetterToShare", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
        builder.grantComplexType(FinremCaseData::getOrdersToSend, "value.coverLetterToShare.documentId", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
        builder.grantComplexType(FinremCaseData::getOrdersToSend, "value.coverLetterToShare.coverLetterName", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
        builder.grantComplexType(FinremCaseData::getOrdersToSend, "value.coverLetterToShare.coverLetterDocument", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
        builder.grantComplexType(FinremCaseData::getOrdersToSend, "value", Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
        builder.grantComplexType(FinremCaseData::getHearingDocumentsCollection, "hearingId", Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
        builder.grantComplexType(FinremCaseData::getHearingDocumentsCollection, "hearingDocument", Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
        builder.grantComplexType(FinremCaseData::getHearingDocumentsCollection, "hearingCaseDocumentType", Set.of(Permission.R), UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN);
    }
}
