package uk.gov.hmcts.reform.finrem.caseorchestration.ccd;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>The search input/result, search-cases, criteria and parties for {@code FinancialRemedyContested}.
 */
@Component
public class FinancialRemedyContestedSearch implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * Configures the search input/result, search-cases, criteria and parties for {@code FinancialRemedyContested}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        builder.searchInputFields()
            .field("divorceCaseNumber", "Divorce Case Number")
            .field("applicantFMName", "Applicant First Name")
            .field("applicantLName", "Applicant Surname")
            .field("respondentFMName", "Respondent First Name")
            .field("respondentLName", "Respondent Surname")
            .field("solicitorReference", "Solicitor Reference")
            .field("evidenceHandled", "Supplementary evidence handled")
            .field("[CASE_REFERENCE]", "CCD Case Number")
            .field("typeOfApplication", "Schedule 1 Application");
        builder.searchResultFields()
            .field("[CASE_REFERENCE]", "Case Reference")
            .field("solicitorReference", "Solicitor Reference")
            .field("applicantLName", "Applicant Name")
            .field("respondentLName", "Respondent Name")
            .field("evidenceHandled", "Supplementary evidence handled")
            .field("[LAST_MODIFIED_DATE]", "Date of Last Event")
            .field("[LAST_STATE_MODIFIED_DATE]", "Last state modified date")
            .field("[STATE]", "Status")
            .field("typeOfApplication", "Application Type");
        builder.searchCasesFields()
            .field("[CASE_REFERENCE]", "Case Reference", f -> f.useCase("orgcases").resultsOrdering("1:ASC"))
            .field("RespondentOrganisationPolicy", "Solicitor Reference", f -> f.useCase("orgcases").listElementCode("OrgPolicyReference"))
            .field("divorceCaseNumber", "Case Number", f -> f.useCase("orgcases"))
            .field("applicantLName", "Applicant Last Name", f -> f.useCase("orgcases"))
            .field("respondentLName", "Respondent Last Name", f -> f.useCase("orgcases"))
            .field("[LAST_MODIFIED_DATE]", "Last Modified Date", f -> f.useCase("orgcases"))
            .field("[STATE]", "State", f -> f.useCase("orgcases"));
    }
}
