package uk.gov.hmcts.reform.finrem.caseorchestration.ccd;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.SortOrder;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>The work-basket input and result fields for {@code FinancialRemedyContested}.
 */
@Component
public class FinancialRemedyContestedWorkBasket implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * Configures the work-basket input and result fields for {@code FinancialRemedyContested}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        builder.workBasketInputFields()
            .field("solicitorReference", "Solicitor Reference")
            .field("evidenceHandled", "Supplementary evidence handled")
            .field("assignedToJudge", "Judge Name")
            .field("regionList", "Region")
            .field("midlandsFRCList", "Midlands FRC's", f -> f.showCondition("regionList=\"midlands\""))
            .field("londonFRCList", "London FRC's", f -> f.showCondition("regionList=\"london\""))
            .field("northWestFRCList", "NorthWest FRC's", f -> f.showCondition("regionList=\"northwest\""))
            .field("northEastFRCList", "North East FRC's", f -> f.showCondition("regionList=\"northeast\""))
            .field("southEastFRCList", "South East FRC's", f -> f.showCondition("regionList=\"southeast\""))
            .field("southWestFRCList", "South West FRC's", f -> f.showCondition("regionList=\"southwest\""))
            .field("walesFRCList", "Wales FRC's", f -> f.showCondition("regionList=\"wales\""))
            .field("highCourtFRCList", "High Court Family Division FRC's", f -> f.showCondition("regionList=\"highcourt\""))
            .field("nottinghamCourtList", "Nottingham Court List", f -> f.showCondition("regionList=\"midlands\" AND midlandsFRCList=\"nottingham\""))
            .field("cfcCourtList", "London Court List", f -> f.showCondition("regionList=\"london\" AND londonFRCList=\"cfc\""))
            .field("birminghamCourtList", "Birmingham Court List", f -> f.showCondition("regionList=\"midlands\" AND midlandsFRCList=\"birmingham\""))
            .field("liverpoolCourtList", "Liverpool Court List", f -> f.showCondition("regionList=\"northwest\" AND northWestFRCList=\"liverpool\""))
            .field("manchesterCourtList", "Manchester Court List", f -> f.showCondition("regionList=\"northwest\" AND northWestFRCList=\"manchester\""))
            .field("lancashireCourtList", "Lancashire Court List", f -> f.showCondition("regionList=\"northwest\" AND northWestFRCList=\"lancashire\""))
            .field("cleavelandCourtList", "Cleveland Court List", f -> f.showCondition("regionList=\"northeast\" AND northEastFRCList=\"cleaveland\""))
            .field("nwyorkshireCourtList", "N&W Yorkshire Court List", f -> f.showCondition("regionList=\"northeast\" AND northEastFRCList=\"nwyorkshire\""))
            .field("humberCourtList", "Humber & S Yorkshire Courts", f -> f.showCondition("regionList=\"northeast\" AND northEastFRCList=\"hsyorkshire\""))
            .field("kentSurreyCourtList", "Kent, Surrey & Sussex Courts", f -> f.showCondition("regionList=\"southeast\" AND southEastFRCList=\"kentfrc\""))
            .field("bedfordshireCourtList", "Bedfordshire Court List", f -> f.showCondition("regionList=\"southeast\" AND southEastFRCList=\"bedfordshire\""))
            .field("thamesvalleyCourtList", "Thames Valley Court List", f -> f.showCondition("regionList=\"southeast\" AND southEastFRCList=\"thamesvalley\""))
            .field("devonCourtList", "Devon Court List", f -> f.showCondition("regionList=\"southwest\" AND southWestFRCList=\"devon\""))
            .field("dorsetCourtList", "Dorset Court List", f -> f.showCondition("regionList=\"southwest\" AND southWestFRCList=\"dorset\""))
            .field("bristolCourtList", "Bristol Court List", f -> f.showCondition("regionList=\"southwest\" AND southWestFRCList=\"bristol\""))
            .field("newportCourtList", "Newport Court List", f -> f.showCondition("regionList=\"wales\" AND walesFRCList=\"newport\""))
            .field("swanseaCourtList", "Swansea Court List", f -> f.showCondition("regionList=\"wales\" AND walesFRCList=\"swansea\""))
            .field("northWalesCourtList", "North Wales Court List", f -> f.showCondition("regionList=\"wales\" AND walesFRCList=\"northwales\""))
            .field("promptForUrgentCaseQuestion", "Urgent Case")
            .field("typeOfApplication", "Schedule 1 Application");
        builder.workBasketResultFields()
            .field("[CASE_REFERENCE]", "Case Reference")
            .field("solicitorReference", "Solicitor Reference")
            .field("applicantLName", "Applicant Name")
            .field("respondentLName", "Respondent Name")
            .field("evidenceHandled", "Supplementary evidence handled")
            .field("[LAST_MODIFIED_DATE]", "Date of Last Event")
            .field("[LAST_STATE_MODIFIED_DATE]", "Last state modified date", f -> f.resultsOrdering(SortOrder.FIRST.ASCENDING))
            .field("[STATE]", "Status")
            .field("assignedToJudge", "Judge Name")
            .field("typeOfApplication", "Application Type");
    }
}
