package uk.gov.hmcts.reform.finrem.caseorchestration.ccd;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>The document categories for {@code FinancialRemedyContested}.
 */
@Component
public class FinancialRemedyContestedCategories implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * Configures the document categories for {@code FinancialRemedyContested}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsApplicantRepliesToQuestionnaire")
            .categoryLabel("Replies To Questionnaire")
            .displayOrder(220)
            .parentCategoryID("hearingDocumentsApplicant");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsRespondentRepliesToQuestionnaire")
            .categoryLabel("Replies To Questionnaire")
            .displayOrder(221)
            .parentCategoryID("hearingDocumentsRespondent");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicantMortgageCapacitiesOrMarketAppraisal")
            .categoryLabel("Mortgage Capacities/Market Appraisal")
            .displayOrder(222)
            .parentCategoryID("applicantDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("respondentMortgageCapacitiesOrMarketAppraisal")
            .categoryLabel("Mortgage Capacities/Market Appraisal")
            .displayOrder(223)
            .parentCategoryID("respondentDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applications")
            .categoryLabel("Applications")
            .displayOrder(1);
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicationsMainApplication")
            .categoryLabel("Main Application")
            .displayOrder(2)
            .parentCategoryID("applications");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicationsVariationOrder")
            .categoryLabel("Variation Application")
            .displayOrder(3)
            .parentCategoryID("applicationsMainApplication");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicationsOtherApplication")
            .categoryLabel("Other Application")
            .displayOrder(4)
            .parentCategoryID("applications");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicationsConsentOrderToFinaliseProceedings")
            .categoryLabel("Consent Order To Finalise Proceedings")
            .displayOrder(5)
            .parentCategoryID("applications");
        builder.categories(UserRole.APPLICANT)
            .categoryID("postHearingDraftOrder")
            .categoryLabel("Post Hearing Draft Orders")
            .displayOrder(6);
        builder.categories(UserRole.APPLICANT)
            .categoryID("approvedOrders")
            .categoryLabel("Approved Orders")
            .displayOrder(7);
        builder.categories(UserRole.APPLICANT)
            .categoryID("approvedOrdersConsentOrderToFinaliseProceedings")
            .categoryLabel("Consent Order To Finalise Proceedings")
            .displayOrder(8)
            .parentCategoryID("approvedOrders");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicantDocuments")
            .categoryLabel("Applicant Documents")
            .displayOrder(9);
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicantDocumentsFormE")
            .categoryLabel("Form E")
            .displayOrder(10)
            .parentCategoryID("applicantDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicantDocumentsFormG")
            .categoryLabel("Form G")
            .displayOrder(11)
            .parentCategoryID("applicantDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicantMortgageCapacitiesOrHousingParticulars")
            .categoryLabel("Mortgage Capacities/Housing Particulars")
            .displayOrder(12)
            .parentCategoryID("applicantDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicantDocumentsRepliesToQuestionnaire")
            .categoryLabel("Replies To Questionnaire")
            .displayOrder(13)
            .parentCategoryID("applicantDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicantDocumentsOpenOffers")
            .categoryLabel("Open Offers")
            .displayOrder(14)
            .parentCategoryID("applicantDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicantDocumentsS25Statement")
            .categoryLabel("S25 Statement")
            .displayOrder(15)
            .parentCategoryID("applicantDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicantDocumentsWitnessStatements")
            .categoryLabel("Witness Statements")
            .displayOrder(16)
            .parentCategoryID("applicantDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicantDocumentsPointOfClaimOrDefence")
            .categoryLabel("Points of claim/defence")
            .displayOrder(17)
            .parentCategoryID("applicantDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicantDocumentsCertificatesOfService")
            .categoryLabel("Certificates Of Service")
            .displayOrder(18)
            .parentCategoryID("applicantDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicantDocumentsMiscellaneousOrOther")
            .categoryLabel("Miscellaneous/Other")
            .displayOrder(19)
            .parentCategoryID("applicantDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicantDocumentsSupportingDocuments")
            .categoryLabel("Supporting Documents")
            .displayOrder(20)
            .parentCategoryID("applicantDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("respondentDocuments")
            .categoryLabel("Respondent Documents")
            .displayOrder(21);
        builder.categories(UserRole.APPLICANT)
            .categoryID("respondentDocumentsFormE")
            .categoryLabel("Form E")
            .displayOrder(22)
            .parentCategoryID("respondentDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("respondentDocumentsFormG")
            .categoryLabel("Form G")
            .displayOrder(23)
            .parentCategoryID("respondentDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("respondentMortgageCapacitiesOrHousingParticulars")
            .categoryLabel("Mortgage Capacities/Housing Particulars")
            .displayOrder(24)
            .parentCategoryID("respondentDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("respondentDocumentsRepliesToQuestionnaire")
            .categoryLabel("Replies To Questionnaire")
            .displayOrder(25)
            .parentCategoryID("respondentDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("respondentDocumentsOpenOffers")
            .categoryLabel("Open Offers")
            .displayOrder(26)
            .parentCategoryID("respondentDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("respondentDocumentsS25Statement")
            .categoryLabel("S25 Statement")
            .displayOrder(27)
            .parentCategoryID("respondentDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("respondentDocumentsWitnessStatements")
            .categoryLabel("Witness Statements")
            .displayOrder(28)
            .parentCategoryID("respondentDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("respondentDocumentsPointOfClaimOrDefence")
            .categoryLabel("Points of claim/defence")
            .displayOrder(29)
            .parentCategoryID("respondentDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("respondentDocumentsCertificatesOfService")
            .categoryLabel("Certificates Of Service")
            .displayOrder(30)
            .parentCategoryID("respondentDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("respondentDocumentsMiscellaneousOrOther")
            .categoryLabel("Miscellaneous/Other")
            .displayOrder(31)
            .parentCategoryID("respondentDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("respondentDocumentsSupportingDocuments")
            .categoryLabel("Supporting Documents")
            .displayOrder(32)
            .parentCategoryID("respondentDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("lipOrScannedDocuments")
            .categoryLabel("LiP/Scanned Documents")
            .displayOrder(33);
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundle")
            .categoryLabel("FDR Documents And FDR Bundle")
            .displayOrder(34);
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrBundle")
            .categoryLabel("FDR Bundle")
            .displayOrder(35)
            .parentCategoryID("fdrDocumentsAndFdrBundle");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsJointDocuments")
            .categoryLabel("Joint documents")
            .displayOrder(36)
            .parentCategoryID("fdrDocumentsAndFdrBundle");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsJointDocumentsEs1")
            .categoryLabel("ES1")
            .displayOrder(37)
            .parentCategoryID("fdrDocumentsJointDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsJointDocumentsEs2")
            .categoryLabel("ES2")
            .displayOrder(38)
            .parentCategoryID("fdrDocumentsJointDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsJointDocumentsChronology")
            .categoryLabel("Chronology")
            .displayOrder(39)
            .parentCategoryID("fdrDocumentsJointDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleApplicant")
            .categoryLabel("Applicant")
            .displayOrder(40)
            .parentCategoryID("fdrDocumentsAndFdrBundle");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleApplicantPositionStatements")
            .categoryLabel("Position Statements / Skeleton Arguments")
            .displayOrder(41)
            .parentCategoryID("fdrDocumentsAndFdrBundleApplicant");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleApplicantWithoutPrejudiceOffers")
            .categoryLabel("Without Prejudice Offers")
            .displayOrder(42)
            .parentCategoryID("fdrDocumentsAndFdrBundleApplicant");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleApplicantDraftOrder")
            .categoryLabel("Draft Order")
            .displayOrder(43)
            .parentCategoryID("fdrDocumentsAndFdrBundleApplicant");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleApplicantPointsOfClaimOrDefence")
            .categoryLabel("Points of claim/defence")
            .displayOrder(44)
            .parentCategoryID("fdrDocumentsAndFdrBundleApplicant");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleApplicantOther")
            .categoryLabel("Other")
            .displayOrder(45)
            .parentCategoryID("fdrDocumentsAndFdrBundleApplicant");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleRespondent")
            .categoryLabel("Respondent")
            .displayOrder(46)
            .parentCategoryID("fdrDocumentsAndFdrBundle");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleRespondentPositionStatements")
            .categoryLabel("Position Statements / Skeleton Arguments")
            .displayOrder(47)
            .parentCategoryID("fdrDocumentsAndFdrBundleRespondent");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleRespondentWithoutPrejudiceOffers")
            .categoryLabel("Without Prejudice Offers")
            .displayOrder(48)
            .parentCategoryID("fdrDocumentsAndFdrBundleRespondent");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleRespondentDraftOrder")
            .categoryLabel("Draft Order")
            .displayOrder(49)
            .parentCategoryID("fdrDocumentsAndFdrBundleRespondent");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleRespondentPointsOfClaimOrDefence")
            .categoryLabel("Points of claim/defence")
            .displayOrder(50)
            .parentCategoryID("fdrDocumentsAndFdrBundleRespondent");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleRespondentOther")
            .categoryLabel("Other")
            .displayOrder(51)
            .parentCategoryID("fdrDocumentsAndFdrBundleRespondent");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener1")
            .categoryLabel("Intervener 1")
            .displayOrder(52)
            .parentCategoryID("fdrDocumentsAndFdrBundle");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener1PositionStatements")
            .categoryLabel("Position Statements / Skeleton Arguments")
            .displayOrder(53)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener1CostsStatement")
            .categoryLabel("Costs Statement")
            .displayOrder(54)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener1DraftOrder")
            .categoryLabel("Draft Order")
            .displayOrder(55)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener1PointsOfClaimOrDefence")
            .categoryLabel("Points of claim/defence")
            .displayOrder(56)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener1Other")
            .categoryLabel("Other")
            .displayOrder(57)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener2")
            .categoryLabel("Intervener 2")
            .displayOrder(58)
            .parentCategoryID("fdrDocumentsAndFdrBundle");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener2PositionStatements")
            .categoryLabel("Position Statements / Skeleton Arguments")
            .displayOrder(59)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener2CostsStatement")
            .categoryLabel("Costs Statement")
            .displayOrder(60)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener2DraftOrder")
            .categoryLabel("Draft Order")
            .displayOrder(61)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener2PointsOfClaimOrDefence")
            .categoryLabel("Points of claim/defence")
            .displayOrder(62)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener2Other")
            .categoryLabel("Other")
            .displayOrder(63)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener3")
            .categoryLabel("Intervener 3")
            .displayOrder(64)
            .parentCategoryID("fdrDocumentsAndFdrBundle");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener3PositionStatements")
            .categoryLabel("Position Statements / Skeleton Arguments")
            .displayOrder(65)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener3CostsStatement")
            .categoryLabel("Costs Statement")
            .displayOrder(66)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener3DraftOrder")
            .categoryLabel("Draft Order")
            .displayOrder(67)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener3PointsOfClaimOrDefence")
            .categoryLabel("Points of claim/defence")
            .displayOrder(68)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener3Other")
            .categoryLabel("Other")
            .displayOrder(69)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener4")
            .categoryLabel("Intervener 4")
            .displayOrder(70)
            .parentCategoryID("fdrDocumentsAndFdrBundle");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener4PositionStatements")
            .categoryLabel("Position Statements / Skeleton Arguments")
            .displayOrder(71)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener4CostsStatement")
            .categoryLabel("Costs Statement")
            .displayOrder(72)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener4DraftOrder")
            .categoryLabel("Draft Order")
            .displayOrder(73)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener4PointsOfClaimOrDefence")
            .categoryLabel("Points of claim/defence")
            .displayOrder(74)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsAndFdrBundleIntervener4Other")
            .categoryLabel("Other")
            .displayOrder(75)
            .parentCategoryID("fdrDocumentsAndFdrBundleIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("fdrDocumentsReports")
            .categoryLabel("Reports")
            .displayOrder(76)
            .parentCategoryID("fdrDocumentsAndFdrBundle");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocuments")
            .categoryLabel("Hearing Documents")
            .displayOrder(77);
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsApplicant")
            .categoryLabel("Applicant")
            .displayOrder(78)
            .parentCategoryID("hearingDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsApplicantCaseSummary")
            .categoryLabel("Case Summary")
            .displayOrder(79)
            .parentCategoryID("hearingDocumentsApplicant");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsApplicantPositionStatement")
            .categoryLabel("Position Statement")
            .displayOrder(80)
            .parentCategoryID("hearingDocumentsApplicant");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsApplicantConciseStatementOfIssues")
            .categoryLabel("Concise Statement Of Issues")
            .displayOrder(81)
            .parentCategoryID("hearingDocumentsApplicant");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsApplicantEs1")
            .categoryLabel("ES1")
            .displayOrder(82)
            .parentCategoryID("hearingDocumentsApplicant");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsApplicantEs2")
            .categoryLabel("ES2")
            .displayOrder(83)
            .parentCategoryID("hearingDocumentsApplicant");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsApplicantFm5")
            .categoryLabel("FM5")
            .displayOrder(84)
            .parentCategoryID("hearingDocumentsApplicant");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsApplicantChronology")
            .categoryLabel("Chronology")
            .displayOrder(85)
            .parentCategoryID("hearingDocumentsApplicant");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsApplicantQuestionnaires")
            .categoryLabel("Questionnaires")
            .displayOrder(86)
            .parentCategoryID("hearingDocumentsApplicant");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsApplicantCostsFormH/H1/N260")
            .categoryLabel("Costs Form H/H1/N260")
            .displayOrder(87)
            .parentCategoryID("hearingDocumentsApplicant");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsApplicantPreHearingDraftOrder")
            .categoryLabel("Pre Hearing Draft Order")
            .displayOrder(88)
            .parentCategoryID("hearingDocumentsApplicant");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsRespondent")
            .categoryLabel("Respondent")
            .displayOrder(89)
            .parentCategoryID("hearingDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsRespondentCaseSummary")
            .categoryLabel("Case Summary")
            .displayOrder(90)
            .parentCategoryID("hearingDocumentsRespondent");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsRespondentPositionStatement")
            .categoryLabel("Position Statement")
            .displayOrder(91)
            .parentCategoryID("hearingDocumentsRespondent");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsRespondentConciseStatementOfIssues")
            .categoryLabel("Concise Statement Of Issues")
            .displayOrder(92)
            .parentCategoryID("hearingDocumentsRespondent");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsRespondentEs1")
            .categoryLabel("ES1")
            .displayOrder(93)
            .parentCategoryID("hearingDocumentsRespondent");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsRespondentEs2")
            .categoryLabel("ES2")
            .displayOrder(94)
            .parentCategoryID("hearingDocumentsRespondent");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsRespondentFm5")
            .categoryLabel("FM5")
            .displayOrder(95)
            .parentCategoryID("hearingDocumentsRespondent");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsRespondentChronology")
            .categoryLabel("Chronology")
            .displayOrder(96)
            .parentCategoryID("hearingDocumentsRespondent");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsRespondentQuestionnaires")
            .categoryLabel("Questionnaires")
            .displayOrder(97)
            .parentCategoryID("hearingDocumentsRespondent");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsRespondentCostsFormH/H1/N260")
            .categoryLabel("Costs Form H/H1/N260")
            .displayOrder(98)
            .parentCategoryID("hearingDocumentsRespondent");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsRespondentPreHearingDraftOrder")
            .categoryLabel("Pre Hearing Draft Order")
            .displayOrder(99)
            .parentCategoryID("hearingDocumentsRespondent");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener1")
            .categoryLabel("Intervener 1")
            .displayOrder(100)
            .parentCategoryID("hearingDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener1CaseSummary")
            .categoryLabel("Case Summary")
            .displayOrder(101)
            .parentCategoryID("hearingDocumentsIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener1PositionStatement")
            .categoryLabel("Position Statement")
            .displayOrder(102)
            .parentCategoryID("hearingDocumentsIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener1ConciseStatementOfIssues")
            .categoryLabel("Concise Statement Of Issues")
            .displayOrder(103)
            .parentCategoryID("hearingDocumentsIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener1Es1")
            .categoryLabel("ES1")
            .displayOrder(104)
            .parentCategoryID("hearingDocumentsIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener1Es2")
            .categoryLabel("ES2")
            .displayOrder(105)
            .parentCategoryID("hearingDocumentsIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener1Fm5")
            .categoryLabel("FM5")
            .displayOrder(106)
            .parentCategoryID("hearingDocumentsIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener1Chronology")
            .categoryLabel("Chronology")
            .displayOrder(107)
            .parentCategoryID("hearingDocumentsIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener1Questionnaires")
            .categoryLabel("Questionnaires")
            .displayOrder(108)
            .parentCategoryID("hearingDocumentsIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener1CostsFormH/H1/N260")
            .categoryLabel("Costs Form H/H1/N260")
            .displayOrder(109)
            .parentCategoryID("hearingDocumentsIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener1PreHearingDraftOrder")
            .categoryLabel("Pre Hearing Draft Order")
            .displayOrder(110)
            .parentCategoryID("hearingDocumentsIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener2")
            .categoryLabel("Intervener 2")
            .displayOrder(111)
            .parentCategoryID("hearingDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener2CaseSummary")
            .categoryLabel("Case Summary")
            .displayOrder(112)
            .parentCategoryID("hearingDocumentsIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener2PositionStatement")
            .categoryLabel("Position Statement")
            .displayOrder(113)
            .parentCategoryID("hearingDocumentsIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener2ConciseStatementOfIssues")
            .categoryLabel("Concise Statement Of Issues")
            .displayOrder(114)
            .parentCategoryID("hearingDocumentsIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener2Es1")
            .categoryLabel("ES1")
            .displayOrder(115)
            .parentCategoryID("hearingDocumentsIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener2Es2")
            .categoryLabel("ES2")
            .displayOrder(116)
            .parentCategoryID("hearingDocumentsIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener2Fm5")
            .categoryLabel("FM5")
            .displayOrder(117)
            .parentCategoryID("hearingDocumentsIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener2Chronology")
            .categoryLabel("Chronology")
            .displayOrder(118)
            .parentCategoryID("hearingDocumentsIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener2Questionnaires")
            .categoryLabel("Questionnaires")
            .displayOrder(119)
            .parentCategoryID("hearingDocumentsIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener2CostsFormH/H1/N260")
            .categoryLabel("Costs Form H/H1/N260")
            .displayOrder(120)
            .parentCategoryID("hearingDocumentsIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener2PreHearingDraftOrder")
            .categoryLabel("Pre Hearing Draft Order")
            .displayOrder(121)
            .parentCategoryID("hearingDocumentsIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener3")
            .categoryLabel("Intervener 3")
            .displayOrder(122)
            .parentCategoryID("hearingDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener3CaseSummary")
            .categoryLabel("Case Summary")
            .displayOrder(123)
            .parentCategoryID("hearingDocumentsIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener3PositionStatement")
            .categoryLabel("Position Statement")
            .displayOrder(124)
            .parentCategoryID("hearingDocumentsIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener3ConciseStatementOfIssues")
            .categoryLabel("Concise Statement Of Issues")
            .displayOrder(125)
            .parentCategoryID("hearingDocumentsIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener3Es1")
            .categoryLabel("ES1")
            .displayOrder(126)
            .parentCategoryID("hearingDocumentsIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener3Es2")
            .categoryLabel("ES2")
            .displayOrder(127)
            .parentCategoryID("hearingDocumentsIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener3Fm5")
            .categoryLabel("FM5")
            .displayOrder(128)
            .parentCategoryID("hearingDocumentsIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener3Chronology")
            .categoryLabel("Chronology")
            .displayOrder(129)
            .parentCategoryID("hearingDocumentsIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener3Questionnaires")
            .categoryLabel("Questionnaires")
            .displayOrder(130)
            .parentCategoryID("hearingDocumentsIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener3CostsFormH/H1/N260")
            .categoryLabel("Costs Form H/H1/N260")
            .displayOrder(131)
            .parentCategoryID("hearingDocumentsIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener3PreHearingDraftOrder")
            .categoryLabel("Pre Hearing Draft Order")
            .displayOrder(132)
            .parentCategoryID("hearingDocumentsIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener4")
            .categoryLabel("Intervener 4")
            .displayOrder(133)
            .parentCategoryID("hearingDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener4CaseSummary")
            .categoryLabel("Case Summary")
            .displayOrder(134)
            .parentCategoryID("hearingDocumentsIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener4PositionStatement")
            .categoryLabel("Position Statement")
            .displayOrder(135)
            .parentCategoryID("hearingDocumentsIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener4ConciseStatementOfIssues")
            .categoryLabel("Concise Statement Of Issues")
            .displayOrder(136)
            .parentCategoryID("hearingDocumentsIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener4Es1")
            .categoryLabel("ES1")
            .displayOrder(137)
            .parentCategoryID("hearingDocumentsIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener4Es2")
            .categoryLabel("ES2")
            .displayOrder(138)
            .parentCategoryID("hearingDocumentsIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener4Fm5")
            .categoryLabel("FM5")
            .displayOrder(139)
            .parentCategoryID("hearingDocumentsIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener4Chronology")
            .categoryLabel("Chronology")
            .displayOrder(140)
            .parentCategoryID("hearingDocumentsIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener4Questionnaires")
            .categoryLabel("Questionnaires")
            .displayOrder(141)
            .parentCategoryID("hearingDocumentsIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener4CostsFormH/H1/N260")
            .categoryLabel("Costs Form H/H1/N260")
            .displayOrder(142)
            .parentCategoryID("hearingDocumentsIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsIntervener4PreHearingDraftOrder")
            .categoryLabel("Pre Hearing Draft Order")
            .displayOrder(143)
            .parentCategoryID("hearingDocumentsIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingBundle")
            .categoryLabel("Hearing Bundle")
            .displayOrder(144);
        builder.categories(UserRole.APPLICANT)
            .categoryID("reports")
            .categoryLabel("Expert Reports")
            .displayOrder(145);
        builder.categories(UserRole.APPLICANT)
            .categoryID("courtCorrespondence")
            .categoryLabel("Court Correspondence")
            .displayOrder(146);
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingNotices")
            .categoryLabel("Hearing Notices")
            .displayOrder(147);
        builder.categories(UserRole.APPLICANT)
            .categoryID("confidentialDocuments")
            .categoryLabel("Confidential Documents")
            .displayOrder(148);
        builder.categories(UserRole.APPLICANT)
            .categoryID("confidentialDocumentsApplicant")
            .categoryLabel("Applicant")
            .displayOrder(149)
            .parentCategoryID("confidentialDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("confidentialDocumentsRespondent")
            .categoryLabel("Respondent")
            .displayOrder(150)
            .parentCategoryID("confidentialDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("confidentialDocumentsIntervener1")
            .categoryLabel("Intervener 1")
            .displayOrder(151)
            .parentCategoryID("confidentialDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("confidentialDocumentsIntervener2")
            .categoryLabel("Intervener 2")
            .displayOrder(152)
            .parentCategoryID("confidentialDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("confidentialDocumentsIntervener3")
            .categoryLabel("Intervener 3")
            .displayOrder(153)
            .parentCategoryID("confidentialDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("confidentialDocumentsIntervener4")
            .categoryLabel("Intervener 4")
            .displayOrder(154)
            .parentCategoryID("confidentialDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocuments")
            .categoryLabel("Intervener Documents")
            .displayOrder(155);
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener1")
            .categoryLabel("Intervener 1")
            .displayOrder(156)
            .parentCategoryID("intervenerDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener1OpenOffers")
            .categoryLabel("Open Offers")
            .displayOrder(157)
            .parentCategoryID("intervenerDocumentsIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener1WitnessStatements")
            .categoryLabel("Witness Statements")
            .displayOrder(158)
            .parentCategoryID("intervenerDocumentsIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener1CostsStatement")
            .categoryLabel("Costs Statement")
            .displayOrder(159)
            .parentCategoryID("intervenerDocumentsIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener1PointOfClaimOrDefence")
            .categoryLabel("Points of claim/defence")
            .displayOrder(160)
            .parentCategoryID("intervenerDocumentsIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener1SupportingDocuments")
            .categoryLabel("Supporting Documents")
            .displayOrder(161)
            .parentCategoryID("intervenerDocumentsIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener1Other")
            .categoryLabel("Other")
            .displayOrder(162)
            .parentCategoryID("intervenerDocumentsIntervener1");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener2")
            .categoryLabel("Intervener 2")
            .displayOrder(163)
            .parentCategoryID("intervenerDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener2OpenOffers")
            .categoryLabel("Open Offers")
            .displayOrder(164)
            .parentCategoryID("intervenerDocumentsIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener2WitnessStatements")
            .categoryLabel("Witness Statements")
            .displayOrder(165)
            .parentCategoryID("intervenerDocumentsIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener2CostsStatement")
            .categoryLabel("Costs Statement")
            .displayOrder(166)
            .parentCategoryID("intervenerDocumentsIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener2PointOfClaimOrDefence")
            .categoryLabel("Points of claim/defence")
            .displayOrder(167)
            .parentCategoryID("intervenerDocumentsIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener2Other")
            .categoryLabel("Other")
            .displayOrder(168)
            .parentCategoryID("intervenerDocumentsIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener2SupportingDocuments")
            .categoryLabel("Supporting Documents")
            .displayOrder(169)
            .parentCategoryID("intervenerDocumentsIntervener2");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener3")
            .categoryLabel("Intervener 3")
            .displayOrder(170)
            .parentCategoryID("intervenerDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener3OpenOffers")
            .categoryLabel("Open Offers")
            .displayOrder(171)
            .parentCategoryID("intervenerDocumentsIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener3WitnessStatements")
            .categoryLabel("Witness Statements")
            .displayOrder(172)
            .parentCategoryID("intervenerDocumentsIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener3CostsStatement")
            .categoryLabel("Costs Statement")
            .displayOrder(173)
            .parentCategoryID("intervenerDocumentsIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener3PointOfClaimOrDefence")
            .categoryLabel("Points of claim/defence")
            .displayOrder(174)
            .parentCategoryID("intervenerDocumentsIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener3Other")
            .categoryLabel("Other")
            .displayOrder(175)
            .parentCategoryID("intervenerDocumentsIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener3SupportingDocuments")
            .categoryLabel("Supporting Documents")
            .displayOrder(176)
            .parentCategoryID("intervenerDocumentsIntervener3");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener4")
            .categoryLabel("Intervener 4")
            .displayOrder(177)
            .parentCategoryID("intervenerDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener4OpenOffers")
            .categoryLabel("Open Offers")
            .displayOrder(178)
            .parentCategoryID("intervenerDocumentsIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener4WitnessStatements")
            .categoryLabel("Witness Statements")
            .displayOrder(179)
            .parentCategoryID("intervenerDocumentsIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener4CostsStatement")
            .categoryLabel("Costs Statement")
            .displayOrder(180)
            .parentCategoryID("intervenerDocumentsIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener4PointOfClaimOrDefence")
            .categoryLabel("Points of claim/defence")
            .displayOrder(181)
            .parentCategoryID("intervenerDocumentsIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener4Other")
            .categoryLabel("Other")
            .displayOrder(182)
            .parentCategoryID("intervenerDocumentsIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("intervenerDocumentsIntervener4SupportingDocuments")
            .categoryLabel("Supporting Documents")
            .displayOrder(183)
            .parentCategoryID("intervenerDocumentsIntervener4");
        builder.categories(UserRole.APPLICANT)
            .categoryID("divorceDocuments")
            .categoryLabel("Divorce Documents")
            .displayOrder(184);
        builder.categories(UserRole.APPLICANT)
            .categoryID("divorceDocumentsApplicationOrPetition")
            .categoryLabel("Application/Petition")
            .displayOrder(185)
            .parentCategoryID("divorceDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("divorceDocumentsConditionalOrderOrDecreeNisi")
            .categoryLabel("Conditional Order/Decree Nisi")
            .displayOrder(186)
            .parentCategoryID("divorceDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("divorceDocumentsFinalOrderOrDecreeAbsolute")
            .categoryLabel("Final Order/Decree Absolute")
            .displayOrder(187)
            .parentCategoryID("divorceDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("administrativeDocuments")
            .categoryLabel("Administrative Documents")
            .displayOrder(188);
        builder.categories(UserRole.APPLICANT)
            .categoryID("administrativeDocumentsCoversheets")
            .categoryLabel("Coversheets")
            .displayOrder(189)
            .parentCategoryID("administrativeDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("administrativeDocumentsJudicialNotes")
            .categoryLabel("Judicial Notes")
            .displayOrder(190)
            .parentCategoryID("administrativeDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("administrativeDocumentsAttendanceSheets")
            .categoryLabel("Attendance Sheets")
            .displayOrder(191)
            .parentCategoryID("administrativeDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("administrativeDocumentsOther")
            .categoryLabel("Other")
            .displayOrder(192)
            .parentCategoryID("administrativeDocuments");
        builder.categories(UserRole.APPLICANT)
            .categoryID("administrativeDocumentsTransitional")
            .categoryLabel("Transitional")
            .displayOrder(193)
            .parentCategoryID("systemDuplicates");
        builder.categories(UserRole.APPLICANT)
            .categoryID("judgmentOrTranscript")
            .categoryLabel("Judgment/Transcript")
            .displayOrder(194);
        builder.categories(UserRole.APPLICANT)
            .categoryID("caseDocuments")
            .categoryLabel("Caseworker Uploaded Documents")
            .displayOrder(195);
        builder.categories(UserRole.APPLICANT)
            .categoryID("shared")
            .categoryLabel("Shared")
            .displayOrder(196);
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicationsOtherApplicationsapp1")
            .categoryLabel("Application 1 (Most Recent)")
            .displayOrder(197)
            .parentCategoryID("applicationsOtherApplication");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicationsOtherApplicationsapp2")
            .categoryLabel("Application 2")
            .displayOrder(198)
            .parentCategoryID("applicationsOtherApplication");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicationsOtherApplicationsapp3")
            .categoryLabel("Application 3")
            .displayOrder(199)
            .parentCategoryID("applicationsOtherApplication");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicationsOtherApplicationsapp4")
            .categoryLabel("Application 4")
            .displayOrder(200)
            .parentCategoryID("applicationsOtherApplication");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicationsOtherApplicationsapp5")
            .categoryLabel("Application 5")
            .displayOrder(201)
            .parentCategoryID("applicationsOtherApplication");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicationsOtherApplicationsapp6")
            .categoryLabel("Application 6")
            .displayOrder(202)
            .parentCategoryID("applicationsOtherApplication");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicationsOtherApplicationsapp7")
            .categoryLabel("Application 7")
            .displayOrder(203)
            .parentCategoryID("applicationsOtherApplication");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicationsOtherApplicationsapp8")
            .categoryLabel("Application 8")
            .displayOrder(204)
            .parentCategoryID("applicationsOtherApplication");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicationsOtherApplicationsapp9")
            .categoryLabel("Application 9")
            .displayOrder(205)
            .parentCategoryID("applicationsOtherApplication");
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicationsOtherApplicationsapp10")
            .categoryLabel("Application 10 (Oldest)")
            .displayOrder(206)
            .parentCategoryID("applicationsOtherApplication");
        builder.categories(UserRole.APPLICANT)
            .categoryID("duplicatedGeneralOrders")
            .categoryLabel("Duplicated General Orders")
            .displayOrder(207)
            .parentCategoryID("systemDuplicates");
        builder.categories(UserRole.APPLICANT)
            .categoryID("systemDuplicates")
            .categoryLabel("System Duplicates")
            .displayOrder(208);
        builder.categories(UserRole.APPLICANT)
            .categoryID("applicationsOtherApplicationsOverflow")
            .categoryLabel("Application Overflow")
            .displayOrder(209)
            .parentCategoryID("applicationsOtherApplication");
        builder.categories(UserRole.APPLICANT)
            .categoryID("courtCorrespondenceApplicant")
            .categoryLabel("Applicant")
            .displayOrder(210)
            .parentCategoryID("courtCorrespondence");
        builder.categories(UserRole.APPLICANT)
            .categoryID("courtCorrespondenceRespondent")
            .categoryLabel("Respondent")
            .displayOrder(211)
            .parentCategoryID("courtCorrespondence");
        builder.categories(UserRole.APPLICANT)
            .categoryID("courtCorrespondenceIntervener1")
            .categoryLabel("Intervener 1")
            .displayOrder(212)
            .parentCategoryID("courtCorrespondence");
        builder.categories(UserRole.APPLICANT)
            .categoryID("courtCorrespondenceIntervener2")
            .categoryLabel("Intervener 2")
            .displayOrder(213)
            .parentCategoryID("courtCorrespondence");
        builder.categories(UserRole.APPLICANT)
            .categoryID("courtCorrespondenceIntervener3")
            .categoryLabel("Intervener 3")
            .displayOrder(214)
            .parentCategoryID("courtCorrespondence");
        builder.categories(UserRole.APPLICANT)
            .categoryID("courtCorrespondenceIntervener4")
            .categoryLabel("Intervener 4")
            .displayOrder(215)
            .parentCategoryID("courtCorrespondence");
        builder.categories(UserRole.APPLICANT)
            .categoryID("courtCorrespondenceOther")
            .categoryLabel("Other")
            .displayOrder(216)
            .parentCategoryID("courtCorrespondence");
        builder.categories(UserRole.APPLICANT)
            .categoryID("hearingDocumentsWitnessSummons")
            .categoryLabel("Witness summons")
            .displayOrder(217)
            .parentCategoryID("hearingDocuments");
    }
}
