package uk.gov.hmcts.reform.finrem.caseorchestration.ccd;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.FinremCaseData;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 *
 * <p>The case-type and jurisdiction identity, definition flags and banner for {@code FinancialRemedyContested}.
 */
@Component
public class FinancialRemedyContestedCaseType implements CCDConfig<FinremCaseData, CcdState, UserRole> {
    /**
     * Configures the case-type and jurisdiction identity, definition flags and banner for {@code FinancialRemedyContested}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<FinremCaseData, CcdState, UserRole> builder) {
        builder.caseType("FinancialRemedyContested", "Contested Financial Remedy", "Contested Financial Remedy – Form A");
        builder.jurisdiction("DIVORCE", "Family Divorce", "Family Divorce: Dissolution of Marriage");
        builder.emitCaseRoleJurisdiction();
        builder.noCaseHistoryTab();
        builder.banner(false, "We apologise if this service is operating more slowly than usual. We're aware of this issue and we're working to fix it, so you don't need to contact us. We hope to fix this as soon as possible.", "", "");
        builder.explicitStateGrants();
        builder.includeCaseRolesInCaseTypeAuthorisation(UserRole.APPLICANT, UserRole.RESPONDENT, UserRole.APPSOLICITOR, UserRole.RESPSOLICITOR, UserRole.APPBARRISTER, UserRole.RESPBARRISTER);
    }
}
