package uk.gov.hmcts.reform.finrem.caseorchestration.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.finrem.caseorchestration.model.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from FinancialRemedyContested on migration; owned by this service team.
 */
public class CaseworkerDivorceFinancialremedyCourtadminRPlus1RolesYcfimvAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_COURTADMIN, Permission.R);
        grants.put(UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, Permission.C);
        grants.put(UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, Permission.R);
        grants.put(UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, Permission.U);
        grants.put(UserRole.CASEWORKER_DIVORCE_FINANCIALREMEDY_JUDICIARY, Permission.D);
        return grants;
    }
}
